### ISSUE TITLE
problems when running MultiQC on FastQC outputs

### ISSUE THREAD

**Issue by umnihi** [ewels/MultiQC#1034]
**Description of bug:**
When we run the MultiQC on FastQC output, we got stuck.  Please help.

**MultiQC Error log:**
```
~/.local/lib/python3.6/site-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. 
Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
~/.local/lib/python3.6/site-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. 
Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[WARNING] plotFingerprint : plotFingerprint_quality_metrics.tabular was initially flagged as the output from plotFingerprint --outQualityMetrics, but that seems to not be the case. Skippin
g...
[ERROR  ]         multiqc : Oops! The 'deeptools' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./Pkgs/deepTools-2.5.1/galaxy/wrapper/test-data/heatmapper_result2.tabular
============================================================
Module deeptools raised an exception: Traceback (most recent call last):
  File "~/.local/bin/multiqc", line 440, in multiqc
    output = mod()
  File "~/.local/lib/python3.6/site-packages/multiqc/modules/deeptools/deeptools.py", line 75, in __init__
    n['plotProfile'] = self.parse_plotProfile()
  File "~/.local/lib/python3.6/site-packages/multiqc/modules/deeptools/plotProfile.py", line 20, in parse_plotProfile
    parsed_data, bin_labels, converted_bin_labels = self.parsePlotProfileData(f)
  File "~/.local/lib/python3.6/site-packages/multiqc/modules/deeptools/plotProfile.py", line 83, in parsePlotProfileData
    step = int(abs(start/bin_labels.index('TSS')))
ValueError: 'TSS' is not in list
============================================================
[INFO   ]           macs2 : Found 2 logs
[ERROR  ]         multiqc : Oops! The 'gatk' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./.local/lib/python3.6/site-packages/multiqc/modules/gatk/varianteval.py
============================================================
Module gatk raised an exception: Traceback (most recent call last):
  File "~/.local/bin/multiqc", line 440, in multiqc
    output = mod()
  File "~/.local/lib/python3.6/site-packages/multiqc/modules/gatk/gatk.py", line 41, in __init__
    n_reports_found += self.parse_gatk_varianteval()
  File "/home/langlois/shens/.local/lib/python3.6/site-packages/multiqc/modules/gatk/varianteval.py", line 20, in parse_gatk_varianteval
    parsed_data = parse_single_report(f['f'])
  File "~/.local/lib/python3.6/site-packages/multiqc/modules/gatk/varianteval.py", line 106, in parse_single_report
    d[headers[i]] = s
IndexError: list index out of range
============================================================
[INFO   ]  feature_counts : Found 399 reports
[ERROR  ]         multiqc : Oops! The 'picard' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./.local/lib/python3.6/site-packages/multiqc/modules/picard/ValidateSamFile.pyc
============================================================
Module picard raised an exception: Traceback (most recent call last):
  File "~/.local/bin/multiqc", line 440, in multiqc
    output = mod()
  File "~/.local/lib/python3.6/site-packages/multiqc/modules/picard/picard.py", line 95, in __init__
    n['ValidateSamFile'] = ValidateSamFile.parse_reports(self)
  File "~/.local/lib/python3.6/site-packages/multiqc/modules/picard/ValidateSamFile.py", line 91, in parse_reports
    data = _parse_reports_by_type(self)
  File "~/.local/lib/python3.6/site-packages/multiqc/modules/picard/ValidateSamFile.py", line 125, in _parse_reports_by_type
    first_line = filehandle.readline().rstrip()
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 1: invalid continuation byte
============================================================
[INFO   ]        samtools : Found 1 flagstat reports
[INFO   ]        samtools : Found 1 rmdup reports
[INFO   ]            star : Found 28 reports
[INFO   ]         bowtie2 : Found 7 reports
[WARNING]        bargraph : Tried to make bar plot, but had no data
[INFO   ]         bowtie1 : Found 1 reports
[INFO   ]        cutadapt : Found 96 reports
[INFO   ]          fastqc : Found 126 reports
[WARNING]          fastqc : Multiple FastQC Theoretical GC Content files found, now using fastqc_theoretical_gc_hg38_txome.txt
[WARNING]          fastqc : Multiple FastQC Theoretical GC Content files found, now using fastqc_theoretical_gc_mm10_genome.txt
[WARNING]          fastqc : Multiple FastQC Theoretical GC Content files found, now using fastqc_theoretical_gc_mm10_txome.txt
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Previous MultiQC output found! Adjusting filenames..
[WARNING]         multiqc : Use -f or --force to overwrite existing reports instead
[INFO   ]         multiqc : Report      : multiqc_report_1.html
[INFO   ]         multiqc : Data        : multiqc_data_1
[INFO   ]         multiqc : MultiQC complete

```

**MultiQC run details (please complete the following):**
 ~/.local/bin/multiqc .

**Comment by ewels** [comment]
Hi @umnihi,

Were you running MultiQC in the directory that has the FastQC reports? You need to specify one or more directories or files to MultiQC. The logs suggest that you might be running it in a software installation directory though.

If you could provide more info on how you’re running MultiQC, that would help. 

Thanks,

Phil

**Comment by umnihi** [comment]
Thank you, Phil.

Here is the new error after changing to fastqc output directory.

~/.local/lib/python3.6/site-packages/multiqc/utils/config.py:45:
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as
the default Loader is unsafe. Please read https://msg.pyyaml.org/load for
full details.

  configs = yaml.load(f)

~/.local/lib/python3.6/site-packages/multiqc/utils/config.py:51:
YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as
the default Loader is unsafe. Please read https://msg.pyyaml.org/load for
full details.

  sp = yaml.load(f)

[INFO   ]         multiqc : This is MultiQC v1.7

[INFO   ]         multiqc : Template    : default

[INFO   ]         multiqc : Searching
'~/Dropbox/Langlois/Langlois_Project_017/outs/'

[INFO   ]          fastqc : Found 90 reports

[INFO   ]         multiqc : Compressing plot data

[WARNING]         multiqc : Previous MultiQC output found! Adjusting
filenames..

[WARNING]         multiqc : Use -f or --force to overwrite existing reports
instead

[INFO   ]         multiqc : Report      : multiqc_report_2.html

[INFO   ]         multiqc : Data        : multiqc_data_2

[INFO   ]         multiqc : MultiQC complete

**Comment by ewels** [comment]
Great! That’s not an error log, that’s just the log 😁 (the `YAMLLoadWarning` thing is just a warning from a dependency - it doesn’t affect the run at all).

Did you take a look at the HTML reports being produced?

**Comment by ewels** [comment]
Closing as there is no error here. Let me know if you have any problems.
