### ISSUE TITLE
multiqc memory error

### ISSUE THREAD

**Issue by Guan-Wang-123** [ewels/MultiQC#1122]
Hi,

I've been running multiqc v1.8 and received the following error information. I'm now reporting the traceback given the error message received below. I'm unsure what might have caused this and how to fix this.

```console
(/gpfs/ysm/project/fucito/gw344/conda_envs/multiqc_1.8) [gw344@farnam2 FASTQC_Illumina]$ multiqc .
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /gpfs/ysm/scratch60/fucito/gw344/multiqc_dataOutput/FASTQC_Illumina
Searching 1901 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    ./36_R1_fastqc/fastqc_data.txt
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/home/gw344/project/conda_envs/multiqc_1.8/lib/python3.7/site-packages/multiqc/multiqc.py", line 546, in run
    output = mod()
  File "/home/gw344/project/conda_envs/multiqc_1.8/lib/python3.7/site-packages/multiqc/modules/fastqc/fastqc.py", line 45, in __init__
    self.parse_fastqc_report(f['f'], s_name, f)
  File "/home/gw344/project/conda_envs/multiqc_1.8/lib/python3.7/site-packages/multiqc/modules/fastqc/fastqc.py", line 174, in parse_fastqc_report
    self.fastqc_data[s_name][section].append(row)
MemoryError
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

Thanks
Guan

**Comment by ewels** [comment]
Wow, impressive @Guan-Wang-123 - I don't think I've ever seen a Python `MemoryError` coming from MultiQC before, it's a new one!

Where are you running MultiQC? Do you have a very small amount of RAM available? Could it be that you are using a 32-bit installation of Python? (see https://stackoverflow.com/a/37726090/713980 )

**Comment by ewels** [comment]
ps. Sorry I didn't make this clear - the problem you're seeing is not really a bug in MultiQC as such, it's an error that Python raises when you run out of memory on your machine. See https://docs.python.org/3/library/exceptions.html#MemoryError

The simplest way to fix this is by giving more memory to MultiQC

**Comment by ewels** [comment]
Closing due to lack of response.
