### ISSUE TITLE
MultiQC module broke

### ISSUE THREAD

**Issue by paulacorell** [ewels/MultiQC#1123]
**Description of bug:**
Error installing MultiQC from scratch

**MultiQC Error log:**
```
[ERROR  ]         multiqc : Oops! The 'gatk' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./miniconda3/lib/python3.7/site-packages/multiqc/modules/gatk/varianteval.py
============================================================
Module gatk raised an exception: Traceback (most recent call last):
  File "/home/paula/miniconda3/lib/python3.7/site-packages/multiqc/multiqc.py", line 546, in run
    output = mod()
  File "/home/paula/miniconda3/lib/python3.7/site-packages/multiqc/modules/gatk/gatk.py", line 40, in __init__
    n_reports_found += self.parse_gatk_varianteval()
  File "/home/paula/miniconda3/lib/python3.7/site-packages/multiqc/modules/gatk/varianteval.py", line 20, in parse_gatk_varianteval
    parsed_data = parse_single_report(f['f'])
  File "/home/paula/miniconda3/lib/python3.7/site-packages/multiqc/modules/gatk/varianteval.py", line 106, in parse_single_report
    d[headers[i]] = s
IndexError: list index out of range
============================================================
[ERROR  ]         multiqc : Oops! The 'picard' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./miniconda3/lib/python3.7/site-packages/multiqc/modules/picard/ValidateSamFile.pyc
============================================================
Module picard raised an exception: Traceback (most recent call last):
  File "/home/paula/miniconda3/lib/python3.7/site-packages/multiqc/multiqc.py", line 546, in run
    output = mod()
  File "/home/paula/miniconda3/lib/python3.7/site-packages/multiqc/modules/picard/picard.py", line 94, in __init__
    n['ValidateSamFile'] = ValidateSamFile.parse_reports(self)
  File "/home/paula/miniconda3/lib/python3.7/site-packages/multiqc/modules/picard/ValidateSamFile.py", line 90, in parse_reports
    data = _parse_reports_by_type(self)
  File "/home/paula/miniconda3/lib/python3.7/site-packages/multiqc/modules/picard/ValidateSamFile.py", line 124, in _parse_reports_by_type
    first_line = filehandle.readline().rstrip()
  File "/home/paula/miniconda3/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 1: invalid continuation byte
```

**File that triggers the error:**
~$ pip install multiqc
~$ multiqc .

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: multiqc .
 - MultiQC Version: MultiQC v1.8
 - Operating System: Ubuntu 1.04.4 LTS
 - Python Version: Python 3.7
 - Method of MultiQC installation: pip

 **Additional context**

**Comment by ewels** [comment]
Hi @paulacorell,

It looks like you are running MultiQC on the installation directory instead of the folder that contains your data (you're [not the first to do this](https://github.com/ewels/MultiQC/issues/1027)).

Please start by reading the documentation‚ which tells you how to run MultiQC: https://multiqc.info/docs/#running-multiqc

Phil
