### ISSUE TITLE
table_columns_visible for a module gives error

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1149]
_Originally posted by @jamigo in https://github.com/ewels/MultiQC/issues/835#issuecomment-607349246_

_[repost by @ewels and minor edits]_

Relating to [#541 (comment)](https://github.com/ewels/MultiQC/issues/541#issuecomment-553392089)

it would be great to see this last option, but using MultiQC v1.8, although I can perfectly use this:
```yaml
table_columns_visible:
    fastp:
        pct_duplication: False
        after_filtering_q30_rate: False
        after_filtering_q30_bases: False
        after_filtering_gc_content: False
        pct_surviving: False
        pct_adapter: False
    FastQC:
        percent_duplicates: False
        percent_gc: False
        avg_sequence_length: False
        percent_fails: False
        total_sequences: False
```
unfortunately this is not working:
```yaml
table_columns_visible:
    fastp: False
    FastQC: False
```
in fact, I get the following error:
```python
Traceback (most recent call last):
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/bin/multiqc", line 11, in <module>
    load_entry_point('multiqc==1.8', 'console_scripts', 'multiqc')()
  File "/mnt/netapp1/Optcesga_FT2_RHEL7/easybuild-cesga/software/Compiler/gcccore/6.4.0/setuptools/40.4.3-python-3.7.0/lib/python3.7/site-packages/setuptools-40.4.3-py3.7.egg/pkg_resources/__init__.py", line 484, in load_entry_point
  File "/mnt/netapp1/Optcesga_FT2_RHEL7/easybuild-cesga/software/Compiler/gcccore/6.4.0/setuptools/40.4.3-python-3.7.0/lib/python3.7/site-packages/setuptools-40.4.3-py3.7.egg/pkg_resources/__init__.py", line 2714, in load_entry_point
  File "/mnt/netapp1/Optcesga_FT2_RHEL7/easybuild-cesga/software/Compiler/gcccore/6.4.0/setuptools/40.4.3-python-3.7.0/lib/python3.7/site-packages/setuptools-40.4.3-py3.7.egg/pkg_resources/__init__.py", line 2332, in load
  File "/mnt/netapp1/Optcesga_FT2_RHEL7/easybuild-cesga/software/Compiler/gcccore/6.4.0/setuptools/40.4.3-python-3.7.0/lib/python3.7/site-packages/setuptools-40.4.3-py3.7.egg/pkg_resources/__init__.py", line 2338, in resolve
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/multiqc-1.8-py3.7.egg/multiqc/__main__.py", line 44, in <module>
    multiqc.run_cli(prog_name='multiqc')
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/Click-7.0-py3.7.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/multiqc-1.8-py3.7.egg/multiqc/multiqc.py", line 238, in run_cli
    kwargs=kwargs
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/multiqc-1.8-py3.7.egg/multiqc/multiqc.py", line 303, in run
    config.mqc_load_userconfig(config_file)
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/multiqc-1.8-py3.7.egg/multiqc/utils/config.py", line 113, in mqc_load_userconfig
    mqc_load_config(p)
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/multiqc-1.8-py3.7.egg/multiqc/utils/config.py", line 123, in mqc_load_config
    mqc_add_config(new_config, yaml_config)
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/multiqc-1.8-py3.7.egg/multiqc/utils/config.py", line 179, in mqc_add_config
    update({c: v})
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/multiqc-1.8-py3.7.egg/multiqc/utils/config.py", line 210, in update
    return update_dict(globals(), u)
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/multiqc-1.8-py3.7.egg/multiqc/utils/config.py", line 217, in update_dict
    d[key] = update_dict(d.get(key, {}), val)
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/multiqc-1.8-py3.7.egg/multiqc/utils/config.py", line 217, in update_dict
    d[key] = update_dict(d.get(key, {}), val)
  File "/myhome/ngs/software/MultiQC-1.8/BUILD_FT/lib/python3.7/site-packages/multiqc-1.8-py3.7.egg/multiqc/utils/config.py", line 219, in update_dict
    d[key] = u[key]
TypeError: 'bool' object does not support item assignment
```

**Comment by ewels** [comment]
Hi @jamigo,

I've been trying to replicate this behaviour but I am unable to - for me your config file works fine (at least on MultiQC v1.9dev).

I'll close this now, as running on the MultiQC_TestData repo with the following config works fine for me and does what is expected:

```yaml
table_columns_visible:
    fastp: False
    FastQC: False
```

If you're still having problems, please zip up a set of reports and config file together which I can use to replicate the problem.

Phil
