### ISSUE TITLE
qualimap -- global name 'log' is not defined

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#116]
Got an error running master branch of multiqc on a folder with qualimap reports:
```
[ERROR  ]             mqc : Oops! The 'qualimap' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module qualimap raised an exception: Traceback (most recent call last):
  File "/data/home/user/bin/mqc", line 228, in multiqc
    report.modules_output.append(mod())
  File "/data/home/user/.local/lib/python2.7/site-packages/multiqc/modules/qualimap/qualimap.py", line 37, in __init__
    QM_BamQC.parse_reports(self)
  File "/data/home/user/.local/lib/python2.7/site-packages/multiqc/modules/qualimap/QM_BamQC.py", line 46, in parse_reports
    log.debug("Duplicate sample name found! Overwriting: {}".format(s_name))
NameError: global name 'log' is not defined
============================================================
```

Any ideas?

**Comment by ewels** [comment]
How recent is your code? I pushed a number of commits to this yesterday so just want to check before I start looking into this. (What's the last commit hash for you?)

**Comment by avilella** [comment]
It is a pip upgrade of your master branch from about 1 hour ago.

**Comment by ewels** [comment]
Ok, I managed to replicate it. Will have a look now.

**Comment by ewels** [comment]
That should do it - thanks for reporting!
