### ISSUE TITLE
Oops! The 'fastqc' MultiQC module broke...

### ISSUE THREAD

**Issue by drramkidrexel** [ewels/MultiQC#117]
Here is the log. This is with the latest dev version from github.

```
[INFO   ]         multiqc : Searching   : .
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_report_data
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/multiqc-0.3.2dev-py2.7.egg/EGG-INFO/scripts/multiqc", line 228, in multiqc
    report.modules_output.append(mod())
  File "/Library/Python/2.7/site-packages/multiqc-0.3.2dev-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 46, in __init__
    self.parse_fastqc_report(f['f'], s_name, f['root'])
  File "/Library/Python/2.7/site-packages/multiqc-0.3.2dev-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 234, in parse_fastqc_report
    self.fastqc_data['seq_dup_levels'][s_name][sections[0]] = float(sections[2])
IndexError: list index out of range
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
Thanks @drramkidrexel - could you send the FastQC report that generates this error? Or let me know what version of FastQC you're using..

Cheers,

Phil

**Comment by ewels** [comment]
Another user (Philipp) sent an example report to me which was causing this error - turns out that older versions of FastQC (v10) have a different data format for the Sequence Duplication section.

**Comment by ewels** [comment]
For future reference, this is from v0.11.2:
```
>>Sequence Duplication Levels	fail
#Total Deduplicated Percentage	28.36755889031817
#Duplication Level	Percentage of deduplicated	Percentage of total
1	69.96331592711988	19.84688484724508
2	10.191720965769685	5.782284893803237
3	4.650251790337494	3.95748874551619
4	2.4860861170090134	2.8209677732262244
```

..and this is from v.0.10.0:
```
>>Sequence Duplication Levels	fail
#Total Duplicate Percentage	81.84769994803247
#Duplication Level	Relative count
1	100.0
2	32.29868480530383
3	21.97731235335902
4	17.39027487784403
...
