### ISSUE TITLE
The 'somalier' MultiQC module broke

### ISSUE THREAD

**Issue by tdelhomme** [ewels/MultiQC#1220]
**Description of bug:**
Hi Phil,
I am trying to run multiqc from a qualimap output and I get the following error that I can't understand. Please note that the outputs `flagstat_report_data` and `flagstat_report.html` are correctly produced and present in the working folder.

**MultiQC Error log:**
```
[tdelhomme@fsupeksvr 62af337c31c3d9404880aae28ea651]$ cat .command.err 
[INFO   ]         multiqc : This is MultiQC v1.10.dev0
[INFO   ]         multiqc : Template    : default
[WARNING]         multiqc : You are running MultiQC with Python 2.7.5
[WARNING]         multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
[INFO   ]         multiqc : Searching   : /scratch/1/tdelhomme/nf-work/8d/62af337c31c3d9404880aae28ea651
[ERROR  ]         multiqc : Oops! The 'somalier' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module somalier raised an exception: Traceback (most recent call last):
  File "/home/tdelhomme/.local/lib/python2.7/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/home/tdelhomme/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/tdelhomme/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/tdelhomme/.local/lib/python2.7/site-packages/multiqc/modules/somalier/__init__.py", line 3, in <module>
    from .somalier import MultiqcModule
  File "/home/tdelhomme/.local/lib/python2.7/site-packages/multiqc/modules/somalier/somalier.py", line 698
    cols_return.append('rgba({},{},{},{})'.format(*cols_rgb, alpha))
SyntaxError: only named arguments may follow *expression
============================================================
[INFO   ]        qualimap : Found 44 BamQC reports
[INFO   ]        samtools : Found 44 flagstat reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_multiplex_qualimap_flagstat_report.html
[INFO   ]         multiqc : Data        : multiqc_multiplex_qualimap_flagstat_report_data
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
Please drag and drop (and upload to the GitHub issue) an input file that I can use to replicate the error.

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC:
```
#!/bin/bash -o pipefail
multiqc . -n multiqc_multiplex_qualimap_flagstat_report.html
```
 - MultiQC Version: MultiQC v1.10.dev0
 - Operating System: CentOS Linux 7 (Core)
 - Python Version: Python 2.7.5
 - Method of MultiQC installation: probably manually

 **Additional context**

**Comment by ewels** [comment]
Hmm, this may be one of the first Python 2k incompatibilities:

```
[WARNING]         multiqc : You are running MultiQC with Python 2.7.5
[WARNING]         multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
```

[Since v1.9](https://github.com/ewels/MultiQC/blob/master/CHANGELOG.md#dropped-official-support-for-python-2) MultiQC no longer officially supports Python 2k.

https://multiqc.info/docs/#python-2

I'll look into whether this particular issue can be fixed, but generally you should try to update to Python 3 if at all possible. Stuff like this is going to get more and more frequent from now on.

Phil

**Comment by tdelhomme** [comment]
Okay, I will try with python 3 and if I get any trouble I will let you know.
Thanks!
