### ISSUE TITLE
MultiQC failes with DRAGEN files

### ISSUE THREAD

**Issue by mjlarsen** [ewels/MultiQC#1223]
**Description of bug:**
Tried to use the new DRAGEN functionality. But it does not seems to work with the current DRAGEN version: v.3.5.7

**MultiQC Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /isilon/drift/drift-genom/dragen-run/09366
Searching 202 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'dragen' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    ./09366.germline.vc_metrics.csv
============================================================
Module dragen raised an exception: Traceback (most recent call last):
  File "/root/miniconda3/envs/gatk-germline/lib/python3.7/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/root/miniconda3/envs/gatk-germline/lib/python3.7/site-packages/multiqc/modules/dragen/dragen.py", line 41, in __init__
    samples_found |= self.add_vc_metrics()
  File "/root/miniconda3/envs/gatk-germline/lib/python3.7/site-packages/multiqc/modules/dragen/vc_metrics.py", line 23, in add_vc_metrics
    data = parse_vc_metrics_file(f)
  File "/root/miniconda3/envs/gatk-germline/lib/python3.7/site-packages/multiqc/modules/dragen/vc_metrics.py", line 204, in parse_vc_metrics_file
    data['Insertions'] = data['Insertions (Hom)'] + data['Insertions (Het)']
KeyError: 'Insertions (Hom)'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
@mjlarsen - Note that the log file says that `./09366.germline.vc_metrics.csv` was likely to be the problem here.
