### ISSUE TITLE
somalier breaks on python2.7

### ISSUE THREAD

**Issue by brentp** [ewels/MultiQC#1268]
here is a traceback:
```

[ERROR  ]         multiqc : Oops! The 'somalier' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module somalier raised an exception: Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/HIPAA/u6018242/anaconda3/lib/python2.7/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/uufs/chpc.utah.edu/common/HIPAA/u6018242/anaconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/uufs/chpc.utah.edu/common/HIPAA/u6018242/anaconda3/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/uufs/chpc.utah.edu/common/HIPAA/u6018242/anaconda3/lib/python2.7/site-packages/multiqc/modules/somalier/__init__.py", line 3, in <module>
    from .somalier import MultiqcModule
  File "/uufs/chpc.utah.edu/common/HIPAA/u6018242/anaconda3/lib/python2.7/site-packages/multiqc/modules/somalier/somalier.py", line 698
    cols_return.append('rgba({},{},{},{})'.format(*cols_rgb, alpha))
SyntaxError: only named arguments may follow *expression
```

where: `    cols_return.append('rgba({},{},{},{})'.format(*cols_rgb, alpha))` is not supported in python < 3.

**Comment by ewels** [comment]
Hi @brentp,

Sorry for the slow response! MultiQC no longer supports Python 2k, since version 1.9. See the changelog and docs: https://multiqc.info/docs/#python-2

Phil
