### ISSUE TITLE
The 'somalier' MultiQC module broke - Salmon plot not generated in report

### ISSUE THREAD

**Issue by dBenedek** [ewels/MultiQC#1269]
**Description of bug:** MultiQC somalier module broke when running MultiQC on FastQC, Salmon, Kallisto, STAR output files with Python version 2.7. Despite output files are generated, **Salmon** plot is missing.

**MultiQC Error log:**

```
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[WARNING]         multiqc : You are running MultiQC with Python 2.7.17
[WARNING]         multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS10_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS10_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS11_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS11_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS12_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS12_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS13_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS13_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS14_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS14_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS15_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS15_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS16_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS16_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS17_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS17_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS18_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS18_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS19_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS19_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS1_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS1_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS20_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS20_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS2_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS2_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS3_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS3_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS4_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS4_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS5_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS5_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS6_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS6_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS7_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS7_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS8_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS8_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS9_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/MDS9_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/control1_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/control1_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/control2_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/control2_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/control3_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/control3_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/control4_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/control4_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/control5_1_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/qc/fastqc/control5_2_fastqc.zip
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS10_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS11_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS12_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS13_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS14_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS15_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS16_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS17_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS18_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS19_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS1_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS20_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS2_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS3_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS4_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS5_corrected_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS6_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS7_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS8_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/MDS9_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/control1_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/control2_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/control3_corrected_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/control4_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/alignment/STAR/control5_Log.final.out
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS10_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS11_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS12_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS13_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS14_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS15_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS16_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS17_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS18_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS19_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS1_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS20_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS2_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS3_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS4_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS5_corrected_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS5_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS6_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS7_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS8_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/MDS9_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/control1_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/control2_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/control3_corrected_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/control3_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/control4_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/salmon/control5_quant
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS1
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS10
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS11
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS12
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS13
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS14
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS15
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS16
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS17
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS18
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS19
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS2
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS20
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS3
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS4
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS5
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS5_corrected
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS6
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS7
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS8
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/MDS9
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/control1
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/control2
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/control3
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/control3_corrected
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/control4
[INFO   ]         multiqc : Searching   : /home/bd1/mds-datasets/dataset1/expression/kallisto/control5
Searching 3312 files..  [####################################]  100%          
[ERROR  ]         multiqc : Oops! The 'somalier' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module somalier raised an exception: Traceback (most recent call last):
  File "/home/bd1/.local/lib/python2.7/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/home/bd1/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/bd1/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/bd1/.local/lib/python2.7/site-packages/multiqc/modules/somalier/__init__.py", line 3, in <module>
    from .somalier import MultiqcModule
  File "/home/bd1/.local/lib/python2.7/site-packages/multiqc/modules/somalier/somalier.py", line 698
    cols_return.append('rgba({},{},{},{})'.format(*cols_rgb, alpha))
SyntaxError: only named arguments may follow *expression
============================================================
[INFO   ]          salmon : Found 25 meta reports
[INFO   ]        kallisto : Found 27 reports
[INFO   ]            star : Found 25 reports
[INFO   ]          fastqc : Found 50 reports
[INFO   ]         multiqc : Compressing plot data
[WARNING]         multiqc : Previous MultiQC output found! Adjusting filenames..
[WARNING]         multiqc : Use -f or --force to overwrite existing reports instead
[INFO   ]         multiqc : Report      : dataset1_combined_multiqc_1.html
[INFO   ]         multiqc : Data        : dataset1_combined_multiqc_data_1
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**

**MultiQC run details (please complete the following):**
* Command used to run MultiQC:  `multiqc -n dataset1_combined_multiqc /home/bd1/mds-datasets/dataset1/qc/fastqc/*zip /home/bd1/mds-datasets/dataset1/alignment/STAR/*Log.final.out /home/bd1/mds-datasets/dataset1/expression/salmon/* /home/bd1/mds-datasets/dataset1/expression/kallisto/*`
* MultiQC Version:  MultiQC v1.9
* Operating System:  Ubuntu 18.04.5 LTS
* Python Version:  Python 2.7
* Method of MultiQC installation:  pip

**Additional context**
 There is a generated MultiQC html output file, only the Salmon module is missing. Salmon version: 1.2.1. Salmon dir structure: 
```
salmon  
│
└───sample1
 │        │    cmd_info.json
 │        │    quant.sf
         │
         └─── aux_info ...
         │
         └─── logs ...
         │
         └─── libParams ...
```

**Comment by ewels** [comment]
Hi @dBenedek,

Sorry for the slow response. MultiQC no longer supports Python 2. Note the warning at the top of the log messages, plus the release changelog Ns docs: https://multiqc.info/docs/#python-2

If you upgrade to Python 3 then your error should be resolved.

Phil
