### ISSUE TITLE
Deeptools IndexError

### ISSUE THREAD

**Issue by martindemko** [ewels/MultiQC#1275]
**Description of bug:**

**MultiQC Error log:**

```python
Module deeptools raised an exception: Traceback (most recent call last):
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/54d73197/lib/python3.6/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/54d73197/lib/python3.6/site-packages/multiqc/modules/deeptools/deeptools.py", line 74, in __init__
    n['plotProfile'] = self.parse_plotProfile()
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/54d73197/lib/python3.6/site-packages/multiqc/modules/deeptools/plotProfile.py", line 17, in parse_plotProfile
    parsed_data, bin_labels, converted_bin_labels = self.parsePlotProfileData(f)
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/54d73197/lib/python3.6/site-packages/multiqc/modules/deeptools/plotProfile.py", line 111, in parsePlotProfileData
    d[s_name].update({converted_bin_labels[i-1]:float(cols[i+1])})
IndexError: range object index out of range
```

**File that triggers the error:**

Sorry, couldn't drop the input file.
Here is the log file:
[multiqc.log](https://github.com/ewels/MultiQC/files/5096639/multiqc.log)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: 
* MultiQC Version: 
* Operating System: 
* Python Version: 
* Method of MultiQC installation: 

**Additional context**

**Comment by martindemko** [comment]
[input.zip](https://github.com/ewels/MultiQC/files/5096693/input.zip)
input data - table from deeptools plotProfile using --outFileNameData

**Comment by ewels** [comment]
Sorry for the delay in getting to this. I think it's now fixed. The code had a `-1` in it that, if removed, solved the issue. I'm not entirely clear on why it was there in the first place, which always makes me a little nervous, but I can't see any differences in the outputs before and after the change in my other test data so hopefully it's fine.

Thanks for reporting + sending the test data. Let me know if you hit any other issues 👍🏻
