### ISSUE TITLE
MultiQC module broke... 

### ISSUE THREAD

**Issue by scijrb** [ewels/MultiQC#1286]
**Description of bug:**
When trying to run multiqc it throws an error message saying the following:

**MultiQC Error log:**

```console
(base) MacBook-Pro-de-Javier:RNAseq_MAP_2020 Javi$ multiqc -f -d /Users/Javi/Desktop/RNAseq_MAP_2020
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Prepending directory to sample names
[INFO   ]         multiqc : Searching   : /Users/Javi/Desktop/RNAseq_MAP_2020
Searching 123 files..  [####################################]  100%          
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/Users/Javi/opt/anaconda3/lib/python3.7/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/Users/Javi/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/Users/Javi/opt/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'multiqc.modules.fastqc'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
(base) MacBook-Pro-de-Javier:RNAseq_MAP_2020 Javi$
```

**File that triggers the error:**

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: 
* MultiQC Version: 
* Operating System: 
* Python Version: 
* Method of MultiQC installation: 

**Additional context**

**Comment by ewels** [comment]
Hi @scijrb,

Sorry for the slow reply. This looks like a strange installation problem. Given my delay in replying and the lack of detail I will close this issue now. However, if it is still a problem then please create a new issue and fill in all of the fields in the template such as installation method and so on.

Phil
