### ISSUE TITLE
The 'phantompeakqualtools' MultiQC module broke...

### ISSUE THREAD

**Issue by martindemko** [ewels/MultiQC#1295]
Hello,
this is actually kind of my fault because I added a header as the first line of the file with the description of columns starting with the hashtag as an ordinary commentary:

**\#Name\tNumMappedReads\tEstFragLen\tEstFragLenCorr\tReadLen\tReadLenCorr\tMinCrossCorrInsertSize\tMinCrossCorrValue\tNSC\tRSC\tQTag**

The problem here is that your script for parsing the phantompeakqualtools output expects no header line, but it could be to a general benefit just to add a line to ignore all lines starting with the hashtag.

I can easily change the script on my side but then it won't be reproducible elsewhere.

What do you think?

```
Module phantompeakqualtools raised an exception: Traceback (most recent call last):
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/54d73197/lib/python3.6/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/54d73197/lib/python3.6/site-packages/multiqc/modules/phantompeakqualtools/phantompeakqualtools.py", line 27, in __init__
    self.parse_phantompeakqualtools(f)
  File "/mnt/ssd/ssd_1/snakemake/.snakemake/conda/54d73197/lib/python3.6/site-packages/multiqc/modules/phantompeakqualtools/phantompeakqualtools.py", line 52, in parse_phantompeakqualtools
    parsed_data['Estimated_Fragment_Length_bp'] = int(s[2].split(",")[0])
ValueError: invalid literal for int() with base 10: 'EstFragLen'
```

**Comment by ewels** [comment]
Hi @martindemko,

I'm not sure about skipping comment lines, but tolerating unexpected lines at least a few times is usually not a bad idea. Given that this is only a problem when people manually add these extra lines in however, I don't see it as a particularly high priority..

Phil
