### ISSUE TITLE
deeptools module broke traceback

### ISSUE THREAD

**Issue by lianov** [ewels/MultiQC#1317]
**Description of bug:**

Upon running multiqc with outputs from `deeptools` `plotProfile` the following appears. Also with the `fingerprint` QC, while MultiQC is detecting the metrics data, it's not plotting the actual fingerprint plot.

**MultiQC Error log:**

```
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /scratch/lianov/BAM_ATAC_sample/deeptools_test/multiqc_outs
[ERROR  ]         multiqc : Oops! The 'deeptools' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    ./plotProfile_data.txt
============================================================
Module deeptools raised an exception: Traceback (most recent call last):
  File "/scratch/lianov/latest_bowtie2_env/lib/python3.6/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/scratch/lianov/latest_bowtie2_env/lib/python3.6/site-packages/multiqc/modules/deeptools/deeptools.py", line 74, in __init__
    n['plotProfile'] = self.parse_plotProfile()
  File "/scratch/lianov/latest_bowtie2_env/lib/python3.6/site-packages/multiqc/modules/deeptools/plotProfile.py", line 17, in parse_plotProfile
    parsed_data, bin_labels, converted_bin_labels = self.parsePlotProfileData(f)
  File "/scratch/lianov/latest_bowtie2_env/lib/python3.6/site-packages/multiqc/modules/deeptools/plotProfile.py", line 106, in parsePlotProfileData
    step = self._int(abs(start/bin_labels.index('TSS')))
UnboundLocalError: local variable 'start' referenced before assignment
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**

(attached at the end of message)
**MultiQC run details (please complete the following):**
* Command used to run MultiQC:  `multiqc .`
* MultiQC Version:  MultiQC v1.9
* Operating System:   Red Hat Enterprise Linux 7 (HPC cluster)
* Python Version:   Python 3.6.10

* Method of MultiQC installation:  conda

**Additional context**

version of `deeptools`: 3.5.0 (also tried with 3.4.3, and same error appeared).

[fingerprint_metrics.txt](https://github.com/ewels/MultiQC/files/5351529/fingerprint_metrics.txt)
[fingerprint.txt](https://github.com/ewels/MultiQC/files/5351530/fingerprint.txt)
[plotProfile_data.txt](https://github.com/ewels/MultiQC/files/5351531/plotProfile_data.txt)

**Comment by ewels** [comment]
Hi @lianov,

Thanks for reporting this. I just had a look and I think that it's because your `plotProfile_data.txt` file doesn't include the upstream and downstream regions around the gene. The module code assumes that these exist and so crashes when it can't find them.

I've just pushed a fix which handles this exception when it happens and keeps the module running. I've tested with the example data that you sent and I think that the report looks sane still:

![read_distribution_profile](https://user-images.githubusercontent.com/465550/113217473-4bca0f00-927e-11eb-92f0-b8ecc54a66fc.png)

Please do test though and let me know if you hit any issues 👍🏻 

Thanks for reporting!
