### ISSUE TITLE
Error running multiqc

### ISSUE THREAD

**Issue by kopeckyl** [ewels/MultiQC#1322]
Hello I am having some issues running multiqc

I install multiqc using `pip install multiqc` and I am also using python 3.8 on Ubuntu 20.04. Here is the error I am getting:

```
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/tranel/lucas/CHR_RNAseq/raw_data/fastqc_reports
Traceback (most recent call last):
  File "/home/tranel/.local/bin/multiqc", line 5, in <module>
    from multiqc.__main__ import multiqc
  File "/home/tranel/.local/lib/python3.8/site-packages/multiqc/__main__.py", line 44, in <module>
    multiqc.run_cli(prog_name='multiqc')
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tranel/.local/lib/python3.8/site-packages/multiqc/multiqc.py", line 215, in run_cli
    multiqc_run = run(
  File "/home/tranel/.local/lib/python3.8/site-packages/multiqc/multiqc.py", line 538, in run
    template_mod = config.avail_templates[config.template].load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2444, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2467, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (networkx 1.11 (/home/tranel/.local/lib/python3.8/site-packages), Requirement.parse('networkx>=2.0'), {'colormath'})
```

Any ideas why this is happening?

**Comment by ewels** [comment]
Hi @kopeckyl,

Something odd has happened with your installation and you have conflicting packages as mentioned in the final line of the log. You have `networkx 1.11` installed, but the `colormath` package (used by MultiQC) requires `networkx>=2.0`.

If you upgrade `networkx` I guess that you should be ok:

```
pip install --upgrade networkx
```

Phil
