### ISSUE TITLE
Runtime error - somalier  module broke

### ISSUE THREAD

**Issue by atks** [ewels/MultiQC#1331]
**Description of bug:**

Runtime error when invoking multiqc 1.9 on mac OSX catalina.
-->

```
**MultiQC Error log:**
<!--
============================================================
Module somalier raised an exception: Traceback (most recent call last):
  File "/Users/adriantks/Library/Python/2.7/lib/python/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/adriantks/Library/Python/2.7/lib/python/site-packages/multiqc/modules/somalier/__init__.py", line 3, in <module>
    from .somalier import MultiqcModule
  File "/Users/adriantks/Library/Python/2.7/lib/python/site-packages/multiqc/modules/somalier/somalier.py", line 698
    cols_return.append('rgba({},{},{},{})'.format(*cols_rgb, alpha))
SyntaxError: only named arguments may follow *expression
============================================================
```

**File that triggers the error:**

**MultiQC run details (please complete the following):**
* Command used to run MultiQC:   multiqc in_dir -ip -o out_dir
* MultiQC Version: v1.9
* Operating System:  macOS CatalinaSierra 10.15.7
* Python Version: Python 2.7
* Method of MultiQC installation:pip

**Comment by ewels** [comment]
Hi @atks,

You will have truncated a line from the MultiQC log which looks like this:

```
[WARNING]         multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
```

This is a Python 2k compatibility issue and will not be fixed. Please upgrade to Python 3 instead.

Dup of #1269 and #1268

Phil
