### ISSUE TITLE
ZeroDivisionError in kraken module

### ISSUE THREAD

**Issue by davidealbanese** [ewels/MultiQC#1346]
**Description of bug:**
MultiQC returns a Python ZeroDivisionError on some kraken2 reports. 

**MultiQC Error log:**

```
[INFO   ]         multiqc : This is MultiQC v1.9
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /nfs2/albanesed/test
[INFO   ]          kraken : Found 1 reports
[ERROR  ]         multiqc : Oops! The 'kraken' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./sample2.report
============================================================
Module kraken raised an exception: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/usr/lib/python3.8/site-packages/multiqc/modules/kraken/kraken.py", line 60, in __init__
    self.sum_sample_counts()
  File "/usr/lib/python3.8/site-packages/multiqc/modules/kraken/kraken.py", line 134, in sum_sample_counts
    self.kraken_sample_total_readcounts[s_name] = round(float(row['counts_rooted']) / (row['percent'] / 100.0))
ZeroDivisionError: float division by zero
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**
[kraken_reports.tar.gz](https://github.com/ewels/MultiQC/files/5560265/kraken_reports.tar.gz)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC:  `multiqc .`
* MultiQC Version:  1.9
* Operating System:  NA (`singularity shell docker://ewels/multiqc:1.9`)
* Python Version:  NA
* Method of MultiQC installation:  NA

**Additional context**

**Comment by davidealbanese** [comment]
Related to #1276.
