### ISSUE TITLE
The 'fgbio' MultiQC module broke

### ISSUE THREAD

**Issue by chelauk** [ewels/MultiQC#1353]
**Description of bug:**

fgbio module of MultiQC breaks

**MultiQC Error log:**

```python
If possible, please include a log file that triggers the error - the last file found was:
    ./patient1_sample_1_st1_qc.error_rate_by_read_position.txt
============================================================
Module fgbio raised an exception: Traceback (most recent call last):
  File "/Users/cjames/miniconda3/envs/py3.8/lib/python3.8/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/Users/cjames/miniconda3/envs/py3.8/lib/python3.8/site-packages/multiqc/modules/fgbio/fgbio.py", line 40, in __init__
    n['errorratebyreadposition'] = ErrorRateByReadPosition.parse_reports(self)
  File "/Users/cjames/miniconda3/envs/py3.8/lib/python3.8/site-packages/multiqc/modules/fgbio/ErrorRateByReadPosition.py", line 34, in parse_reports
    fields[4:] = [float(field) for field in fields[4:]]
  File "/Users/cjames/miniconda3/envs/py3.8/lib/python3.8/site-packages/multiqc/modules/fgbio/ErrorRateByReadPosition.py", line 34, in <listcomp>
    fields[4:] = [float(field) for field in fields[4:]]
ValueError: could not convert string to float: ''
============================================================

```

**File that triggers the error:**

[patient1_sample_1_st1_qc.error_rate_by_read_position.txt](https://github.com/ewels/MultiQC/files/5658152/patient1_sample_1_st1_qc.error_rate_by_read_position.txt)

**MultiQC run details (please complete the following):**
* Command used to run MultiQC: 

`multiqc -f  . --config multiqc_config.yaml`

* MultiQC Version:

MultiQC v1.9

* Operating System:

macOS Mojave 10.14.6

* Python Version:

Python 3.8.5

* Method of MultiQC installation:

pip

**Additional context** 

ran within nextflow pipeline. fastqc and picard hs_metrics worked fine

**Comment by ewels** [comment]
Hi @chelauk,

I just tried your file locally and it worked fine:

```console
$  multiqc ../patient1_sample_1_st1_qc.error_rate_by_read_position.txt
[INFO   ]         multiqc : This is MultiQC v1.10.dev0 (8df26af)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /Users/ewels/Downloads/patient1_sample_1_st1_qc.error_rate_by_read_position.txt
[INFO   ]           fgbio : Found 1 errorratebyreadposition reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

Report: [multiqc_report.html.zip](https://github.com/ewels/MultiQC/files/5749093/multiqc_report.html.zip)

So I guess that this error has already been fixed in MultiQC v1.10dev. This isn't released yet, but you can install the development version as follows:

```
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

Phil
