### ISSUE TITLE
No space left on device error with big sample sets.

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [ewels/MultiQC#1356]
**Description of bug:**
When using MultiQC on a cluster, big sample sets can fill up the /tmp folder of the node where the job runs, leading to crashes or empty output files.

**MultiQC Error log:**

```
/usr/local/lib/python3.8/site-packages/networkx/convert_matrix.py:567: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if python_type is 'void':
/usr/local/lib/python3.8/site-packages/networkx/drawing/nx_pydot.py:210: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if name is '':
[WARNING]         multiqc : MultiQC Version v1.9 now available!
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /path/to/folder/multiqc_report/multiqc_data
[INFO   ]         multiqc : Searching   : /path/to/folder/
/usr/local/lib/python3.8/site-packages/multiqc/modules/custom_content/custom_content.py:65: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  cust_mods[c_id]['config'].update( { k:v for k, v in f.items() if k is not 'data' } )
[INFO   ] base_recalibrator : Found 32 BaseRecalibrator reports
[INFO   ]          picard : Found 32 AlignmentSummaryMetrics reports
[INFO   ]          picard : Found 64 BaseDistributionByCycleMetrics reports
[INFO   ]          picard : Found 32 HsMetrics reports
[INFO   ]          picard : Found 32 InsertSizeMetrics reports
[INFO   ]          picard : Found 32 MarkDuplicates reports
[INFO   ]          fastqc : Found 64 reports
[INFO   ]         multiqc : Compressing plot data
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import multiqc
  File "/usr/local/lib/python3.8/site-packages/multiqc/__main__.py", line 44, in <module>
    multiqc.run_cli(prog_name='multiqc')
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/multiqc/multiqc.py", line 204, in run_cli
    sys_exit_code = run(
  File "/usr/local/lib/python3.8/site-packages/multiqc/multiqc.py", line 699, in run
    util_functions.write_data_file(multiqc_json_dump, 'multiqc_data', False, 'json')
  File "/usr/local/lib/python3.8/site-packages/multiqc/utils/util_functions.py", line 71, in write_data_file
    print( jsonstr.encode('utf-8', 'ignore').decode('utf-8'), file=f)
OSError: [Errno 28] No space left on device
```

**Workaround**
Manually set the temp folder for MultiQC (i.e. python) to another folder, for example on a shared filesystem, by using `export TMPDIR=tmp`

Maybe this issue can be fixed or made more explicit by adding a `--temp-folder` argument to MultiQC?

**Comment by ewels** [comment]
Wow, how big are your runs / how small is your `/tmp` folder? I've never seen this before 😅 

I'm not sure that this is a common enough problem to warrant a new command line option (plus the workaround is pretty simple), but I've added it to the troubleshooting documentation to help anyone else who might run into this in the future.

Thanks for reporting this! 👍🏻 

Phil

**Comment by Redmar-van-den-Berg** [comment]
This happened to me on our HPC cluster, so I don't even know how small the `/tmp` folder is on some nodes, might just be a few kb.

Thanks for adding this to the documentation, that should be enough for people to solve it when they run into this issue. It took me quite some time to figure it out.
