### ISSUE TITLE
MultiQC Error on Dragen with Single-end reads

### ISSUE THREAD

**Issue by pchitsutti** [ewels/MultiQC#1374]
**Description of bug:**

Multiqc error upon reading Dragen metric file.
The samples there are single-end reads.

**MultiQC Error log:**

```

[INFO   ]         multiqc : This is MultiQC v1.10.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /gpfs/gpfs1/dls/apex/uat_data/analysis/apex/SINGLEREAD/haib20TEST01/SRqconly/batch_1/results
[ERROR  ]         multiqc : Oops! The 'dragen' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    /gpfs/gpfs1/dls/apex/uat_data/analysis/apex/SINGLEREAD/haib20TEST01/SRqconly/batch_1/results/6405-JL-0001_111/metrics/6405-JL-0001_111.mapping_metrics.csv
============================================================
Module dragen raised an exception: Traceback (most recent call last):
  File "/gpfs/gpfs1/dls/home/apex/.local/lib/python3.6/site-packages/multiqc/multiqc.py", line 579, in run
    output = mod()
  File "/gpfs/gpfs1/dls/home/apex/.local/lib/python3.6/site-packages/multiqc/modules/dragen/dragen.py", line 78, in __init__
    samples_found |= self.add_mapping_metrics()
  File "/gpfs/gpfs1/dls/home/apex/.local/lib/python3.6/site-packages/multiqc/modules/dragen/mapping_metrics.py", line 56, in add_mapping_metrics
    self.report_mapping_metrics(data_by_sample, data_by_rg_by_sample)
  File "/gpfs/gpfs1/dls/home/apex/.local/lib/python3.6/site-packages/multiqc/modules/dragen/mapping_metrics.py", line 87, in report_mapping_metrics
    plot=table.plot(data_by_rg, own_tabl_headers, pconfig={"namespace": NAMESPACE}),
  File "/gpfs/gpfs1/dls/home/apex/.local/lib/python3.6/site-packages/multiqc/plots/table.py", line 53, in plot
    return make_table(dt)
  File "/gpfs/gpfs1/dls/home/apex/.local/lib/python3.6/site-packages/multiqc/plots/table.py", line 157, in make_table
    val = header["modify"](val)
  File "/gpfs/gpfs1/dls/home/apex/.local/lib/python3.6/site-packages/multiqc/modules/dragen/utils.py", line 111, in <lambda>
    col["modify"] = lambda x: x * config.base_count_multiplier
TypeError: can't multiply sequence by non-int of type 'float'
============================================================
[INFO   ]          fastqc : Found 92 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_report_data
[INFO   ]         multiqc : MultiQC complete


```

**File that triggers the error:**

[6405-JL-0001_111.mapping_metrics.csv.zip](https://github.com/ewels/MultiQC/files/5993947/6405-JL-0001_111.mapping_metrics.csv.zip)

The samples there are single-end reads so the metric files have 'NA' in R2 value.
Maybe this is the cause?

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: multiqc ./results -f -n ./results/multiqc_report.html -o ./results/multiqc_report
- MultiQC Version: 1.10.dev0
- Operating System: CentOS 7.7.190
- Python Version: Python 3.6.7
- Method of MultiQC installation: pip

**Additional context**

**Comment by ewels** [comment]
Fixed in #1465 ✅ 

Thanks for reporting @pchitsutti !
