### ISSUE TITLE
sortmerna module broke

### ISSUE THREAD

**Issue by rebeelouise** [ewels/MultiQC#1378]
**Description of bug:**

MultiQC was ran to assess sortmerna outputs

**MultiQC Error log:**
```console
hlrpenri@borgcube:~/projects/sispa_sisters/COVID/trimmed_fastq/sortmerna$ multiqc .
[WARNING]         multiqc : MultiQC Version v1.9 now available!
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[WARNING]         multiqc : You are running MultiQC with Python 2.7.18
[WARNING]         multiqc : Please upgrade! MultiQC will soon drop support for Python < 3.6
[INFO   ]         multiqc : Searching   : /home/hlrpenri/projects/sispa_sisters/COVID/trimmed_fastq/sortmerna
Searching 10243 files..  [####################################]  100%          
[ERROR  ]         multiqc : Oops! The 'sortmerna' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./trimmed_SISPA_822-blank_barcode09/out/aligned.log
============================================================
Module sortmerna raised an exception: Traceback (most recent call last):
  File "/home/hlrpenri/miniconda2/lib/python2.7/site-packages/multiqc/multiqc.py", line 546, in run
    output = mod()
  File "/home/hlrpenri/miniconda2/lib/python2.7/site-packages/multiqc/modules/sortmerna/sortmerna.py", line 30, in __init__
    self.parse_sortmerna(f)
  File "/home/hlrpenri/miniconda2/lib/python2.7/site-packages/multiqc/modules/sortmerna/sortmerna.py", line 85, in parse_sortmerna
    self.sortmerna[s_name]["rRNA_pct"] = float(self.sortmerna[s_name]["rRNA"]) / float(self.sortmerna[s_name]["total"]) * 100
KeyError: 'total'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**File that triggers the error:**

[aligned.log](https://github.com/ewels/MultiQC/files/6004919/aligned.log)

**MultiQC run details (please complete the following):**

- Command used to run MultiQC:   multiqc .
- MultiQC Version:  multiqc, version 1.8
- Operating System:  linux
- Python Version:  Python 2.7.18 :: Anaconda, Inc.
- Method of MultiQC installation:  conda

**Comment by rebeelouise** [comment]
I have resolved this by installing multiqc in my python3 environment (https://salishsea-meopar-docs.readthedocs.io/en/latest/work_env/python3_conda_environment.html) - allowing for the installation of the latest version of multiQC which does not throw the same error and produces the QC reports.

**Comment by ewels** [comment]
Great, glad you got it working!
