### ISSUE TITLE
Error converting string to float

### ISSUE THREAD

**Issue by fgvieira** [ewels/MultiQC#1394]
**Description of bug:**

When running MultiQC on the attached file, I get an error that `could not convert string to float: '1.6-05'`, even though that string is not in the file.

**MultiQC Error log:**

```
[2021-03-14 22:10:41,971] multiqc.modules.gatk.base_recalibrator             [INFO   ]  Found 1 BaseRecalibrator reports
[2021-03-14 22:10:41,984] multiqc.modules.gatk.varianteval                   [INFO   ]  Found 2 VariantEval reports
[2021-03-14 22:10:41,995] multiqc                                            [ERROR  ]  Oops! The 'gatk' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    stats/variants/eval/haplotypecaller/g1_haplotypecaller.grp
============================================================
Module gatk raised an exception: Traceback (most recent call last):
  File "NGS/cache/conda/cdb5388f0bf10908b0f9ac2db2399a42/lib/python3.9/site-packages/multiqc/multiqc.py", line 579, in run
    output = mod()
  File "NGS/cache/conda/cdb5388f0bf10908b0f9ac2db2399a42/lib/python3.9/site-packages/multiqc/modules/gatk/gatk.py", line 42, in __init__
    n_reports_found += self.parse_gatk_varianteval()
  File "NGS/cache/conda/cdb5388f0bf10908b0f9ac2db2399a42/lib/python3.9/site-packages/multiqc/modules/gatk/varianteval.py", line 85, in parse_gatk_varianteval
    name="Compare Overlap", anchor="gatk-compare-overlap", plot=comp_overlap_table(self.gatk_varianteval)
  File "NGS/cache/conda/cdb5388f0bf10908b0f9ac2db2399a42/lib/python3.9/site-packages/multiqc/modules/gatk/varianteval.py", line 267, in comp_overlap_table
    table_html = table.plot(data, headers, {"id": "gatk_compare_overlap", "table_title": "GATK - Compare Overlap"})
  File "NGS/cache/conda/cdb5388f0bf10908b0f9ac2db2399a42/lib/python3.9/site-packages/multiqc/plots/table.py", line 53, in plot
    return make_table(dt)
  File "NGS/cache/conda/cdb5388f0bf10908b0f9ac2db2399a42/lib/python3.9/site-packages/multiqc/plots/table.py", line 138, in make_table
    c_scale = mqc_colour.mqc_colour_scale(header["scale"], header["dmin"], header["dmax"])
  File "NGS/cache/conda/cdb5388f0bf10908b0f9ac2db2399a42/lib/python3.9/site-packages/multiqc/utils/mqc_colour.py", line 33, in __init__
    if float(minval) == float(maxval):
ValueError: could not convert string to float: '1.6-05'
============================================================
```

**File that triggers the error:**

[g1_freebayes.grp.txt](https://github.com/ewels/MultiQC/files/6137601/g1_freebayes.grp.txt)

(not sure if it matters, but added extension `.txt` to upload)

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: `multiqc --force -o reports -n multiqc_variants_report.html stats/variants/eval/haplotypecaller/`
- MultiQC Version: `MultiQC v1.10`
- Operating System: `CentOS`
- Python Version: `Python 3.9`
- Method of MultiQC installation: `conda`

**Comment by Zymergen-phaverty** [comment]
I get the same error, FWIW.

**Comment by ewels** [comment]
Thanks for reporting - I fixed this almost immediately after the release in 391809fae1b38bfa0aa83626acdb9166f0f63228 so if you install v1.11dev it should hopefully be fixed.

I think I might release a patch release in the coming days to fix this and one or two other minor bugs that showed up. 

Phil
