### ISSUE TITLE
Error with Picard module

### ISSUE THREAD

**Issue by beboche** [ewels/MultiQC#1399]
**Description of bug:**

[ERROR  ]         multiqc : Oops! The 'picard' MultiQC module broke... 

**MultiQC Error log:**

```

[ERROR  ]         multiqc : Oops! The 'picard' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    /softs/MobiDL/tmp_output/201016_MN00265_0334_A000H35MTF/SU7144/panelCapture/PicardQualityDir/SU7144_hs_metrics.txt
============================================================
Module picard raised an exception: Traceback (most recent call last):
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/multiqc.py", line 579, in run
    output = mod()
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/modules/picard/picard.py", line 73, in __init__
    n["HsMetrics"] = HsMetrics.parse_reports(self)
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/modules/picard/HsMetrics.py", line 179, in parse_reports
    self.add_section(name="HSMetrics", anchor="picard_hsmetrics", plot=table.plot(data, _get_table_headers(data)))
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/plots/table.py", line 53, in plot
    return make_table(dt)
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/plots/table.py", line 138, in make_table
    c_scale = mqc_colour.mqc_colour_scale(header["scale"], header["dmin"], header["dmax"])
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/utils/mqc_colour.py", line 33, in __init__
    if float(minval) == float(maxval):
ValueError: could not convert string to float: '2.7-05'
============================================================
[INFO   ]        samtools : Found 1 flagstat reports
[INFO   ]          fastqc : Found 2 reports
Traceback (most recent call last):
  File "/home/neuro_admin/anaconda3/bin/multiqc", line 5, in <module>
    from multiqc.__main__ import multiqc
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/__main__.py", line 53, in <module>
    multiqc.run_cli(prog_name="multiqc")
  File "/home/neuro_admin/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/neuro_admin/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/neuro_admin/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/neuro_admin/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/multiqc.py", line 248, in run_cli
    kwargs=kwargs,
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/multiqc.py", line 728, in run
    report.general_stats_html = table.plot(report.general_stats_data, report.general_stats_headers, pconfig)
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/plots/table.py", line 53, in plot
    return make_table(dt)
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/plots/table.py", line 138, in make_table
    c_scale = mqc_colour.mqc_colour_scale(header["scale"], header["dmin"], header["dmax"])
  File "/home/neuro_admin/.local/lib/python3.7/site-packages/multiqc/utils/mqc_colour.py", line 33, in __init__
    if float(minval) == float(maxval):
ValueError: could not convert string to float: '4.4-05'

```

**File that triggers the error:**

[SU7144_hs_metrics.txt.gz](https://github.com/ewels/MultiQC/files/6188042/SU7144_hs_metrics.txt.gz)

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: multiqc -o "/path/to/output-folder/" -n "some_prefix" "/path/to/folder/to/check" -f
- MultiQC Version: This is MultiQC v1.10
- Operating System: CentOS 7
- Python Version: Python 3.7.10
- Method of MultiQC installation: pip

**Additional context**

Ran in a WDL workflow through SLURM. All other samples of the run are ok.

**Comment by beboche** [comment]
Sample was nearly empty

**Comment by ewels** [comment]
Still shouldn't cause an error like this though - thankfully I can say that this bug is fixed in the dev version already on `master`, will do a patch release soon.

**Comment by beboche** [comment]
ok thanks for the answer and the future fix!
