### ISSUE TITLE
Flexbar module is broken

### ISSUE THREAD

**Issue by adomingues** [ewels/MultiQC#1407]
**Description of bug:**

A warning message is generated after running multiqc:

> Oops! The 'flexbar' MultiQC module broke..

**MultiQC Error log:**

```
multiqc -o ${PRJ_RESULTS}/multiqc .
[INFO   ]         multiqc : This is MultiQC v1.10.1
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /mnt/projects/genomics/projects/RBM20_clip/results
Searching   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 550/550  
[INFO   ]            star : Found 8 reports
[INFO   ]         bowtie2 : Found 3 reports
[ERROR  ]         multiqc : Oops! The 'flexbar' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./processed_reads/flexbar/raw_rbm20_6sg_NH_HM_04.log
============================================================
Module flexbar raised an exception: Traceback (most recent call last):
  File "/mnt/genomics/envs/multiqc/lib/python3.6/site-packages/multiqc/multiqc.py", line 594, in run
    output = mod()
  File "/mnt/genomics/envs/multiqc/lib/python3.6/site-packages/multiqc/modules/flexbar/flexbar.py", line 31, in __init__
    self.parse_flexbar(f)
  File "/mnt/genomics/envs/multiqc/lib/python3.6/site-packages/multiqc/modules/flexbar/flexbar.py", line 94, in parse_flexbar
    _save_data(parsed_data)
  File "/mnt/genomics/envs/multiqc/lib/python3.6/site-packages/multiqc/modules/flexbar/flexbar.py", line 64, in _save_data
    float(parsed_data["removed_bases"]) / float(parsed_data["processed_bases"])
ZeroDivisionError: float division by zero
============================================================
[INFO   ]          fastqc : Found 10 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : ../../../../../genomics/projects/results/multiqc/multiqc_report.html
[INFO   ]         multiqc : Data        : ../../../../../genomics/projects/results/multiqc/multiqc_data
[INFO   ]         multiqc : MultiQC complete

```

**File that triggers the error:**

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: `multiqc -o ${PRJ_RESULTS}/multiqc .`
- MultiQC Version: MultiQC v1.10.1
- Operating System: Ubuntu 20.04
- Python Version: Python 3.6.13
- Method of MultiQC installation: conda

**Additional context**

**Comment by ewels** [comment]
Thanks for reporting! Please can you zip and attach `./processed_reads/flexbar/raw_rbm20_6sg_NH_HM_04.log` so that I can try to replicate this to find the problem 😄

**Comment by ewels** [comment]
(I guess that this sample has zero reads in it)

**Comment by adomingues** [comment]
You are right - not reads in it. I think this was a reliq from a previously failed test. Attached nonetheless. 

[raw_rbm20_6sg_NH_HM_04.zip](https://github.com/ewels/MultiQC/files/6277084/raw_rbm20_6sg_NH_HM_04.zip)

**Comment by ewels** [comment]
Thanks! Yes still good to handle it rather than crashing 👍🏻

**Comment by ewels** [comment]
Ok, should be fixed in the development version now, done in 4d3fd1c. It just sets the % removed bases to `0` if there are zero total reads.

Let me know if you hit any other problems. Thanks for reporting!

**Comment by adomingues** [comment]
Cheers!
