### ISSUE TITLE
snpeff' MultiQC module broke

### ISSUE THREAD

**Issue by mprabha2** [ewels/MultiQC#1410]
```
libwebp.so.7: cannot open shared object file: No such file or directory
[ERROR  ]         multiqc : Oops! The 'snpeff' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./gatk/src/test/resources/subsetExAC.snps_model.report
============================================================
Module snpeff raised an exception: Traceback (most recent call last):
  File "/home/prabha/anaconda3/lib/python3.7/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/home/prabha/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/home/prabha/anaconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'multiqc.modules.snpeff'
============================================================
```

**Comment by ewels** [comment]
This looks like an installation error. Please try reinstalling MultiQC. Documentation: https://multiqc.info/docs/#installing-multiqc

If you still have problems, please use the issue template and fill in all of the suggested information: https://github.com/ewels/MultiQC/issues/new?assignees=&labels=&template=bug_report.md
