### ISSUE TITLE
sentieon module doesn't handle "total_pairs" being 0

### ISSUE THREAD

**Issue by Jessime** [ewels/MultiQC#1420]
**Description of bug:**

The title pretty much says it all. We sometimes have samples with 0 reads, which multiqc doesn't handle gracefully. 

**MultiQC Error log:**

```
[ERROR  ]         multiqc : Oops! The 'sentieon' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    ./SQ42003/sentieon/SQ42003_insert_size_metrics.txt
============================================================
Module sentieon raised an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/multiqc/multiqc.py", line 594, in run
    output = mod()
  File "/usr/local/lib/python3.8/site-packages/multiqc/modules/sentieon/sentieon.py", line 52, in __init__
    n["InsertSizeMetrics"] = InsertSizeMetrics.parse_reports(self)
  File "/usr/local/lib/python3.8/site-packages/multiqc/modules/sentieon/InsertSizeMetrics.py", line 110, in parse_reports
    self.sentieon_insertSize_samplestats[s_name]["summed_mean"] = v["meansum"] / v["total_pairs"]
ZeroDivisionError: division by zero
```

**File that triggers the error:**

```
#SentieonCommandLine: /locus/data/external_data/research_experiments/wgs_resources/bin/sentieon/sentieon_current/libexec/driver -i SQ42027/SQ42027_aligned.deduped.sort.bam -r /locus/data/external_data/research_experiments/wgs_resources/data/reference/human/human_g1k_v37_modified.fasta/human_g1k_v37_modified.fasta --algo InsertSizeMetricAlgo SQ42027/sentieon/SQ42027_insert_size_metrics.txt
MEDIAN_INSERT_SIZE      MEDIAN_ABSOLUTE_DEVIATION       MIN_INSERT_SIZE MAX_INSERT_SIZE MEAN_INSERT_SIZE        STANDARD_DEVIATION      READ_PAIRS      PAIR_ORIENTATION        WIDTH_OF_10_PERCENT     WIDTH_OF_20_PERCENT     WIDTH_OF_30_PERCENT     WIDTH_OF_40_PERCENT     WIDTH_OF_50_PERCENT     WIDTH_OF_60_PERCENT     WIDTH_OF_70_PERCENT     WIDTH_OF_80_PERCENT     WIDTH_OF_90_PERCENT     WIDTH_OF_99_PERCENT

insert_size

```

**MultiQC run details (please complete the following):**

- Command used to run MultiQC: `multiqc .`
- MultiQC Version: `multiqc, version 1.10.1`
- Operating System: `singularity`
- Python Version: `Python 3.8.9`
- Method of MultiQC installation: `pip`

**Additional context**

I'm not sure if multiqc has standard policies around representing null values. But it seems easy enough to add a quick check and set to something like `np.nan` if `v["total_pairs"] == 0`

**Comment by ewels** [comment]
Yeah, I get a different error with your file (`ValueError: 'PAIR_ORIENTATION' is not in list`) which I guess is because it's missing tabs. Is it easy for you to attach the raw zipped file please?

**Comment by ewels** [comment]
@Jessime - please can you attach the original file that triggers this error so that I can replicate it?

Thanks!
