### ISSUE TITLE
Update to `rich` breaks custom traceback rendering

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#1477]
Looks like a recent update to the `rich` package has broken the custom traceback rendering that I put together not that long ago..

```python
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/multiqc/multiqc.py", line 615, in run
    output = mod()
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/multiqc/modules/cutadapt/cutadapt.py", line 45, in __init__
    self.parse_cutadapt_logs(f)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/multiqc/modules/cutadapt/cutadapt.py", line 171, in parse_cutadapt_logs
    self.cutadapt_length_counts[end][plot_sname] = dict()
KeyError: '?'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.10/x64/bin/multiqc", line 5, in <module>
    from multiqc.__main__ import multiqc
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/multiqc/__main__.py", line 53, in <module>
    multiqc.run_cli(prog_name="multiqc")
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/multiqc/multiqc.py", line 235, in run_cli
    multiqc_run = run(
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/multiqc/multiqc.py", line 682, in run
    console.print(
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/console.py", line 1574, in print
    extend(render(renderable, render_options))
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/console.py", line 1215, in render
    for render_output in iter_render:
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/panel.py", line 152, in __rich_console__
    lines = console.render_lines(renderable, child_options, style=style)
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/console.py", line 1250, in render_lines
    lines = list(
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/segment.py", line 198, in split_and_crop_lines
    for segment in segments:
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/segment.py", line 106, in <genexpr>
    segments = (
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/console.py", line 1215, in render
    for render_output in iter_render:
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/padding.py", line 92, in __rich_console__
    lines = console.render_lines(
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/console.py", line 1250, in render_lines
    lines = list(
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/segment.py", line 198, in split_and_crop_lines
    for segment in segments:
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/site-packages/rich/console.py", line 1203, in render
    raise errors.NotRenderableError(
rich.errors.NotRenderableError: Unable to render <class 'multiqc.multiqc.run.<locals>.CustomTraceback'>; A str, Segment or object with __rich_console__ method is required
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1768/1768
```

**Comment by ewels** [comment]
I'm pretty sure that this was working fine for me with `rich-10.2.2` but upgrading to `rich-10.4.0` causes the above error.

**Comment by ewels** [comment]
Confirmed, it's going from `10.3.0` to `10.4.0` that it breaks..

**Comment by ewels** [comment]
Fixed - turned out that I was probably just doing something wrong and `rich` got better at spotting that. Confirmed that updated code now works on versions `10.2.2` -> `10.4.0`
