### ISSUE TITLE
ZeroDivisionError with qualimap/rnaseq module

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1492]
### Description of bug

I hate to say it but I found another one of those `ZeroDivisionError` puppies after I upgraded MultiQC to 1.11 within the nf-core/rnaseq pipeline. I haven't changed the test data so maybe it was something introduced whilst fixing https://github.com/ewels/MultiQC/issues/1258 ?

Running `multiqc -f .` in the test data attached should reproduce the error.

### File that triggers the error

[test.tar.gz](https://github.com/ewels/MultiQC/files/6817780/test.tar.gz)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.11

|           multiqc | Search path : test
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 32/32
|          bargraph | Tried to make bar plot, but had no data
╭────────────────────────────────────────────────────────── Oops! The 'qualimap' MultiQC module broke... ───────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                                     │
│ Please attach a file that triggers the error. The last file found was: ./raw_data_qualimapReport/coverage_profile_along_genes_(total).txt                         │
│                                                                                                                                                                   │
│ Traceback (most recent call last):                                                                                                                                │
│   File "conda/envs/multiqc-1.11/lib/python3.9/site-packages/multiqc/multiqc.py", line 624, in run                              │
│     output = mod()                                                                                                                                                │
│   File "conda/envs/multiqc-1.11/lib/python3.9/site-packages/multiqc/modules/qualimap/qualimap.py", line 47, in __init__        │
│     n["RNASeq"] = QM_RNASeq.parse_reports(self)                                                                                                                   │
│   File "conda/envs/multiqc-1.11/lib/python3.9/site-packages/multiqc/modules/qualimap/QM_RNASeq.py", line 163, in parse_reports │
│     self.qualimap_rnaseq_cov_hist_percent[s_name][k] = (v / total) * 100.0                                                                                        │
│ ZeroDivisionError: float division by zero                                                                                                                         │
│                                                                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment]
Fixed by @ErikDanielsson in #1498 👏🏻
