### ISSUE TITLE
`fastp` module crashes with empty samples (zero reads)

### ISSUE THREAD

**Issue by telatin** [ewels/MultiQC#1499]
### Description of bug

Automatic processing a sequencing run that included a negative control that manage not to have any reads failed (division by zero). A division check can make the module safer when automatically processing raw outputs.

### File that triggers the error

Fastp JSON report of an empty sample:

 📦  [PCRblank.fastp.json.zip](https://github.com/ewels/MultiQC/files/6839517/PCRblank.fastp.json.zip)

### MultiQC Error log

```console
$ multiqc -o report .

  /// MultiQC 🔍 | v1.11

|           multiqc | Search path : /Volumes/Informatics/GMH/projects/758-emily/control-run/filt
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 32/32  
|             fastp | FastQ input file has zero raw reads
╭───────────────────────────────────────── Oops! The 'fastp' MultiQC module broke... ──────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                │
│ Please attach a file that triggers the error. The last file found was: ./PCRblank.fastp.json                                 │
│                                                                                                                              │
│ Traceback (most recent call last):                                                                                           │
│   File "/Users/telatina/miniconda3/lib/python3.9/site-packages/multiqc/multiqc.py", line 624, in run                         │
│     output = mod()                                                                                                           │
│   File "/Users/telatina/miniconda3/lib/python3.9/site-packages/multiqc/modules/fastp/fastp.py", line 47, in __init__         │
│     self.parse_fastp_log(f)                                                                                                  │
│   File "/Users/telatina/miniconda3/lib/python3.9/site-packages/multiqc/modules/fastp/fastp.py", line 230, in parse_fastp_log │
│     self.fastp_data[s_name]["adapter_cutting_adapter_trimmed_reads"]                                                         │
│ ZeroDivisionError: float division by zero                                                                                    │
│                                                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment]
Thanks @telatin 👍🏻  Fixed in #1489, tested and seems to solve the issue ✨
