### ISSUE TITLE
 'sortmerna' MultiQC module broke

### ISSUE THREAD

**Issue by d-deen** [ewels/MultiQC#1523]
### Description of bug

Hello,

I received the following error when running MultiQC on sortmeRNA results:

```python
Module sortmerna raised an exception: Traceback (most recent call last):
  File "/mnt/storage/apps/eb/software/MultiQC/1.7-foss-2018b-Python-3.6.6/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/mnt/storage/apps/eb/software/MultiQC/1.7-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/multiqc/modules/sortmerna/sortmerna.py", line 30, in __init__
    self.parse_sortmerna(f)
  File "/mnt/storage/apps/eb/software/MultiQC/1.7-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/multiqc/modules/sortmerna/sortmerna.py", line 85, in parse_sortmerna
    self.sortmerna[s_name]["rRNA_pct"] = float(self.sortmerna[s_name]["rRNA"]) / float(self.sortmerna[s_name]["total"]) * 100
KeyError: 'total'
```

### MultiQC Error log

```console
multiqc .
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 46 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'sortmerna' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    ./rRNA.log
============================================================
Module sortmerna raised an exception: Traceback (most recent call last):
  File "/mnt/storage/apps/eb/software/MultiQC/1.7-foss-2018b-Python-3.6.6/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/mnt/storage/apps/eb/software/MultiQC/1.7-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/multiqc/modules/sortmerna/sortmerna.py", line 30, in __init__
    self.parse_sortmerna(f)
  File "/mnt/storage/apps/eb/software/MultiQC/1.7-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/multiqc/modules/sortmerna/sortmerna.py", line 85, in parse_sortmerna
    self.sortmerna[s_name]["rRNA_pct"] = float(self.sortmerna[s_name]["rRNA"]) / float(self.sortmerna[s_name]["total"]) * 100
KeyError: 'total'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
MultiQC v1.7 is now very old, we're on v1.11 with v1.12 to be released soon. There have been several changes to the sortmerna module since then, so I'm guessing that this bug is already fixed.

If you still hit the same error with the latest version of MultiQC, please open a new issue 👍🏻
