### ISSUE TITLE
Problem with Samtools

### ISSUE THREAD

**Issue by pastoma85** [ewels/MultiQC#1554]
### Description of bug

```
Module samtools raised an exception: Traceback (most recent call last):
  File "/Users/pasqualetomaiuolo/opt/miniconda3/lib/python3.8/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/Users/pasqualetomaiuolo/opt/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/Users/pasqualetomaiuolo/opt/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'multiqc.modules.samtools'
============================================================
```

**Comment by ewels** [comment]
My guess is that this is an installation error. Please try reinstalling MultiQC.

Otherwise, I need more information to help, sorry. If you're still hitting problems, please create a new issue and follow the instructions / fill in all of the fields:

> _Please paste your full command and MultiQC log._
> _Please do not truncate it, as the MultiQC version and command may be needed to help._
