### ISSUE TITLE
rseqc junction_saturation input files trigger an `AttributeError`

### ISSUE THREAD

**Issue by a-frantz** [ewels/MultiQC#1582]
### Description of bug

I think this will trigger for other rseqc modules but I haven't checked.

I was using the test data to get a look at what the saturation figures look like (I'm starting work on a similar module), and MultiQC was reporting it didn't find any valid reports in `MultiQC_TestData/data/modules/rseqc/junction_saturation/`.

Did some code diving, and commented out the `try/except` clauses in `multiqc/modules/rseqc/rseqc.py` line 62-70. Once I made that change, the `AttributeError` in the below logs appeared. Looks to me like this will trigger for any of the modules?

### File that triggers the error

`MultiQC_TestData/data/modules/rseqc/junction_saturation/SRR42383*`

### MultiQC Error log

```console
$ multiqc -f ../MultiQC_TestData/data/modules/rseqc/junction_saturation/SRR42383*

  /// MultiQC 🔍 | v1.12.dev0 (ec0a548)

|           multiqc | Search path : /Users/afrantz/MultiQC_TestData/data/modules/rseqc/junction_saturation/SRR4238351_subsamp.sorted.rseqc.junctionSaturation_plot.r
|           multiqc | Search path : /Users/afrantz/MultiQC_TestData/data/modules/rseqc/junction_saturation/SRR4238355_subsamp.sorted.rseqc.junctionSaturation_plot.r
|           multiqc | Search path : /Users/afrantz/MultiQC_TestData/data/modules/rseqc/junction_saturation/SRR4238359_subsamp.sorted.rseqc.junctionSaturation_plot.r
|           multiqc | Search path : /Users/afrantz/MultiQC_TestData/data/modules/rseqc/junction_saturation/SRR4238379_subsamp.sorted.rseqc.junctionSaturation_plot.r
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 4/4
╭───────────────────────────────────────────────────────────────────────── Oops! The 'rseqc' MultiQC module broke... ─────────────────────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                                                               │
│ Please attach a file that triggers the error. The last file found was: ../MultiQC_TestData/data/modules/rseqc/junction_saturation/SRR4238379_subsamp.sorted.rseqc.junctionSaturation_plot.r │
│                                                                                                                                                                                             │
│ Traceback (most recent call last):                                                                                                                                                          │
│   File "/Users/afrantz/MultiQC/multiqc/multiqc.py", line 649, in run                                                                                                                        │
│     output = mod()                                                                                                                                                                          │
│   File "/Users/afrantz/MultiQC/multiqc/modules/rseqc/rseqc.py", line 66, in __init__                                                                                                        │
│     n[sm] = getattr(module, "parse_reports")(self)                                                                                                                                          │
│   File "/Users/afrantz/MultiQC/multiqc/modules/rseqc/junction_saturation.py", line 53, in parse_reports                                                                                     │
│     self.write_data_file(self.junction_saturation, "rseqc_junction_saturation")                                                                                                             │
│ AttributeError: 'MultiqcModule' object has no attribute 'junction_saturation'                                                                                                               │
│                                                                                                                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment]
ps. It looks like this bug crept in as part of #1490 so hasn't been exposed in a stable release yet. So good catch @a-frantz! Hopefully there aren't too many others like this..

**Comment by MatthiasZepper** [comment]
> This struck me as a weird error so I couldn't resist taking a quick look (sorry @MatthiasZepper).

No worries. I will never complain about work that magically resolves :wink:. I did not even have to enchant a broom to work for me like other apprentices used to do...
