### ISSUE TITLE
RSeQC tin.py module errors when providing empty input file

### ISSUE THREAD

**Issue by drpatelh** [ewels/MultiQC#1604]
### Description of bug

Running the `rseqc/tin` module errors if an empty file is found.

Tested with MultiQC v1.11

### File that triggers the error

An empty file provided to the module will trigger it. I set [this](https://github.com/nf-core/rnaseq/blob/6634d646ffde36eb7910b54fba897dfd27891ddd/assets/multiqc_config.yaml#L104-L105) in the config for it to be found.

### MultiQC Error log

```console
Command output:
  |         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 357/357  

Command error:
  |    custom_content | biotype-gs: Found 5 General Statistics columns
  |    custom_content | biotype_counts: Found 5 samples (bargraph)
  |    custom_content | DupInt: Found 5 General Statistics columns
  |    custom_content | dupradar: Found 5 samples (linegraph)
  |    custom_content | salmon_deseq2_clustering: Found 5 samples (heatmap)
  |    custom_content | salmon_deseq2_pca: Found 5 samples (scatter)
  |    custom_content | star_salmon_deseq2_pca: Found 5 samples (scatter)
  |    custom_content | star_salmon_deseq2_clustering: Found 5 samples (heatmap)
  |            picard | Found 5 MarkDuplicates reports
  |            preseq | Found 5 reports
  |          qualimap | Found 5 RNASeq reports
  |             rseqc | Found 5 read_distribution reports
  |             rseqc | Found 3 inner_distance reports
  |             rseqc | Found 5 read_duplication reports
  |             rseqc | Found 5 junction_annotation reports
  |             rseqc | Found 5 junction_saturation reports
  |             rseqc | Found 5 infer_experiment reports
  |             rseqc | Found 5 bam_stat reports
  ╭───────────────── Oops! The 'rseqc' MultiQC module broke... ──────────────────╮
  │ Please copy this log and report it at                                        │
  │ https://github.com/ewels/MultiQC/issues                                      │
  │ Please attach a file that triggers the error. The last file found was:       │
  │ ./rseqc/tin/RAP1_UNINDUCED_REP1.tin.txt                                      │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/usr/local/lib/python3.9/site-packages/multiqc/multiqc.py", line 624 │
  │     output = mod()                                                           │
  │   File "/usr/local/lib/python3.9/site-packages/multiqc/modules/rseqc/rseqc.p │
  │     n[sm] = getattr(module, "parse_reports")(self)                           │
  │   File "/usr/local/lib/python3.9/site-packages/multiqc/modules/rseqc/tin.py" │
  │     contents = next(reader)                                                  │
  │   File "/usr/local/lib/python3.9/csv.py", line 111, in __next__              │
  │     row = next(self.reader)                                                  │
  │ StopIteration                                                                │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
  |            salmon | Found 5 meta reports
  |            salmon | Found 5 fragment length distributions
  |          samtools | Found 5 stats reports
  |          samtools | Found 5 flagstat reports
  |          samtools | Found 5 idxstats reports
  |              star | Found 5 reports
  |            fastqc | Found 8 reports
  |          cutadapt | Found 8 reports
  |            fastqc | Found 8 reports
  |           multiqc | Compressing plot data
  |           multiqc | Report      : multiqc_report.html
  |           multiqc | Data        : multiqc_data
  |           multiqc | Plots       : multiqc_plots
  |           multiqc | MultiQC complete
```

**Comment by ewels** [comment]
Fixed in bae13eff3e82595bd459d9d4ee5c801b6dca0624 ✅
