### ISSUE TITLE
'fastp' MultiQC module broke

### ISSUE THREAD

**Issue by ashwini06** [ewels/MultiQC#1608]
### Description of bug

```
╭────────────────────────────────────────────────── Oops! The 'fastp' MultiQC module broke... ───────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                  │
│ Please attach a file that triggers the error. The last file found was:                                                                         │
│ /home/proj/stage/cancer/cases/equalbug/analysis/qc/multiqc_data_old/multiqc_fastp.json                                                         │
│                                                                                                                                                │
│ Traceback (most recent call last):                                                                                                             │
│   File "/opt/conda/lib/python3.8/site-packages/multiqc/multiqc.py", line 624, in run                                                           │
│     output = mod()                                                                                                                             │
│   File "/opt/conda/lib/python3.8/site-packages/multiqc/modules/fastp/fastp.py", line 47, in __init__                                           │
│     self.parse_fastp_log(f)                                                                                                                    │
│   File "/opt/conda/lib/python3.8/site-packages/multiqc/modules/fastp/fastp.py", line 161, in parse_fastp_log                                   │
│     cmd = parsed_json["command"].split()                                                                                                       │
│ KeyError: 'command'                                                                                                                            │
│
```

### MultiQC Error log

```console
Multiqc v1.11

|    MarkDuplicates | Skipping MarkDuplicates sample 'multiqc_data' as missing essential fields
|    MarkDuplicates | Skipping MarkDuplicates sample 'multiqc_data' as missing essential fields
|    MarkDuplicates | Skipping MarkDuplicates sample 'multiqc_data' as missing essential fields
|    MarkDuplicates | Skipping MarkDuplicates sample 'multiqc_data' as missing essential fields
|    MarkDuplicates | Skipping MarkDuplicates sample 'multiqc_data' as missing essential fields
|            picard | Found 4 MarkDuplicates reports
|          samtools | Found 2 stats reports
|          samtools | Found 2 flagstat reports
|          samtools | Found 2 idxstats reports
|            snippy | Found 1 reports
|          bargraph | Tried to make bar plot, but had no data
╭────────────────────────────────────────────────── Oops! The 'fastp' MultiQC module broke... ───────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                  │
│ Please attach a file that triggers the error. The last file found was:                                                                         │
│ /home/proj/stage/cancer/cases/equalbug/analysis/qc/multiqc_data_old/multiqc_fastp.json                                                         │
│                                                                                                                                                │
│ Traceback (most recent call last):                                                                                                             │
│   File "/opt/conda/lib/python3.8/site-packages/multiqc/multiqc.py", line 624, in run                                                           │
│     output = mod()                                                                                                                             │
│   File "/opt/conda/lib/python3.8/site-packages/multiqc/modules/fastp/fastp.py", line 47, in __init__                                           │
│     self.parse_fastp_log(f)                                                                                                                    │
│   File "/opt/conda/lib/python3.8/site-packages/multiqc/modules/fastp/fastp.py", line 161, in parse_fastp_log                                   │
│     cmd = parsed_json["command"].split()                                                                                                       │
│ KeyError: 'command'                                                                                                                            │
│                                                                                                                                                │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|            fastqc | Found 4 reports
|           multiqc | Compressing plot data
|           multiqc | Deleting    : ../analysis/qc/multiqc_data   (-f was specified)
|           multiqc | Report      : ../analysis/qc/multiqc_report.html
|           multiqc | Data        : ../analysis/qc/multiqc_data
|           multiqc | MultiQC complete
```

**Comment by ashwini06** [comment]
works fine now, closing this issue!
