### ISSUE TITLE
Deprecated 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by adria-boada** [ewels/MultiQC#1642]
### Description of bug

It appears like a function of 'markupsafe' has been deprecated and rises an ImportError. See this github post: https://github.com/pallets/markupsafe/issues/284

To fix it, I have downgraded 'markupsafe': `pip install markupsafe==2.0.1`

### MultiQC Error log

```console
$ multiqc 
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 5, in <module>
    from multiqc.__main__ import run_multiqc
  File "/usr/local/lib/python3.8/dist-packages/multiqc/__init__.py", line 16, in <module>
    from .multiqc import run
  File "/usr/local/lib/python3.8/dist-packages/multiqc/multiqc.py", line 17, in <module>
    import jinja2
  File "/home/adria/.local/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/adria/.local/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/adria/.local/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/adria/.local/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.8/dist-packages/markupsafe/__init__.py)
```

**Comment by ewels** [comment]
Thanks for letting me know! Sounds like a relatively simple fix:

> Remove `soft_unicode`, which was previously deprecated. Use `soft_str` instead.

**Comment by ewels** [comment]
Bumped to >= version 3.0.0. That was [released in May 2021](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-0-0) which is quite a while ago, so should hopefully have limited impact on most users.
