### ISSUE TITLE
Module with snpeff

### ISSUE THREAD

**Issue by hmkim** [ewels/MultiQC#166]
$ multiqc -v -f -d .

## If you're reporting a bug..
Please paste the full log message that you get in a code block. If possible, please attach an example file which triggers the problem.
```
ication_levels.png
[2016-03-30 11:48:56,619] multiqc                                            [DEBUG  ]  Ignoring file as has filetype 'image/png': kmer_profiles.png
[2016-03-30 11:48:56,675] multiqc.modules.snpeff.snpeff                      [INFO   ]  Found 1 reports
[2016-03-30 11:48:56,678] multiqc                                            [ERROR  ]  Oops! The 'snpeff' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module snpeff raised an exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/multiqc-0.5.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 266, in multiqc
    report.modules_output.append(mod())
  File "/usr/local/lib/python2.7/dist-packages/multiqc-0.5.dev0-py2.7.egg/multiqc/modules/snpeff/snpeff.py", line 60, in __init__
    'content': self.count_effects_plot()
  File "/usr/local/lib/python2.7/dist-packages/multiqc-0.5.dev0-py2.7.egg/multiqc/modules/snpeff/snpeff.py", line 221, in count_effects_plot
    sorted_keys = sorted(keys, reverse=True, key=self.snpeff_data[s_name].__getitem__)
KeyError: 'TF_binding_site_variant'
============================================================
[2016-03-30 11:48:56,680] multiqc.modules.qualimap.qualimap                  [DEBUG  ]  Could not find any reports in ('.',)
[2016-03-30 11:48:56,683] multiqc.modules.featureCounts.feature_counts       [DEBUG  ]  Could not find any reports in ('.',)
[2016-03-30 11:48:56,685] multiqc.modules.methylQA.methylQA                  [DEBUG  ]  Could not find any reports in ('.',)
```

```
        # Sort the keys based on the first dataset
        for s_name in self.snpeff_data:
            sorted_keys = sorted(keys, reverse=True, key=self.snpeff_data[s_name].__getitem__)
            break
```

In function of sorted(), can I examine the key available in python?

I recognize the cause of problem. but I can't handle the python code well.
All snpeff output not same, there is no Key (TF_binding_site_variant, NONE, etc..) in case.

Please check this.

**Comment by hmkim** [comment]
```
258         # Sort the keys based on the first dataset
259         for s_name in self.snpeff_data:
260             sorted_keys = sorted(keys, reverse=True, key=self.snpeff_data[s_name].__getitem__)
261             break
```
to

```
258         # Sort the keys based on the first dataset
259         for s_name in self.snpeff_data:
**260             new_keys = []
261             for t in self.snpeff_data[s_name].keys():
262                 for r in keys:
263                     if r == t:
264                         new_keys.append(t)**
265             sorted_keys = sorted(**new_keys**, reverse=True, key=self.snpeff_data[s_name].__getitem__)
266             break
```

I solved this problem.

Apply to this too.

```
219         # Sort the keys based on the first dataset
220         for s_name in self.snpeff_data:
221             sorted_keys = sorted(keys, reverse=True, key=self.snpeff_data[s_name].__getitem__)
222             break
```

**Comment by ewels** [comment]
Thanks @hmkim - this kind of error is tricky, I build new modules around log files that I have available and later find that other people's log files have slightly different fields! Thanks for your investigative work, instead I think I'll update the code to simply use whatever field names it finds for the `Count by Effects` and `Count by Genomic Region` plots (rather than hardcoding them) which should fix your problem.

Phil
