### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by TANGLi83-star** [ewels/MultiQC#1671]
### Description of bug

I could run the multiqc yesterday. But it suddenly broke down. Please help me solve this problem.

### MultiQC Error log

```console
$ multiqc fastqc/

 Traceback (most recent call last):                                                                           │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/multiqc/multiqc.py", line 6 │
│     mod = config.avail_modules[this_module].load()                                                           │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/pkg_resources/__init__.py", │
│     return self.resolve()                                                                                    │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/pkg_resources/__init__.py", │
│     module = __import__(self.module_name, fromlist=['__name__'], level=0)                                    │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/multiqc/modules/fastqc/__in │
│     from .fastqc import MultiqcModule                                                                        │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/multiqc/modules/fastqc/fast │
│     from multiqc.modules.base_module import BaseMultiqcModule                                                │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/multiqc/modules/base_module │
│     import markdown                                                                                          │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/markdown/__init__.py", line │
│     from .core import Markdown, markdown, markdownFromFile  # noqa: E402                                     │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/markdown/core.py", line 26, │
│     from . import util                                                                                       │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/markdown/util.py", line 88, │
│     INSTALLED_EXTENSIONS = metadata.entry_points(group='markdown.extensions')                                │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/importlib_metadata/__init__ │
│     return SelectableGroups.load(eps).select(**params)                                                       │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/importlib_metadata/__init__ │
│     ordered = sorted(eps, key=by_group)                                                                      │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/importlib_metadata/__init__ │
│     eps = itertools.chain.from_iterable(                                                                     │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/importlib_metadata/_itertoo │
│     k = key(element)                                                                                         │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/importlib_metadata/__init__ │
│     return self._name_from_stem(stem) or super()._normalized_name                                            │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/importlib_metadata/__init__ │
│     return Prepared.normalize(self.name)                                                                     │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/site-packages/importlib_metadata/__init__ │
│     return re.sub(r"[-_.]+", "-", name).lower().replace('-', '_')                                            │
│   File "/usrdata/users/SDAU/012043/miniconda3/envs/R/lib/python3.9/re.py", line 210, in sub                  │
│     return _compile(pattern, flags).sub(repl, string, count)                                                 │
│ TypeError: expected string or bytes-like object
```

**Comment by ewels** [comment]
This is an old issue now that got buried, sorry.

It's not possible to work on this without some example data to reproduce the problem. I'm going to close, if it's still a problem then please create a new issue using the [bug issue template](https://github.com/ewels/MultiQC/issues/new?assignees=&labels=&projects=&template=bug_report.yml).
