### ISSUE TITLE
AttributeError: module 'typing' has no attribute '_SpecialForm'

### ISSUE THREAD

**Issue by nick-youngblut** [ewels/MultiQC#1687]
### Description of bug

```
[...]
Searching 2134 files..
[ERROR  ]         multiqc : Oops! The 'afterqc' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module afterqc raised an exception: Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 9, in <module>
    from typing import Protocol
ImportError: cannot import name 'Protocol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/bin/multiqc", line 425, in multiqc
    mod = config.avail_modules[this_module].load()
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/multiqc/modules/afterqc/__init__.py", line 3, in <module>
    from .afterqc import MultiqcModule
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/multiqc/modules/afterqc/afterqc.py", line 12, in <module>
    from multiqc.modules.base_module import BaseMultiqcModule
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/multiqc/modules/base_module.py", line 10, in <module>
    import markdown
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/markdown/core.py", line 26, in <module>
    from . import util
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/markdown/util.py", line 36, in <module>
    import importlib_metadata as metadata
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 17, in <module>
    from . import _adapters, _meta
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/importlib_metadata/_meta.py", line 1, in <module>
    from ._compat import Protocol
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 16, in <module>
    from typing_extensions import Protocol  # type: ignore
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/typing_extensions.py", line 159, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'
============================================================
[ERROR  ]         multiqc : Oops! The 'custom_content' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module custom_content raised an exception: Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 9, in <module>
    from typing import Protocol
ImportError: cannot import name 'Protocol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/bin/multiqc", line 425, in multiqc
    mod = config.avail_modules[this_module].load()
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/multiqc/modules/custom_content/__init__.py", line 3, in <module>
    from .custom_content import *
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/multiqc/modules/custom_content/custom_content.py", line 14, in <module>
    from multiqc.modules.base_module import BaseMultiqcModule
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/multiqc/modules/base_module.py", line 10, in <module>
    import markdown
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/markdown/__init__.py", line 29, in <module>
    from .core import Markdown, markdown, markdownFromFile  # noqa: E402
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/markdown/core.py", line 26, in <module>
    from . import util
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/markdown/util.py", line 36, in <module>
    import importlib_metadata as metadata
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 17, in <module>
    from . import _adapters, _meta
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/importlib_metadata/_meta.py", line 1, in <module>
    from ._compat import Protocol
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/importlib_metadata/_compat.py", line 16, in <module>
    from typing_extensions import Protocol  # type: ignore
  File "/tmp/global2/nyoungblut/code/dev/ll_pipelines/llmgqc/.snakemake/conda/5a3a0d76947e4bdb66405fcaf2ef6c7a/lib/python3.6/site-packages/typing_extensions.py", line 159, in <module>
    class _FinalForm(typing._SpecialForm, _root=True):
AttributeError: module 'typing' has no attribute '_SpecialForm'
[...]
```

Conda env:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
brotlipy                  0.7.0           py36h8f6f2f9_1001    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.5.30        py36h5fab9bb_0    conda-forge
cffi                      1.14.6           py36hd8eec40_1    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.0.1            py36h5fab9bb_0    conda-forge
colormath                 3.0.0                      py_2    conda-forge
cryptography              35.0.0           py36hb60f036_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyh787bdff_2    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               h8e229c2_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py36h5fab9bb_3    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
gst-plugins-base          1.20.1               hcf0ee16_1    conda-forge
gstreamer                 1.20.1               hd4edc92_1    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.8.1            py36h5fab9bb_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_1    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.3.1            py36h605e78d_1    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0           14_linux64_openblas    conda-forge
libcblas                  3.9.0           14_linux64_openblas    conda-forge
libclang                  13.0.1          default_hc23dcda_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 11.2.0              h1d223b6_15    conda-forge
libgfortran-ng            11.2.0              h69a702a_15    conda-forge
libgfortran5              11.2.0              h5c6108e_15    conda-forge
libglib                   2.70.2               h174f98d_4    conda-forge
libgomp                   11.2.0              h1d223b6_15    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           14_linux64_openblas    conda-forge
libllvm13                 13.0.1               hf817b99_2    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     14.2                 hd57d9b9_0    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_15    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzstring                  1.0.4                   py_1001    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py36h8f6f2f9_0    conda-forge
matplotlib                3.3.4            py36h5fab9bb_0    conda-forge
matplotlib-base           3.3.4            py36hd391965_0    conda-forge
multiqc                   1.5a                     py36_0    bioconda
mysql-common              8.0.28               haf5c9bc_4    conda-forge
mysql-libs                8.0.28               h28c427c_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  2.7.1              pyhd8ed1ab_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.77                 h2350873_0    conda-forge
numpy                     1.19.5           py36hfc0c790_2    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1n               h166bdaf_0    conda-forge
pandas                    1.1.5            py36h284efc9_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    8.3.2            py36h676a545_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py36h5fab9bb_7    conda-forge
pyqt-impl                 5.12.3           py36h7ec31b9_7    conda-forge
pyqt5-sip                 4.19.18          py36hc4f0c31_7    conda-forge
pyqtchart                 5.12             py36h7ec31b9_7    conda-forge
pyqtwebengine             5.12.1           py36h7ec31b9_7    conda-forge
pysocks                   1.7.1            py36h5fab9bb_3    conda-forge
python                    3.6.15          hb7a2778_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py36h8f6f2f9_1    conda-forge
qt                        5.12.9               h1304e3e_6    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
scipy                     1.5.3            py36h81d768a_1    conda-forge
setuptools                58.0.4           py36h5fab9bb_2    conda-forge
simplejson                3.17.5           py36h8f6f2f9_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
spectra                   0.0.11                     py_1    conda-forge
sqlite                    3.38.2               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tornado                   6.1              py36h8f6f2f9_1    conda-forge
typing_extensions         4.2.0              pyha770c72_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

### File that triggers the error

There are 1067 files, so I cannot provide them here

### MultiQC Error log

```console
See above
```

**Comment by nick-youngblut** [comment]
This fixed the error:

```
  - typing_extensions    4.2.0  pyha770c72_0  installed
  + typing_extensions    4.1.1  pyha770c72_0  conda-forge/noarch         30kB
```

apparently, `typing_extensions=4.2.0` breaks `multiqc=1.5a`

**Comment by ewels** [comment]
Wow, MultiQC v1.5 is scary old 😅 (2018, first release was 2017). Have you tried with a newer version?

> There are 1067 files, so I cannot provide them here

Yup, but could you try it again with 1 and see if you get the same error? 😉 

Generally speaking, please avoid truncating the top of the log, as that includes important stuff like software versions and custom configurations that you're using etc. You can always attach a `multiqc.log` file if you don't want to make the issue too verbose 👍🏻
