### ISSUE TITLE
MultiQC v1.13 can't read Dragen 4.0.3. mapping metrics file: TypeError: can't multiply sequence by non-int of type 'float'

### ISSUE THREAD

**Issue by WimSpee** [ewels/MultiQC#1765]
### Description of bug

MultiQC v1.13 can't read Dragen 4.0.3. mapping metrics file of a single sample.

It could read the mapping metrics files of many other samples created also by Dragen 4.0.3. 

The error is
`TypeError: can't multiply sequence by non-int of type 'float'`

See the error log section for the full log/error output. 

Searching for the error here in the issues I found this issue
https://github.com/ewels/MultiQC/issues/1374

The sample that failed is also single ended. But the PR related to the above issue is merged and released in MultiQC v1.13?

Thank you for having a look. 

### File that triggers the error

[DA_1599_159.mapping_metrics.csv](https://github.com/ewels/MultiQC/files/9566224/DA_1599_159.mapping_metrics.csv)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.13

|           multiqc | Search path : ./CG_2.5_multiqc_DA_1599_159
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 15/15
╭────────────────────────────────────────────── Oops! The 'dragen' MultiQC module broke... ──────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                          │
│ Please attach a file that triggers the error. The last file found was: ./DA_1599_159.mapping_metrics.csv                             │
│                                                                                                                                        │
│ Traceback (most recent call last):                                                                                                     │
│   File "/home/my_user/.local/lib/python3.9/site-packages/multiqc/multiqc.py", line 654, in run                                          │
│     output = mod()                                                                                                                     │
│   File "/home/my_user/.local/lib/python3.9/site-packages/multiqc/modules/dragen/dragen.py", line 77, in __init__                        │
│     samples_found |= self.add_mapping_metrics()                                                                                        │
│   File "/home/my_user/.local/lib/python3.9/site-packages/multiqc/modules/dragen/mapping_metrics.py", line 59, in add_mapping_metrics    │
│     self.report_mapping_metrics(data_by_sample, data_by_rg_by_sample)                                                                  │
│   File "/home/my_user/.local/lib/python3.9/site-packages/multiqc/modules/dragen/mapping_metrics.py", line 90, in report_mapping_metrics │
│     plot=table.plot(data_by_rg, own_tabl_headers, pconfig={"namespace": NAMESPACE}),                                                   │
│   File "/home/my_user/.local/lib/python3.9/site-packages/multiqc/plots/table.py", line 53, in plot                                      │
│     return make_table(dt)                                                                                                              │
│   File "/home/my_user/.local/lib/python3.9/site-packages/multiqc/plots/table.py", line 157, in make_table                               │
│     val = header["modify"](val)                                                                                                        │
│   File "/home/my_user/.local/lib/python3.9/site-packages/multiqc/modules/dragen/utils.py", line 105, in <lambda>                        │
│     col["modify"] = lambda x: x * config.read_count_multiplier                                                                         │
│ TypeError: can't multiply sequence by non-int of type 'float'                                                                          │
│                                                                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment]
Just tested the supplied file and it worked fine, so closing as I think that this is already fixed 👍🏻
