### ISSUE TITLE
The 'fastqc' MultiQC module broke...

### ISSUE THREAD

**Issue by dmncyap** [ewels/MultiQC#1776]
### Description of bug

```python
Traceback (most recent call last):                                           
File "/usr/local/lib/python3.10/site-packages/multiqc/multiqc.py", line 65 
output = mod()                                                           
File "/usr/local/lib/python3.10/site-packages/multiqc/modules/fastqc/fastq 
self.read_count_plot()                                                  
File "/usr/local/lib/python3.10/site-packages/multiqc/modules/fastqc/fastq 
pdata[s_name]["Duplicate Reads"] = int(                                 
ValueError: cannot convert float NaN to integer
```

### File that triggers the error

[SRR5715030_1.trimmed_fastqc.zip](https://github.com/ewels/MultiQC/files/9739315/SRR5715030_1.trimmed_fastqc.zip)

### MultiQC Error log

```console
hpc quay.io/biocontainers/multiqc:1.13a--pyhdfd78af_1 multiqc 3_output --outdir 3_output/multiqc

  /// MultiQC 🔍 | v1.13.dev0

|           multiqc | Search path : /home/users/dsyap/3_output
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 14258/14258
|            fastqc | Found 422 reports
|            fastqc | Sample had zero reads: 'null'
╭───────────────── Oops! The 'fastqc' MultiQC module broke... ─────────────────╮
│ Please copy this log and report it at                                        │
│ https://github.com/ewels/MultiQC/issues                                      │
│ Please attach a file that triggers the error. The last file found was:       │
│ 3_output/acute_trimmed_fastqc/a3_stress/SRR5715030_1.trimmed_fastqc.zip      │
│                                                                              │
│ Traceback (most recent call last):                                           │
│   File "/usr/local/lib/python3.10/site-packages/multiqc/multiqc.py", line 65 │
│     output = mod()                                                           │
│   File "/usr/local/lib/python3.10/site-packages/multiqc/modules/fastqc/fastq │
│     self.read_count_plot()                                                   │
│   File "/usr/local/lib/python3.10/site-packages/multiqc/modules/fastqc/fastq │
│     pdata[s_name]["Duplicate Reads"] = int(                                  │
│ ValueError: cannot convert float NaN to integer                              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

**Comment by Redmar-van-den-Berg** [comment]
Are you sure you attached the correct file? If I analyze the file using the container you specify I get no error.

**Comment by ewels** [comment]
Confirmed, I get no error running MultiQC with this example file. Closing until it can be replicated.
