### ISSUE TITLE
Error when parsing log from umi_tools dedup

### ISSUE THREAD

**Issue by kalavattam** [ewels/MultiQC#1852]
### Description of bug

Encounter the following error when trying to run MultiQC with log (stdout) from having run `umi_tools dedup`: `ValueError: invalid literal for int() with base 10: '7350293, Read pairs: 7350293'`

```txt
/// MultiQC | v1.14

|           multiqc | Search path : /fh/fast/tsukiyama_t/grp/tsukiyamalab/kalavatt/2022_transcriptome-construction/results/2023-0115/test_UMI-processing_umi-tools/STAR/umi-tools_dedup_adjusted_rm-unmapped_5782
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 14/14
╭───────────────────────────────────────────────── Oops! The 'umitools' MultiQC module broke... ─────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                  │
│ Please attach a file that triggers the error. The last file found was: ./5782_Q_IN_S8.UMIs_trim.stdout.txt                                     │
│                                                                                                                                                │
│ Traceback (most recent call last):                                                                                                             │
│   File "/home/kalavatt/miniconda3/envs/Trinity_env/lib/python3.10/site-packages/multiqc/multiqc.py", line 654, in run                          │
│     output = mod()                                                                                                                             │
│   File "/home/kalavatt/miniconda3/envs/Trinity_env/lib/python3.10/site-packages/multiqc/modules/umitools/umitools.py", line 36, in __init__    │
│     input_fname, data = self.parse_logs(f["f"])                                                                                                │
│   File "/home/kalavatt/miniconda3/envs/Trinity_env/lib/python3.10/site-packages/multiqc/modules/umitools/umitools.py", line 123, in parse_logs │
│     logdata[key] = value[1](line.partition(value[0])[2])                                                                                       │
│ ValueError: invalid literal for int() with base 10: '7350293, Read pairs: 7350293'                                                             │
│                                                                                                                                                │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

### File that triggers the error

[5782_Q_IN_S8.UMIs_trim.stdout.txt](https://github.com/ewels/MultiQC/files/10551909/5782_Q_IN_S8.UMIs_trim.stdout.txt)

### MultiQC Error log

```console
❯ ls -lhaFG
total 1.1G
drwxrws--- 2 kalavatt  751 Jan 31 09:14 ./
drwxrws--- 6 kalavatt 3.0K Jan 31 15:21 ../
-rw-rw---- 1 kalavatt 458M Jan 31 08:57 5782_Q_IN_S8.UMIs.dedu.bam
-rw-rw---- 1 kalavatt  327 Jan 31 08:58 5782_Q_IN_S8.UMIs.stats_edit_distance.tsv
-rw-rw---- 1 kalavatt  434 Jan 31 08:58 5782_Q_IN_S8.UMIs.stats_per_umi_per_position.tsv
-rw-rw---- 1 kalavatt 1.8M Jan 31 08:58 5782_Q_IN_S8.UMIs.stats_per_umi.tsv
-rw-rw---- 1 kalavatt    0 Jan 31 08:48 5782_Q_IN_S8.UMIs.stderr.txt
-rw-rw---- 1 kalavatt  13K Jan 31 08:58 5782_Q_IN_S8.UMIs.stdout.txt
-rw-rw---- 1 kalavatt  341 Jan 31 08:58 5782_Q_IN_S8.UMIs.time.txt
-rw-rw---- 1 kalavatt 473M Jan 31 09:10 5782_Q_IN_S8.UMIs_trim.dedu.bam
-rw-rw---- 1 kalavatt  328 Jan 31 09:10 5782_Q_IN_S8.UMIs_trim.stats_edit_distance.tsv
-rw-rw---- 1 kalavatt  434 Jan 31 09:10 5782_Q_IN_S8.UMIs_trim.stats_per_umi_per_position.tsv
-rw-rw---- 1 kalavatt 1.8M Jan 31 09:10 5782_Q_IN_S8.UMIs_trim.stats_per_umi.tsv
-rw-rw---- 1 kalavatt    0 Jan 31 09:00 5782_Q_IN_S8.UMIs_trim.stderr.txt
-rw-rw---- 1 kalavatt 9.0K Jan 31 09:10 5782_Q_IN_S8.UMIs_trim.stdout.txt
-rw-rw---- 1 kalavatt  341 Jan 31 09:10 5782_Q_IN_S8.UMIs_trim.time.txt

❯ multiqc .
```

**Comment by ewels** [comment]
Duplicate of https://github.com/ewels/MultiQC/issues/1845 - tested the example file and it works fine on the development version.

Thanks for reporting anyway!
