### ISSUE TITLE
DRAGEN: Oops! The 'somalier' MultiQC module broke..

### ISSUE THREAD

**Issue by gaiaandreoletti** [ewels/MultiQC#1867]
### Description of bug

I have received the error message below and am unsure how to proceed.
I am running the DRAGEN v4.0 RNAseq pipeline. Never had this issue before...

Thank you for the help.
Gaia

### File that triggers the error

[48465A_4.wgs_fine_hist.csv](https://github.com/ewels/MultiQC/files/10710542/48465A_4.wgs_fine_hist.csv)

### MultiQC Error log

```console
[ERROR  ]         multiqc : Oops! The 'somalier' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module somalier raised an exception: Traceback (most recent call last):
  File "/bifx/apps/anaconda/lib/python2.7/site-packages/multiqc/multiqc.py", line 567, in run
    mod = config.avail_modules[this_module].load()
  File "/bifx/apps/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/bifx/apps/anaconda/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/bifx/apps/anaconda/lib/python2.7/site-packages/multiqc/modules/somalier/__init__.py", line 3, in <module>
    from .somalier import MultiqcModule
  File "/bifx/apps/anaconda/lib/python2.7/site-packages/multiqc/modules/somalier/somalier.py", line 698
    cols_return.append('rgba({},{},{},{})'.format(*cols_rgb, alpha))
SyntaxError: only named arguments may follow *expression
============================================================
[ERROR  ]         multiqc : Oops! The 'dragen' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./48465A_4/48465A_4.wgs_fine_hist.csv
============================================================
Module dragen raised an exception: Traceback (most recent call last):
  File "/bifx/apps/anaconda/lib/python2.7/site-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/bifx/apps/anaconda/lib/python2.7/site-packages/multiqc/modules/dragen/dragen.py", line 47, in __init__
    samples_found |= self.add_coverage_hist()
TypeError: unsupported operand type(s) for |=: 'set' and 'list'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by gaiaandreoletti** [comment]
updated to the latest version of multiQC and the issue was resolved. Apologies

**Comment by ewels** [comment]
Oh great! I only added the _"I am using the latest version of MultiQC"_ tickbox to the template a day or two ago. Glad that it's helping already! 😅
