### ISSUE TITLE
UnboundLocalError `sorted_pct` in kraken module

### ISSUE THREAD

**Issue by Midnighter** [ewels/MultiQC#1877]
### Description of bug

The kraken module fails with the below error. I think it's because the taxonomic ranks in my file are U, R, R1-7 rather than the typical U, R, P, C, etc.

### File that triggers the error

[kraken2.report.txt](https://github.com/ewels/MultiQC/files/10925082/kraken2.report.txt)

### MultiQC Error log

```console
multiqc kraken2.report.txt                                                                                                                                                               ─╯

  /// MultiQC 🔍 | v1.14

|           multiqc | Search path : /tmp/kraken2.report.txt
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
|            kraken | Found 1 reports
╭────────────────────────────────────────────────────────── Oops! The 'kraken' MultiQC module broke... ───────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                                   │
│ Please attach a file that triggers the error. The last file found was: kraken2.report.txt                                                                       │
│                                                                                                                                                                 │
│ Traceback (most recent call last):                                                                                                                              │
│   File "/home/moritz/.local/share/mambaforge/envs/tax/lib/python3.11/site-packages/multiqc/multiqc.py", line 654, in run                                        │
│     output = mod()                                                                                                                                              │
│              ^^^^^                                                                                                                                              │
│   File "/home/moritz/.local/share/mambaforge/envs/tax/lib/python3.11/site-packages/multiqc/modules/kraken/kraken.py", line 77, in __init__                      │
│     self.top_five_duplication_heatmap()                                                                                                                         │
│   File "/home/moritz/.local/share/mambaforge/envs/tax/lib/python3.11/site-packages/multiqc/modules/kraken/kraken.py", line 445, in top_five_duplication_heatmap │
│     for classif, pct_sum in sorted_pct:                                                                                                                         │
│                             ^^^^^^^^^^                                                                                                                          │
│ UnboundLocalError: cannot access local variable 'sorted_pct' where it is not associated with a value                                                            │
│                                                                                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry about this issue and it took so long to resolve!

Should be fixed now with https://github.com/ewels/MultiQC/pull/2230
