### ISSUE TITLE
cellranger module - KeyError, 10X scRNAseq data

### ISSUE THREAD

**Issue by Fattigman** [ewels/MultiQC#1889]
```
╭─────────────────────────────────── Oops! The 'cellranger' MultiQC module broke... ────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                         │
│ Please attach a file that triggers the error. The last file found was: ./web_summary.html                             │
│
│ Traceback (most recent call last):                                                                                    │
│   File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 654, in run                                 │
│     output = mod()                                                                                                    │
│              ^^^^^                                                                                                    │
│   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/cellranger/cellranger.py", line 39, in __init__       │
│     n["count"] = self.parse_count_html()                                                                              │
│                  ^^^^^^^^^^^^^^^^^^^^^^^                                                                              │
│   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/cellranger/count.py", line 30, in parse_count_html    │
│     self.parse_count_report(f)                                                                                        │
│   File "/usr/local/lib/python3.11/site-packages/multiqc/modules/cellranger/count.py", line 245, in parse_count_report │
│     warnings[alarm["id"]] = "FAIL"                                                                                    │
│              ~~~~~^^^^^^                                                                                              │
│ KeyError: 'id' 
```

This happens for all of my scRNAseq 10X multiqc reports. 
I am using cellranger 7.0.0
I run multiqc simply by ```singularity run /path/to/multiqc.simg multiqc .``` on the folder with my cellranger output

**Comment by Fattigman** [comment]
You are correct. I ran it with the 1.15dev and it worked, so the changes you made their seems to have fixed the issue.

Thank you very much!
