### ISSUE TITLE
SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by DaniEstevezBarcia** [ewels/MultiQC#1917]
### Description of bug

Hello,

For some reason I cannot run multiqc in the cluster where I am working. See the steps I took and the document I attach with the error message.

After creating a new conda environment in the cluster

`conda create -y --name utils python=3.6`

I installed multiqc

`conda install -c bioconda multiqc`

And the run it to a folder containing all my fastqc analysis. I receive then the error message that I detail below.

Is there any way to solve this?

Thank you

### MultiQC Error log

```console
$ multiqc fastqc/1stBatch/
Traceback (most recent call last):
  File "/home/daeb/miniforge3/envs/utils/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import run_multiqc
  File "/home/daeb/miniforge3/envs/utils/lib/python3.6/site-packages/multiqc/__init__.py", line 16, in <module>
    from .multiqc import run
  File "/home/daeb/miniforge3/envs/utils/lib/python3.6/site-packages/multiqc/multiqc.py", line 27, in <module>
    import rich_click as click
  File "/home/daeb/miniforge3/envs/utils/lib/python3.6/site-packages/rich_click/__init__.py", line 16, in <module>
    from rich_click.rich_command import RichCommand
  File "/home/daeb/miniforge3/envs/utils/lib/python3.6/site-packages/rich_click/rich_command.py", line 5, in <module>
    from rich_click.rich_click import rich_abort_error, rich_format_error, rich_format_help
  File "/home/daeb/miniforge3/envs/utils/lib/python3.6/site-packages/rich_click/rich_click.py", line 5, in <module>
    import rich.markdown
  File "/home/daeb/miniforge3/envs/utils/lib/python3.6/site-packages/rich/markdown.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by DaniEstevezBarcia** [comment]
I fixed it! Seeing the error I thought that it was about the python version:

I created a conda environment with python 3.5.

Then I installed multiqc but instead of using bioconda I just used conda install multiqc (in the video instructions I believe it is done specifying the channel, I saw the warning much later in the documentation).

**Comment by ewels** [comment]
> in the video instructions I believe it is done specifying the channel

Ahh, good spot! Thanks for telling me this, I thought I had updated everywhere but I never thought of checking the video!
