### ISSUE TITLE
Job not completing

### ISSUE THREAD

**Issue by hillms** [ewels/MultiQC#1924]
Hello,

I am trying to compile fastqc outputs, but the job keeps canceling. I have used multiqc many times, including on the cluster that I am currently working on. 

I have already updated my base conda and multiqc. Could you please help me troubleshoot this?

multiqc --version 1.0.dev0

```
/home/user/anaconda3/envs/multiqc/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/utils/config.py:44: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/home/user/anaconda3/envs/multiqc/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/utils/config.py:50: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]          fastqc : Found 270 reports
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/home/user/anaconda3/envs/multiqc/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/home/user/anaconda3/envs/multiqc/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 91, in __init__
    self.fastqc_general_stats()
  File "/home/user/anaconda3/envs/multiqc/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/fastqc/fastqc.py", line 200, in fastqc_general_stats
    'avg_sequence_length': bs['avg_sequence_length'],
KeyError: 'avg_sequence_length'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
MultiQC v1.0.dev0 is over six years old.

Please update to the latest version - v1.14 - and try again. I can reopen the issue if it persists.

**Comment by ewels** [comment]
Ah just re-read this bit:

> I have already updated my base conda and multiqc.

In that case, your conda installation probably didn't work. Please see the warning in the [docs](https://multiqc.info/docs/getting_started/installation/#conda-1):

> The order of conda channels is important. Do not use `-c bioconda` in the installation command, weird stuff can happen (like only being able to install very old versions).

Bioconda channel docs [here](https://bioconda.github.io/#usage):

```bash
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```
