### ISSUE TITLE
Deeptools float conversion crash fails entire workflow

### ISSUE THREAD

**Issue by FelixKrueger** [ewels/MultiQC#1939]
### Description of bug

I've got a run where a file MultiQC complains that it can't convert the string `--` to a float - fair enough. However, this crashes the nf-core/chipseq pipeline; in standalone mode the error also occurs, but the MultiQC report still gets generated (withtout deeptools plots). Is there something that could be done to change that? 

I appreciate that the input sample might have some rather horrible qualities (only 2600 sequences in total) as it was a negative control - but still it would be nice if it wouldn't crash the entire workflow.

### File that triggers the error

[buggedFile.mLb.clN.plotProfile.txt](https://github.com/ewels/MultiQC/files/11785752/buggedFile.mLb.clN.plotProfile.txt)

### MultiQC Error log

```console
$ multiqc .

/// MultiQC 🔍 | v1.14

|           multiqc | Search path : /share/Data/
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1769/1769
|    custom_content | nsc_coefficient: Found 40 samples (bargraph)
|    custom_content | rsc_coefficient: Found 40 samples (bargraph)
|    custom_content | strand_shift_correlation: Found 40 samples (linegraph)
|phantompeakqualtools | Found 40 logs
|            preseq | Found 38 reports
╭────────────────────────────────────────────────────────── Oops! The 'deeptools' MultiQC module broke... ──────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                                     │
│ Please attach a file that triggers the error. The last file found was: ./bowtie2/mergedLibrary/deepTools/plotProfile/buggedFile.mLb.clN.plotProfile.tab │
│                                                                                                                                                                   │
│ Traceback (most recent call last):                                                                                                                                │
│   File "/share/fkrueger/mambaforge-pypy3/envs/INDEX/lib/python3.10/site-packages/multiqc/multiqc.py", line 654, in run                                            │
│     output = mod()                                                                                                                                                │
│   File "/share/fkrueger/mambaforge-pypy3/envs/INDEX/lib/python3.10/site-packages/multiqc/modules/deeptools/deeptools.py", line 96, in __init__                    │
│     n["plotProfile"] = self.parse_plotProfile()                                                                                                                   │
│   File "/share/fkrueger/mambaforge-pypy3/envs/INDEX/lib/python3.10/site-packages/multiqc/modules/deeptools/plotProfile.py", line 16, in parse_plotProfile         │
│     parsed_data, bin_labels, converted_bin_labels = self.parsePlotProfileData(f)                                                                                  │
│   File "/share/fkrueger/mambaforge-pypy3/envs/INDEX/lib/python3.10/site-packages/multiqc/modules/deeptools/plotProfile.py", line 149, in parsePlotProfileData     │
│     d[s_name].update({converted_bin_labels[i - 1]: float(cols[i + 1])})                                                                                           │
│ ValueError: could not convert string to float: '--'                                                                                                               │
│                                                                                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|            picard | Found 40 AlignmentSummaryMetrics reports
|            picard | Found 80 BaseDistributionByCycleMetrics reports
|            picard | Found 40 InsertSizeMetrics reports
|            picard | Found 40 MarkDuplicates reports
|            picard | Found 40 QualityByCycleMetrics reports
|            picard | Found 40 QualityScoreDistributionMetrics reports
|          samtools | Found 80 stats reports
|          samtools | Found 80 flagstat reports
|          samtools | Found 80 idxstats reports
|          cutadapt | Found 80 reports
|            fastqc | Found 162 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
|           multiqc | 9 flat-image plots used in the report due to large sample numbers
|           multiqc | To force interactive plots, use the '--interactive' flag. See the documentation.
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Sorry for this issue and that it took so long! Finally resolved it with https://github.com/ewels/MultiQC/pull/2229, should be out with the next release on Friday :)
