### ISSUE TITLE
kaiju module - UnboundLocalError

### ISSUE THREAD

**Issue by mdtorohernando** [ewels/MultiQC#1947]
(Kaiju) pgen@pgen:/media/pgen/Disco_2/GEN00462_Javi_shotgun/4_Fastq_clean/unmapped_host/assembly/contigs/Kaiju_nr_euk_contigs$ multiqc .

  /// MultiQC 🔍 | v1.14

|           multiqc | Search path : /media/pgen/Disco_2/GEN00462_Javi_shotgun/4_Fastq_clean/unmapped_host/assembly/contigs/Kaiju_nr_euk_contigs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 69/69  
╭───────────────────────────────────────────────── Oops! The 'kaiju' MultiQC module broke... ─────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                               │
│ Please attach a file that triggers the error. The last file found was: ./sample23.kaiju_nr_euk_summary_genus.tsv                            │
│                                                                                                                                             │
│ Traceback (most recent call last):                                                                                                          │
│   File "/home/pgen/mambaforge/envs/Kaiju/lib/python3.11/site-packages/multiqc/multiqc.py", line 654, in run                                 │
│     output = mod()                                                                                                                          │
│              ^^^^^                                                                                                                          │
│   File "/home/pgen/mambaforge/envs/Kaiju/lib/python3.11/site-packages/multiqc/modules/kaiju/kaiju.py", line 32, in __init__                 │
│     taxo_rank, parsed_data = self.parse_kaiju2table_report(f)                                                                               │
│                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                               │
│   File "/home/pgen/mambaforge/envs/Kaiju/lib/python3.11/site-packages/multiqc/modules/kaiju/kaiju.py", line 97, in parse_kaiju2table_report │
│     return taxo_rank, parsed_data                                                                                                           │
│            ^^^^^^^^^                                                                                                                        │
│ UnboundLocalError: cannot access local variable 'taxo_rank' where it is not associated with a value                                         │
│                                                                                                                                             │
╰──────────────────────────────────────────────────────────────
![kaiju](https://github.com/ewels/MultiQC/assets/26143966/9d36a608-738a-4be6-8346-ea79572e56e6)
───────────────────────────────────────────────────────────────────────────────╯
|           multiqc | No analysis results found. Cleaning up..
|           multiqc | MultiQC complete

**Comment by vladsavelyev** [comment]
@mdtorohernando, thank you for reporting the issue! Should be fixed in https://github.com/ewels/MultiQC/pull/2023 now

**Comment by ewels** [comment]
Thanks @mdtorohernando ! Next time, please use the provided issue template and supply an example file or two that triggers this error.

@vladsavelyev has fixed it in #2023 , but without any test data we can't be sure that there won't be other, secondary bugs hiding behind it.

**Comment by mdtorohernando** [comment]
Oh so sorry!!! I didn't know. Thank you very much for your attention.

**Comment by vladsavelyev** [comment]
@mdtorohernando, if you are around, could you provide the input that triggered that error, please? Ideally, through creating a PR into https://github.com/ewels/MultiQC_TestData/tree/master/data/modules/kaiju/issue_1947

In the currently existing test examples for Kaiju, all file have a "cannot be assigned" line second before the end, so they would never trigger this error. But it looks like your test for some reason didn't have that line.

**Comment by mdtorohernando** [comment]
I’m out on a travel. I can try to send you files next Monday!! Sorry !!
