### ISSUE TITLE
Oops! The 'cellranger' MultiQC module broke...

### ISSUE THREAD

**Issue by apeleraux** [ewels/MultiQC#1965]
### Description of bug

I am using a SnakeMake wrapper for multiQC as shown in the code of the SnakeMake rule below. Please find attached the log file and the CellRanger-derived web_summary file probably causing the crash. 

### File that triggers the error

[web_summary.zip](https://github.com/ewels/MultiQC/files/12240673/web_summary.zip)

### MultiQC Error log

```console
CODE:

rule multiqc:
    input:
        multiqc_input
    output:
        report(f"{OUTDIR}/qc/multiqc_report.html", caption="../report/conf/multiqc.rst", category="1_QC")
    params:
        extra = config["parameters"]["multiqc"]
    benchmark:
        "{}/multiqc.bmk".format(LOGDIR)
    log:
        "{}/multiqc.log".format(LOGDIR)
    threads: get_resource("multiqc","threads")
    resources:
        mem=get_resource("multiqc","mem"),
        walltime=get_resource("multiqc","walltime")
    wrapper:
        "v2.2.1/bio/multiqc"    # THIS IS THE VERSION 1.14 OF MULTIQC, WHICH SUPPORTS CELLRANGER



LOG FILE:

  /// MultiQC 🔍 | v1.14 (ac480ca)

|           multiqc | Report title: CNIO Bioinformatics Unit Single-Cell sequencing QC.
|           multiqc | Search path : /common/workdir/scRNAseq-bollito/results/cellranger_count/002_NB_02003_D1/outs
|           multiqc | Search path : /common/workdir/scRNAseq-bollito/logs/rseqc/rseqc_junction_annotation
|           multiqc | Search path : /common/workdir/scRNAseq-bollito/results/cellranger_count/004_NB_02001_D1/outs
|           multiqc | Search path : /common/workdir/scRNAseq-bollito/results/qc/fastqc
|           multiqc | Search path : /common/workdir/scRNAseq-bollito/results/qc/rseqc
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 145/145  
|             rseqc | Found 2 read_distribution reports
|             rseqc | Found 2 read_gc reports
|             rseqc | Found 2 read_duplication reports
|             rseqc | Found 2 junction_annotation reports
|             rseqc | Found 2 junction_saturation reports
|             rseqc | Found 2 infer_experiment reports
|             rseqc | Found 2 bam_stat reports
╭─────────────────────────────────────────────────────────────────────── Oops! The 'cellranger' MultiQC module broke... ────────────────────────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                                                                 │
│ Please attach a file that triggers the error. The last file found was: results/cellranger_count/002_NB_02003_D1/outs/web_summary.html                                                         │
│                                                                                                                                                                                               │
│ Traceback (most recent call last):                                                                                                                                                            │
│   File "/common/workdir/scRNAseq-bollito/.snakemake/conda/2c2a99d9359eb0b8996ac893d143eb43/lib/python3.11/site-packages/multiqc/multiqc.py", line 654, in run                                 │
│     output = mod()                                                                                                                                                                            │
│              ^^^^^                                                                                                                                                                            │
│   File "/common/workdir/scRNAseq-bollito/.snakemake/conda/2c2a99d9359eb0b8996ac893d143eb43/lib/python3.11/site-packages/multiqc/modules/cellranger/cellranger.py", line 39, in __init__       │
│     n["count"] = self.parse_count_html()                                                                                                                                                      │
│                  ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                      │
│   File "/common/workdir/scRNAseq-bollito/.snakemake/conda/2c2a99d9359eb0b8996ac893d143eb43/lib/python3.11/site-packages/multiqc/modules/cellranger/count.py", line 30, in parse_count_html    │
│     self.parse_count_report(f)                                                                                                                                                                │
│   File "/common/workdir/scRNAseq-bollito/.snakemake/conda/2c2a99d9359eb0b8996ac893d143eb43/lib/python3.11/site-packages/multiqc/modules/cellranger/count.py", line 245, in parse_count_report │
│     warnings[alarm["id"]] = "FAIL"                                                                                                                                                            │
│              ~~~~~^^^^^^                                                                                                                                                                      │
│ KeyError: 'id'                                                                                                                                                                                │
│                                                                                                                                                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|            fastqc | Found 8 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : results/qc/multiqc_report.html
|           multiqc | Data        : results/qc/multiqc_report_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by apeleraux** [comment]
I have actually rerun this code, and equivalent code using multiqc command (with multiqc v1.14) rather than the Snakemake wrapper, and got it to work fine. So somehow the bug has vanished...

**Comment by ewels** [comment]
Great! Note that several CellRanger bugs like this have been fixed in the development version (see the [changelog](https://github.com/ewels/MultiQC/blob/master/CHANGELOG.md)). I'm hopefully doing a release today, but it'll definitely be worth updating 😊

**Comment by apeleraux** [comment]
Perfect, thanks a lot !
Annick

De : Phil Ewels ***@***.***>
Envoyé : vendredi 4 août 2023 07:43
À : ewels/MultiQC ***@***.***>
Cc : Peleraux, Annick /FR ***@***.***>; State change ***@***.***>
Objet : Re: [ewels/MultiQC] Oops! The 'cellranger' MultiQC module broke... (Issue #1965)


Great! Note that several CellRanger bugs like this have been fixed in the development version (see the changelog<https://github.com/ewels/MultiQC/blob/master/CHANGELOG.md>). I'm hopefully doing a release today, but it'll definitely be worth updating 😊
