### ISSUE TITLE
Fastqc not working

### ISSUE THREAD

**Issue by Tasmiapotato** [ewels/MultiQC#1974]
### Description of bug

I am installing fastqc on ubuntu but it is giving these errors. what should i do?
~$ fastqc
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/java.awt.Frame.<init>(Frame.java:393)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at uk.ac.babraham.FastQC.FastQCApplication.<init>(FastQCApplication.java:63)
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:338)

(i have exported xvfb, xorg and changed display to 0,1,10,0.0)

### File that triggers the error

~$ fastqc
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
        at java.desktop/java.awt.Window.<init>(Window.java:553)
        at java.desktop/java.awt.Frame.<init>(Frame.java:428)
        at java.desktop/java.awt.Frame.<init>(Frame.java:393)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at uk.ac.babraham.FastQC.FastQCApplication.<init>(FastQCApplication.java:63)
        at uk.ac.babraham.FastQC.FastQCApplication.main(FastQCApplication.java:338)

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by bounlu** [comment]
`apt install fastqc`

**Comment by vladsavelyev** [comment]
@Tasmiapotato FastQC is a tool separate from MultiQC. Please look for help on other resources :) This one particularly is an old and common problem, e.g.: https://www.biostars.org/p/160144/
