### ISSUE TITLE
Module breaks with QUAST file: IndexError: list index out of range

### ISSUE THREAD

**Issue by eam12** [ewels/MultiQC#1980]
### Description of bug

Hello,

Many thanks for creating such a fabulous tool! I am running MultiQC version 1.15 on a number of QUAST outputs, but am encountering the following error for the attached QUAST output (`SRR6663578_quast.tar.gz`). I've run thousands of files so I'm not sure what the issue is with this one. Any help would be much appreciated!

Thanks so much,
Liz

```
$ multiqc --profile-runtime -o /home/johnsont/millere/quast_multiqc_test /home/johnsont/millere/quast_multiqc_test/.

   /// MultiQC 🔍 | v1.15

|           multiqc | Search path : /home/johnsont/millere/quast_multiqc_test
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 6/6  
|            report | Profile-runtime: Searching files took 0.05s
╭─────────────────────────────────────────────────── Oops! The 'quast' MultiQC module broke... ────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                    │
│ Please attach a file that triggers the error. The last file found was: /home/johnsont/millere/quast_multiqc_test/./SRR6663578_quast/report.tsv   │
│                                                                                                     
[SRR6663578_quast.tar.gz](https://github.com/ewels/MultiQC/files/12338056/SRR6663578_quast.tar.gz)
                                             │
│ Traceback (most recent call last):                                                                                                               │
│   File "/home/johnsont/shared/.conda/envs/multiqc_1.15/lib/python3.11/site-packages/multiqc/multiqc.py", line 654, in run                        │
│     output = mod()                                                                                                                               │
│              ^^^^^                                                                                                                               │
│   File "/home/johnsont/shared/.conda/envs/multiqc_1.15/lib/python3.11/site-packages/multiqc/modules/quast/quast.py", line 42, in __init__        │
│     self.parse_quast_log(f)                                                                                                                      │
│   File "/home/johnsont/shared/.conda/envs/multiqc_1.15/lib/python3.11/site-packages/multiqc/modules/quast/quast.py", line 93, in parse_quast_log │
│     s_names = lines[0].split("\t")                                                                                                               │
│               ~~~~~^^^                                                                                                                           │
│ IndexError: list index out of range                                                                                                              │
│                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|   profile_runtime | Running run time profiling module
|           multiqc | Report      : ../../../../../../../home/johnsont/millere/quast_multiqc_test/multiqc_report.html
|           multiqc | Data        : ../../../../../../../home/johnsont/millere/quast_multiqc_test/multiqc_data
|           multiqc | Run took 2.77 seconds
|           multiqc |  - 0.05s: Searching files
|           multiqc |  - 0.48s: Running modules
|           multiqc |  - 0.00s: Compressing report data
|           multiqc | For more information, see the 'Run Time' section in ../../../../../../../home/johnsont/millere/quast_multiqc_test/multiqc_report.html
|           multiqc | Flat-image plots used. Disable with '--interactive'. See docs.
|           multiqc | MultiQC complete
```

### File that triggers the error

[SRR6663578_quast.zip](https://github.com/ewels/MultiQC/files/12338072/SRR6663578_quast.zip)

### MultiQC Error log

```console
$ multiqc --profile-runtime -o /home/johnsont/millere/quast_multiqc_test /home/johnsont/millere/quast_multiqc_test/.

  /// MultiQC 🔍 | v1.15

|           multiqc | Search path : /home/johnsont/millere/quast_multiqc_test
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 6/6  
|            report | Profile-runtime: Searching files took 0.05s
╭─────────────────────────────────────────────────── Oops! The 'quast' MultiQC module broke... ────────────────────────────────────────────────────╮
│ Please copy this log and report it at https://github.com/ewels/MultiQC/issues                                                                    │
│ Please attach a file that triggers the error. The last file found was: /home/johnsont/millere/quast_multiqc_test/./SRR6663578_quast/report.tsv   │
│                                                                                                                                                  │
│ Traceback (most recent call last):                                                                                                               │
│   File "/home/johnsont/shared/.conda/envs/multiqc_1.15/lib/python3.11/site-packages/multiqc/multiqc.py", line 654, in run                        │
│     output = mod()                                                                                                                               │
│              ^^^^^                                                                                                                               │
│   File "/home/johnsont/shared/.conda/envs/multiqc_1.15/lib/python3.11/site-packages/multiqc/modules/quast/quast.py", line 42, in __init__        │
│     self.parse_quast_log(f)                                                                                                                      │
│   File "/home/johnsont/shared/.conda/envs/multiqc_1.15/lib/python3.11/site-packages/multiqc/modules/quast/quast.py", line 93, in parse_quast_log │
│     s_names = lines[0].split("\t")                                                                                                               │
│               ~~~~~^^^                                                                                                                           │
│ IndexError: list index out of range                                                                                                              │
│                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
|   profile_runtime | Running run time profiling module
|           multiqc | Report      : ../../../../../../../home/johnsont/millere/quast_multiqc_test/multiqc_report.html
|           multiqc | Data        : ../../../../../../../home/johnsont/millere/quast_multiqc_test/multiqc_data
|           multiqc | Run took 2.77 seconds
|           multiqc |  - 0.05s: Searching files
|           multiqc |  - 0.48s: Running modules
|           multiqc |  - 0.00s: Compressing report data
|           multiqc | For more information, see the 'Run Time' section in ../../../../../../../home/johnsont/millere/quast_multiqc_test/multiqc_report.html
|           multiqc | Flat-image plots used. Disable with '--interactive'. See docs.
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/#troubleshooting-1).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
@eam12, thanks for reporting the issue!

It looks like QUAST didn't finish successfully, and its expected output (`report.tsv`) is empty. 

To debug it further, this is the tail of `quast.log`:

```
[Errno 5] Input/output error: '/scratch.global/johnsont/out_Typhimurium/assemblies/quast/SRR6663578_quast/report.tsv'
Traceback (most recent call last):
  File "/home/johnsont/shared/.conda/envs/4_assembly/bin/quast.py", line 309, in <module>
    return_code = main(sys.argv[1:])
  File "/home/johnsont/shared/.conda/envs/4_assembly/bin/quast.py", line 230, in main
    reports_fpaths, transposed_reports_fpaths = reporting.save_total(output_dirpath)
  File "/home/johnsont/shared/.conda/envs/4_assembly/lib/python3.8/site-packages/quast_libs/reporting.py", line 761, in save_total
    return save(output_dirpath, qconfig.report_prefix, qconfig.transposed_report_prefix, Fields.order, silent=silent)
  File "/home/johnsont/shared/.conda/envs/4_assembly/lib/python3.8/site-packages/quast_libs/reporting.py", line 716, in save
    save_tsv(report_tsv_fpath, all_rows)
  File "/home/johnsont/shared/.conda/envs/4_assembly/lib/python3.8/site-packages/quast_libs/reporting.py", line 563, in save_tsv
    tsv_file = open(fpath, 'w')
OSError: [Errno 5] Input/output error: '/scratch.global/johnsont/out_Typhimurium/assemblies/quast/SRR6663578_quast/report.tsv'
```

It looks like QUAST was trying to create a file under `/scratch.global/johnsont/out_Typhimurium/assemblies/quast/SRR6663578_quast/report.tsv`, but the operating system didn't let it do it. Is there any chance that the output folder was moved in the middle of execution, for instance, `/scratch.global` was automatically cleaned up?

**Comment by eam12** [comment]
Whoops! I should have noticed `report.tsv` was empty. We've been experiencing a lot of issues with our HPC systems recently so it looks like QUAST didn't finish successfully on quite a number of samples. As far as I can tell, the output folder wasn't moved, deleted, etc. I have tried running MultiQC on this (and similar incomplete output directories) several times in different output directories and I continue to get the same error message.

**Comment by vladsavelyev** [comment]
@eam12 another suggestion is that there is some sort of race condition, happening from multiple instances of QUAST trying to write the same file. Any chance a few instances of QUAST were running on `SRR6663578`?

Otherwise, without the reproducible data, unfortunately, I don't have ideas what might be causing an I/O error here. It would be good to report this issue in [QUAST repo](https://github.com/ablab/quast).
