### ISSUE TITLE
Python 3.12 installation problems

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#2112]
Originally reported [in the community forum](https://community.seqera.io/t/multiqc-modulenotfounderror-no-module-named-imp/147/2)

---

Looks like MultiQC is having some problems running in Conda with Python 3.12, due to a dependency error of some kind:

```console
❯ conda create --name py3.12 python=3.12 multiqc --yes --quiet
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/ewels/.miniconda3/miniconda3/envs/py3.12

  added / updated specs:
    - multiqc
    - python=3.12


The following packages will be downloaded:
```

<details>

```
    package                    |            build
    ---------------------------|-----------------
    brotli-1.1.0               |       hb547adb_1          19 KB  conda-forge
    brotli-bin-1.1.0           |       hb547adb_1          17 KB  conda-forge
    brotli-python-1.1.0        |  py312h9f69965_1         335 KB  conda-forge
    ca-certificates-2023.7.22  |       hf0a4a13_0         146 KB  conda-forge
    certifi-2023.7.22          |     pyhd8ed1ab_0         150 KB  conda-forge
    charset-normalizer-3.3.0   |     pyhd8ed1ab_0          45 KB  conda-forge
    click-8.1.7                |unix_pyh707e725_0          82 KB  conda-forge
    contourpy-1.1.1            |  py312h389731b_1         222 KB  conda-forge
    cycler-0.12.1              |     pyhd8ed1ab_0          13 KB  conda-forge
    fonttools-4.43.1           |  py312he37b823_0         2.5 MB  conda-forge
    freetype-2.12.1            |       hadb7bae_2         582 KB  conda-forge
    humanfriendly-10.0         |     pyhd8ed1ab_6          72 KB  conda-forge
    importlib-metadata-6.8.0   |     pyha770c72_0          25 KB  conda-forge
    kiwisolver-1.4.5           |  py312h389731b_1          60 KB  conda-forge
    lcms2-2.15                 |       hf2736f0_3         210 KB  conda-forge
    libblas-3.9.0              |18_osxarm64_openblas          15 KB  conda-forge
    libbrotlicommon-1.1.0      |       hb547adb_1          67 KB  conda-forge
    libbrotlidec-1.1.0         |       hb547adb_1          28 KB  conda-forge
    libbrotlienc-1.1.0         |       hb547adb_1         274 KB  conda-forge
    libcblas-3.9.0             |18_osxarm64_openblas          14 KB  conda-forge
    libcxx-16.0.6              |       h4653b0c_0         1.1 MB  conda-forge
    libdeflate-1.19            |       hb547adb_0          52 KB  conda-forge
    libgfortran-5.0.0          |13_2_0_hd922786_1         108 KB  conda-forge
    libgfortran5-13.2.0        |       hf226fd6_1         972 KB  conda-forge
    libjpeg-turbo-3.0.0        |       hb547adb_1         535 KB  conda-forge
    liblapack-3.9.0            |18_osxarm64_openblas          14 KB  conda-forge
    libopenblas-0.3.24         |openmp_hd76b1f2_0         2.7 MB  conda-forge
    libsqlite-3.43.2           |       h091b4b1_0         790 KB  conda-forge
    libtiff-4.6.0              |       ha8a6c65_2         240 KB  conda-forge
    libwebp-base-1.3.2         |       hb547adb_0         267 KB  conda-forge
    libxcb-1.15                |       hf346824_0         327 KB  conda-forge
    llvm-openmp-17.0.2         |       h1c12783_0         269 KB  conda-forge
    markdown-3.5               |     pyhd8ed1ab_0          75 KB  conda-forge
    markdown-it-py-3.0.0       |     pyhd8ed1ab_0          63 KB  conda-forge
    markupsafe-2.1.3           |  py312h02f2b3b_1          26 KB  conda-forge
    matplotlib-base-3.8.0      |  py312hba9b818_2         7.5 MB  conda-forge
    multiqc-1.16               |     pyhdfd78af_0         1.0 MB  bioconda
    networkx-3.1               |     pyhd8ed1ab_0         1.4 MB  conda-forge
    numpy-1.26.0               |  py312h696b312_0         5.9 MB  conda-forge
    openjpeg-2.5.0             |       h4c1507b_3         316 KB  conda-forge
    openssl-3.1.3              |       h53f4e23_0         2.1 MB  conda-forge
    packaging-23.2             |     pyhd8ed1ab_0          48 KB  conda-forge
    pillow-10.0.1              |  py312hb653a51_2        43.8 MB  conda-forge
    pip-23.2.1                 |     pyhd8ed1ab_0         1.3 MB  conda-forge
    pthread-stubs-0.4          |    h27ca646_1001           6 KB  conda-forge
    pygments-2.16.1            |     pyhd8ed1ab_0         833 KB  conda-forge
    pyparsing-3.1.1            |     pyhd8ed1ab_0          87 KB  conda-forge
    python-3.12.0              |h47c9636_0_cpython        12.7 MB  conda-forge
    python_abi-3.12            |          4_cp312           6 KB  conda-forge
    pyyaml-6.0.1               |  py312h02f2b3b_1         178 KB  conda-forge
    requests-2.31.0            |     pyhd8ed1ab_0          55 KB  conda-forge
    rich-13.6.0                |     pyhd8ed1ab_0         179 KB  conda-forge
    rich-click-1.7.0           |     pyhd8ed1ab_0          32 KB  conda-forge
    setuptools-68.2.2          |     pyhd8ed1ab_0         454 KB  conda-forge
    simplejson-3.19.2          |  py312he37b823_0         126 KB  conda-forge
    tk-8.6.13                  |       hb31c410_0         3.1 MB  conda-forge
    typing_extensions-4.8.0    |     pyha770c72_0          34 KB  conda-forge
    urllib3-2.0.6              |     pyhd8ed1ab_0          96 KB  conda-forge
    wheel-0.41.2               |     pyhd8ed1ab_0          56 KB  conda-forge
    xorg-libxau-1.0.11         |       hb547adb_0          13 KB  conda-forge
    zipp-3.17.0                |     pyhd8ed1ab_0          19 KB  conda-forge
    zstd-1.5.5                 |       h4f39d0f_0         391 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        94.0 MB

The following NEW packages will be INSTALLED:

  brotli             conda-forge/osx-arm64::brotli-1.1.0-hb547adb_1
  brotli-bin         conda-forge/osx-arm64::brotli-bin-1.1.0-hb547adb_1
  brotli-python      conda-forge/osx-arm64::brotli-python-1.1.0-py312h9f69965_1
  bzip2              conda-forge/osx-arm64::bzip2-1.0.8-h3422bc3_4
  ca-certificates    conda-forge/osx-arm64::ca-certificates-2023.7.22-hf0a4a13_0
  certifi            conda-forge/noarch::certifi-2023.7.22-pyhd8ed1ab_0
  charset-normalizer conda-forge/noarch::charset-normalizer-3.3.0-pyhd8ed1ab_0
  click              conda-forge/noarch::click-8.1.7-unix_pyh707e725_0
  coloredlogs        conda-forge/noarch::coloredlogs-15.0.1-pyhd8ed1ab_3
  colormath          conda-forge/noarch::colormath-3.0.0-py_2
  contourpy          conda-forge/osx-arm64::contourpy-1.1.1-py312h389731b_1
  cycler             conda-forge/noarch::cycler-0.12.1-pyhd8ed1ab_0
  fonttools          conda-forge/osx-arm64::fonttools-4.43.1-py312he37b823_0
  freetype           conda-forge/osx-arm64::freetype-2.12.1-hadb7bae_2
  future             conda-forge/noarch::future-0.18.3-pyhd8ed1ab_0
  humanfriendly      conda-forge/noarch::humanfriendly-10.0-pyhd8ed1ab_6
  idna               conda-forge/noarch::idna-3.4-pyhd8ed1ab_0
  importlib-metadata conda-forge/noarch::importlib-metadata-6.8.0-pyha770c72_0
  jinja2             conda-forge/noarch::jinja2-3.1.2-pyhd8ed1ab_1
  kiwisolver         conda-forge/osx-arm64::kiwisolver-1.4.5-py312h389731b_1
  lcms2              conda-forge/osx-arm64::lcms2-2.15-hf2736f0_3
  lerc               conda-forge/osx-arm64::lerc-4.0.0-h9a09cb3_0
  libblas            conda-forge/osx-arm64::libblas-3.9.0-18_osxarm64_openblas
  libbrotlicommon    conda-forge/osx-arm64::libbrotlicommon-1.1.0-hb547adb_1
  libbrotlidec       conda-forge/osx-arm64::libbrotlidec-1.1.0-hb547adb_1
  libbrotlienc       conda-forge/osx-arm64::libbrotlienc-1.1.0-hb547adb_1
  libcblas           conda-forge/osx-arm64::libcblas-3.9.0-18_osxarm64_openblas
  libcxx             conda-forge/osx-arm64::libcxx-16.0.6-h4653b0c_0
  libdeflate         conda-forge/osx-arm64::libdeflate-1.19-hb547adb_0
  libexpat           conda-forge/osx-arm64::libexpat-2.5.0-hb7217d7_1
  libffi             conda-forge/osx-arm64::libffi-3.4.2-h3422bc3_5
  libgfortran        conda-forge/osx-arm64::libgfortran-5.0.0-13_2_0_hd922786_1
  libgfortran5       conda-forge/osx-arm64::libgfortran5-13.2.0-hf226fd6_1
  libjpeg-turbo      conda-forge/osx-arm64::libjpeg-turbo-3.0.0-hb547adb_1
  liblapack          conda-forge/osx-arm64::liblapack-3.9.0-18_osxarm64_openblas
  libopenblas        conda-forge/osx-arm64::libopenblas-0.3.24-openmp_hd76b1f2_0
  libpng             conda-forge/osx-arm64::libpng-1.6.39-h76d750c_0
  libsqlite          conda-forge/osx-arm64::libsqlite-3.43.2-h091b4b1_0
  libtiff            conda-forge/osx-arm64::libtiff-4.6.0-ha8a6c65_2
  libwebp-base       conda-forge/osx-arm64::libwebp-base-1.3.2-hb547adb_0
  libxcb             conda-forge/osx-arm64::libxcb-1.15-hf346824_0
  libzlib            conda-forge/osx-arm64::libzlib-1.2.13-h53f4e23_5
  llvm-openmp        conda-forge/osx-arm64::llvm-openmp-17.0.2-h1c12783_0
  lzstring           conda-forge/noarch::lzstring-1.0.4-py_1001
  markdown           conda-forge/noarch::markdown-3.5-pyhd8ed1ab_0
  markdown-it-py     conda-forge/noarch::markdown-it-py-3.0.0-pyhd8ed1ab_0
  markupsafe         conda-forge/osx-arm64::markupsafe-2.1.3-py312h02f2b3b_1
  matplotlib-base    conda-forge/osx-arm64::matplotlib-base-3.8.0-py312hba9b818_2
  mdurl              conda-forge/noarch::mdurl-0.1.0-pyhd8ed1ab_0
  multiqc            bioconda/noarch::multiqc-1.16-pyhdfd78af_0
  munkres            conda-forge/noarch::munkres-1.1.4-pyh9f0ad1d_0
  ncurses            conda-forge/osx-arm64::ncurses-6.4-h7ea286d_0
  networkx           conda-forge/noarch::networkx-3.1-pyhd8ed1ab_0
  numpy              conda-forge/osx-arm64::numpy-1.26.0-py312h696b312_0
  openjpeg           conda-forge/osx-arm64::openjpeg-2.5.0-h4c1507b_3
  openssl            conda-forge/osx-arm64::openssl-3.1.3-h53f4e23_0
  packaging          conda-forge/noarch::packaging-23.2-pyhd8ed1ab_0
  pillow             conda-forge/osx-arm64::pillow-10.0.1-py312hb653a51_2
  pip                conda-forge/noarch::pip-23.2.1-pyhd8ed1ab_0
  pthread-stubs      conda-forge/osx-arm64::pthread-stubs-0.4-h27ca646_1001
  pygments           conda-forge/noarch::pygments-2.16.1-pyhd8ed1ab_0
  pyparsing          conda-forge/noarch::pyparsing-3.1.1-pyhd8ed1ab_0
  pysocks            conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6
  python             conda-forge/osx-arm64::python-3.12.0-h47c9636_0_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python_abi         conda-forge/osx-arm64::python_abi-3.12-4_cp312
  pyyaml             conda-forge/osx-arm64::pyyaml-6.0.1-py312h02f2b3b_1
  readline           conda-forge/osx-arm64::readline-8.2-h92ec313_1
  requests           conda-forge/noarch::requests-2.31.0-pyhd8ed1ab_0
  rich               conda-forge/noarch::rich-13.6.0-pyhd8ed1ab_0
  rich-click         conda-forge/noarch::rich-click-1.7.0-pyhd8ed1ab_0
  setuptools         conda-forge/noarch::setuptools-68.2.2-pyhd8ed1ab_0
  simplejson         conda-forge/osx-arm64::simplejson-3.19.2-py312he37b823_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  spectra            conda-forge/noarch::spectra-0.0.11-py_1
  tk                 conda-forge/osx-arm64::tk-8.6.13-hb31c410_0
  typing_extensions  conda-forge/noarch::typing_extensions-4.8.0-pyha770c72_0
  tzdata             conda-forge/noarch::tzdata-2023c-h71feb2d_0
  urllib3            conda-forge/noarch::urllib3-2.0.6-pyhd8ed1ab_0
  wheel              conda-forge/noarch::wheel-0.41.2-pyhd8ed1ab_0
  xorg-libxau        conda-forge/osx-arm64::xorg-libxau-1.0.11-hb547adb_0
  xorg-libxdmcp      conda-forge/osx-arm64::xorg-libxdmcp-1.1.3-h27ca646_0
  xz                 conda-forge/osx-arm64::xz-5.2.6-h57fd34a_0
  yaml               conda-forge/osx-arm64::yaml-0.2.5-h3422bc3_2
  zipp               conda-forge/noarch::zipp-3.17.0-pyhd8ed1ab_0
  zstd               conda-forge/osx-arm64::zstd-1.5.5-h4f39d0f_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
```

</details>

```console
❯ conda activate py3.12

❯ multiqc --help
Traceback (most recent call last):
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.12/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import run_multiqc
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.12/lib/python3.12/site-packages/multiqc/__init__.py", line 16, in <module>
    from .multiqc import run
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.12/lib/python3.12/site-packages/multiqc/multiqc.py", line 30, in <module>
    from .plots import table
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.12/lib/python3.12/site-packages/multiqc/plots/table.py", line 9, in <module>
    from multiqc.plots import beeswarm, table_object
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.12/lib/python3.12/site-packages/multiqc/plots/beeswarm.py", line 9, in <module>
    from multiqc.plots import table_object
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.12/lib/python3.12/site-packages/multiqc/plots/table_object.py", line 9, in <module>
    from multiqc.utils import config, report
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.12/lib/python3.12/site-packages/multiqc/utils/report.py", line 18, in <module>
    import lzstring
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.12/lib/python3.12/site-packages/lzstring/__init__.py", line 11, in <module>
    from future import standard_library
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.12/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
```

**Comment by ewels** [comment]
Quick look - I think it's the `lzstring` package, which has not had a lot of activity in quite a while.

Conda feedstock is [here](https://github.com/conda-forge/lzstring-feedstock) and source code is [here](https://github.com/gkovacs/lz-string-python).

I imagine that it's due to [this line](https://github.com/gkovacs/lz-string-python/blob/f1c109544413c1ba910c4af99337c14da1680441/lzstring/__init__.py#L7) and that removing it will fix the issue:

```python
from __future__ import absolute_import
```

**Comment by ewels** [comment]
Looks good - the fix to the main upstream package is my preferred approach, as patching conda won't fix it for anyone installing from PyPI / local clones.

We should really have the CI running with the pre-release versions of Python to catch this stuff before the stable releases hit.

**Comment by mfansler** [comment]
Just want to check what (if any) patching we should do with Bioconda/Conda Forge metadata. If this package itself has incompatibilities with Python 3.12, then we should patch the Bioconda repodata to have `python <3.12` to all the previous releases.

If it is only a dependency (e.g., `future`), we can leave the metadata on Bioconda alone and patch the relevant Conda Forge package.

Could you clarify this?

**Comment by ewels** [comment]
Hi @mfansler,

It's both:

- A problem in the dependency `lzstring` (see PRs to fix the [upstream tool](https://github.com/gkovacs/lz-string-python/pull/6) and [patch conda-forge](https://github.com/conda-forge/lzstring-feedstock/pull/7) - help welcome on the latter especially)
- A problem in MultiQC itself (see PR to [fix it](https://github.com/ewels/MultiQC/pull/2113/), aiming for a release on Monday if all goes to plan).

I'm happy for the bioconda metadata to be updated to python <3.12 for this release, but I'm also hoping that we can have fixed releases out on Monday that are python 3.12 compatible.

Phil

**Comment by vladsavelyev** [comment]
@muripabi, the fix should be merged soon :)

**Comment by fgvieira** [comment]
Will you release a minor version with this patch or will you wait for `1.17`?

**Comment by vladsavelyev** [comment]
@fgvieira, it is released now :)
https://github.com/ewels/MultiQC/releases/tag/v1.17

**Comment by aditimahabole** [comment]
hello everyone i am having problem while installing tensor flow 
first i wrote pip install tensorflow and it gave me this error:
<img width="546" alt="image" src="https://github.com/ewels/MultiQC/assets/78752342/bbb4a6b2-33cf-434b-838f-c8877ea66eec">
then i searched on google and i found out this link:
https://stackoverflow.com/questions/42317075/tensorflow-r1-0-could-not-a-find-a-version-that-satisfies-the-requirement-tens
and i pasted the command given in this :
pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.0.0-py3-none-any.whl
the output i got was succesfully installed
<img width="739" alt="image" src="https://github.com/ewels/MultiQC/assets/78752342/d2a57eff-1ebb-4e17-a09d-e1410da022a3">

so then i ran command python manage.py migrate 
to start django 
so i got this error
<img width="735" alt="image" src="https://github.com/ewels/MultiQC/assets/78752342/39df2757-8ae6-485b-bd0c-8eb09453a6ec">

<img width="749" alt="image" src="https://github.com/ewels/MultiQC/assets/78752342/010130d7-519a-4f54-a850-62d641078e7e">

<img width="746" alt="image" src="https://github.com/ewels/MultiQC/assets/78752342/24915f2e-d552-48e8-b21e-278f395d88e1">

the error was **no module named imp**
so i tried to do pip install imp 
and then i got this error:
<img width="592" alt="image" src="https://github.com/ewels/MultiQC/assets/78752342/31f855c1-10a7-4ed0-b563-83bba15e382f">

PLEASE SOMEBODY HELP ME OUT I DONT KNOW WHAT TO DO.
