### ISSUE TITLE
Error when running with `--no-report`

### ISSUE THREAD

**Issue by lacek** [ewels/MultiQC#2198]
### Description of bug

Example command that triggers the error:

```bash
multiqc --no-report stats
```

When `--no-report` is given, `config.output_fn` is None (https://github.com/ewels/MultiQC/blob/v1.18/multiqc/multiqc.py#L676) and therefore the debug statement (https://github.com/ewels/MultiQC/blob/v1.18/multiqc/multiqc.py#L1064) will throw error.

### File that triggers the error

Just arbitrary valid input, e.g. a bcftools stats output txt.

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.18

|           multiqc | Search path : /runtime/stats
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1
|          bcftools | Found 1 stats reports
|           multiqc | Report      : None
|           multiqc | Data        : multiqc_data
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 8, in <module>
    sys.exit(run_multiqc())
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multiqc/__main__.py", line 23, in run_multiqc
    multiqc.run_cli(prog_name="multiqc")
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 300, in run_cli
    multiqc_run = run(**kwargs)
                  ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/multiqc/multiqc.py", line 1064, in run
    logger.debug("Full report path: {}".format(os.path.realpath(config.output_fn)))
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 415, in realpath
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment]
Thank you so much @lacek for creating the bug report, and sorry about this problem! 

It should be fixed with https://github.com/ewels/MultiQC/pull/2212
