### ISSUE TITLE
Problem in running MultiQC

### ISSUE THREAD

**Issue by vd4mmind** [ewels/MultiQC#226]
I had successfully installed MultiQC but had problem with running , even the running of version or help runs with error, it seems a problem with the python lib distribution but am unable to understand it. Any help to resolve this issue?
Error
```
multiqc --version
```
```python
Traceback (most recent call last):
  File "/home/vdas/MyVE/bin/multiqc", line 4, in <module>
    __import__('pkg_resources').run_script('multiqc==0.7.dev0', 'multiqc')
  File "/home/vdas/MyVE/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/vdas/MyVE/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/home/vdas/MyVE/lib/python2.7/site-packages/multiqc-0.7.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 33, in <module>
    from multiqc import logger, __version__
  File "/home/vdas/MyVE/local/lib/python2.7/site-packages/multiqc-0.7.dev0-py2.7.egg/multiqc/__init__.py", line 11, in <module>
    from multiqc.modules.base_module import BaseMultiqcModule
  File "/home/vdas/MyVE/local/lib/python2.7/site-packages/multiqc-0.7.dev0-py2.7.egg/multiqc/modules/base_module.py", line 12, in <module>
    from multiqc import plots
  File "/home/vdas/MyVE/local/lib/python2.7/site-packages/multiqc-0.7.dev0-py2.7.egg/multiqc/plots/__init__.py", line 1, in <module>
    from . import bargraph, beeswarm, heatmap, linegraph, table
  File "/home/vdas/MyVE/local/lib/python2.7/site-packages/multiqc-0.7.dev0-py2.7.egg/multiqc/plots/bargraph.py", line 17, in <module>
    import matplotlib.pyplot as plt
  File "/home/vdas/MyVE/lib/python2.7/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar
  File "/home/vdas/MyVE/lib/python2.7/site-packages/matplotlib/colorbar.py", line 36, in <module>
    import matplotlib.contour as contour
  File "/home/vdas/MyVE/lib/python2.7/site-packages/matplotlib/contour.py", line 16, in <module>
    import matplotlib._contour as _contour
ImportError: /scratch/GT/softwares/SalmonBeta-0.6.1_DebianSqueeze/lib/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/vdas/MyVE/lib/python2.7/site-packages/matplotlib/_contour.so)
```

Below is my .bashrc setup, can you tell me where am getting it wrong?

```bash
export PATH=$PATH:/scratch/GT/softwares/bin
alias R3="/home/vdas/R-3.1.2/bin/R"
export LD_LIBRARY_PATH=/scratch/GT/softwares/Sailfish-0.6.3-Linux_x86-64/lib:$LD_LIBRARY_PATH
export PATH=/scratch/GT/softwares/Sailfish-0.6.3-Linux_x86-64/bin:$PATH
export PATH=$PATH:/scratch/GT/softwares/RNASeqReadSimulator-master/src
export PYTHONPATH=$HOME/MyVE/lib/python2.7/site-packages:/scratch/GT/softwares/hdf5/lib:$PYTHONPATH
export PATH=$HOME/bin:$PATH
#export PYTHONPATH=/scratch/GT/softwares/MACS.2.1.0/MACS2:$PYTHONPATH
#export PATH=/scratch/GT/softwares/MACS.2.1.0/bin:$PATH
export PATH=/scratch/GT/softwares/kallisto-0.42.3/build/src:$PATH
#export PATH=/home/vdas/tools/deepTools2/bin:$PATH
export LD_LIBRARY_PATH=/scratch/GT/softwares/hdf5/lib:$LD_LIBRARY_PATH
export PATH=/home/vdas/MyVE/bin:$PATH
#export PATH=$PATH:/scratch/GT/softwares/deepTools/bin/
export LD_LIBRARY_PATH=/scratch/GT/softwares/SalmonBeta-0.6.1_DebianSqueeze/lib:$LD_LIBRARY_PATH
export PATH=/scratch/GT/softwares/SalmonBeta-0.6.1_DebianSqueeze/bin:$PATH
export PATH=/scratch/GT/softwares/ngsplot/bin:$PATH
export NGSPLOT=/scratch/GT/softwares/ngsplot
export PATH=/home/vdas/tools/jdk1.8.0_77/bin:$PATH
export LD_LIBRARY_PATH=/home/vdas/tools/jdk1.8.0_77/lib:$LD_LIBRARY_PATH
export PATH=/home/vdas/tools/ldc2-0.17.1-linux-x86_64/bin:$PATH
export LIBRARY_PATH=/home/vdas/tools/ldc2-0.17.1-linux-x86_64/lib:$LD_LIBRARY_PATH
export PATH=/home/vdas/tools/htslib-1.3.1/install/bin:$PATH
export PATH=/home/vdas/tools/bcftools-1.3.1/install/bin:$PATH
export PATH=/home/vdas/tools/samtools-1.3.1/install/bin:$PATH
export PATH=/home/vdas/tools/sambamba/build:$PATH
#export PATH=/home/vdas/MyVE/lib/python2.7/site-packages/editdistance:$PATH
#export PATH=$PATH:/home/vdas/MyVE/lib/python2.7/site-packages/AfterQC
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
My Python distribution is under MyVE, tools like Salmon and all are working but any tool like yours which uses the matplotlib any python are failing like the error posted. Any help?

**Comment by ewels** [comment]
Hi @vd4mmind,

As you suggest - this is an error with MatPlotLib rather than MultiQC (which is just trying to import it). MatPlotLib is great when it works, but it can sometimes cause a lot of headaches. I'm thinking of trying to handle these in a better way - I've just made an issue for it: #228.

A bit of googling suggests that this error comes from some kind of GCC error, another step down the dependency tree. [This post](http://stackoverflow.com/questions/21832808/using-both-matplotlib-and-rpy2-with-multi-buildpacks-on-heroku) gives a potential solution - basically adding the following line to your `.bashrc` file:

```bash
export LD_LIBRARY_PATH=/usr/lib:/usr/local/lib:$LD_LIBRARY_PATH
```

Otherwise, I would probably try [reinstalling MatPlotLib directly](http://matplotlib.org/users/installing.html). Googling the error `libstdc++.so.6: version `GLIBCXX_3.4.15' not found` also gives a lot of posts about this, hopefully you don't have to go too far down the rabbit hole..

Phil

**Comment by ewels** [comment]
Hi @vd4mmind,

Did you get this to work in the end? I've just implemented some error handling to try to contain problems with MatPlotLib. If you grab v0.7dev then it should now work, though with an ugly warning at the top of the log output. Hope this helps!

Phil

**Comment by padafa** [comment]
I had a problem... help?

$ multiqc .
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 4, in <module>
    __import__('pkg_resources').run_script('multiqc==1.7.dev0', 'multiqc')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'matplotlib<3.0.0,>=2.1.1' distribution was not found and is required by multiqc

**Comment by ewels** [comment]
Hi @padafa,

Please create a new issue for questions like this. This is over two years old and was resolved. I have moved your question to #865.

Phil
