### ISSUE TITLE
The 'bismark' MultiQC module broke... 

### ISSUE THREAD

**Issue by serine** [ewels/MultiQC#246]
## bug..? 

```
(multiqc)[bioinformatics-platform]:pathNotShown/secondRun-EndToEnd% multiqc --config multiqc_config_example.yaml . --force
[INFO   ]         multiqc : This is MultiQC v0.7dev
[INFO   ]          config : Loading config settings from: multiqc_config_example.yaml
[INFO   ]         multiqc : Searching '.'
[INFO   ]  feature_counts : Found 14 reports
[ERROR  ]         multiqc : Oops! The 'bismark' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module bismark raised an exception: Traceback (most recent call last):
  File "/mnt/ceph/mbp/servers/bioinformatics-platform/home/kirill/.virtualenvs/multiqc/lib/python2.7/site-packages/multiqc-0.7dev-py2.7.egg/EGG-INFO/scripts/multiqc", line 296, in multiqc
    report.modules_output.append(mod())
  File "/home/kirill/.virtualenvs/multiqc/local/lib/python2.7/site-packages/multiqc-0.7dev-py2.7.egg/multiqc/modules/bismark/bismark.py", line 83, in __init__
    for f in self.find_log_files(sp['align']):
KeyError: 'align'
============================================================
[INFO   ]            star : Found 14 reports
[INFO   ]          fastqc : Found 112 reports
[WARNING]         multiqc : Deleting    : multiqc_report.html   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc_report.html
[WARNING]         multiqc : Deleting    : multiqc_data   (-f was specified)
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete

```

in the `multiqc_config.yaml` only changed these lines

```
# Title to use for the report.
title: "This is test title name"
fn_ignore_dirs:
    - RNAsik-pipe.*
    - preqcBamFiles
    - RNAseQC-report
    - refFiles
    - rMatsContainer

max_table_rows: 113              # Swap tables for a beeswarm plot above this
```

**Comment by ewels** [comment]
What's in `multiqc_config_example.yaml`? Are you sure you're specifying the correct config file?

**Comment by ewels** [comment]
I've just updated the example config file so that if people accidentally use it or any of it's contents it should only reset things to their defaults anyway (and not break anything). See fb13139110762d5865ddb44588339327ec738d08.

**Comment by ewels** [comment]
Closing this until I can replicate it. Feel free to reopen!
