### ISSUE TITLE
Issue with running multiqc in STAR output directory

### ISSUE THREAD

**Issue by royfrancis** [ewels/MultiQC#310]
I noticed that when running `multiqc .` in a directory with fastq files and all STAR output, multiqc doesn't seem to work. The multiqc run starts normally and then hangs. I cancelled it manually after 10 mins or so (Code and error below). But if I copy the STAR Log.final.out files into a new directory and run multiqc, it works instantly.

```
[bla@bla]$ multiqc .
[INFO   ]         multiqc : This is MultiQC v0.8.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'

^X^C[CRITICAL]         multiqc : User Cancelled Execution!
============================================================
Traceback (most recent call last):
  File "/home/royfranc/.pyenv/versions/2.7.6/bin/multiqc", line 303, in multiqc
    report.modules_output.append(mod())
  File "/home/royfranc/.pyenv/versions/2.7.6/lib/python2.7/site-packages/multiqc/modules/picard/picard.py", line 51, in __init__
    n['BaseDistributionByCycleMetrics'] = BaseDistributionByCycleMetrics.parse_reports(self)
  File "/home/royfranc/.pyenv/versions/2.7.6/lib/python2.7/site-packages/multiqc/modules/picard/BaseDistributionByCycleMetrics.py", line 98, in parse_reports
    for f in base_dist_files:
  File "/home/royfranc/.pyenv/versions/2.7.6/lib/python2.7/site-packages/multiqc/modules/base_module.py", line 86, in find_log_files
    for m in contents_match:
KeyboardInterrupt
============================================================
User Cancelled Execution!
```

**Comment by ewels** [comment]
Hi @royfrancis,

This is interesting. Is it _only_ STAR output and FastQ files in your directory? Note that STAR is one of the fastest modules - the FastQC module for example is a lot slower per report. Is it always the same Traceback that you get when you cancel execution (stopped on the same lines of code)? Finally - what does the output look like when you run MultiQC in verbose mode with `-v`/`--verbose`? Could you paste that log please?

Cheers,

Phil

**Comment by royfrancis** [comment]
Yes. I only have STAR output files and fastq files (actually soft links to fastq files). Now I think this is just me being impatient. I have 384 files in the directory (just the final log files alone). If all the STAR output and fastq files are present, the number of files would be around 4600 files. I think it just takes time.

The output from verbose looks like below:

```
...
[2016-09-29 22:47:35,813] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.spliceJunctionAndExonCounts.forJunctionSeq.txt
[2016-09-29 22:47:35,813] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.spliceJunctionCounts.knownSplices.txt
[2016-09-29 22:47:35,902] multiqc                                            [DEBUG  ]  Ignoring file as too large: exonGeTrInfo.tab
[2016-09-29 22:47:35,902] multiqc                                            [DEBUG  ]  Ignoring file as too large: exonInfo.tab
[2016-09-29 22:47:35,902] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbInfo.txt
[2016-09-29 22:47:35,903] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbList.fromGTF.out.tab
[2016-09-29 22:47:35,903] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbList.out.tab
[2016-09-29 22:47:36,372] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.exonCounts.formatted.for.DEXSeq.txt
[2016-09-29 22:47:36,372] multiqc                                            [DEBUG  ]  Ignoring file as matched an ignore pattern: QC.geneBodyCoverage.DEBUG.intervals.txt.gz
[2016-09-29 22:47:36,373] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.spliceJunctionAndExonCounts.forJunctionSeq.txt
[2016-09-29 22:47:36,373] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.spliceJunctionCounts.knownSplices.txt
[2016-09-29 22:47:36,537] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.exonCounts.formatted.for.DEXSeq.txt
[2016-09-29 22:47:36,537] multiqc                                            [DEBUG  ]  Ignoring file as matched an ignore pattern: QC.geneBodyCoverage.DEBUG.intervals.txt.gz
[2016-09-29 22:47:36,538] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.spliceJunctionAndExonCounts.forJunctionSeq.txt
[2016-09-29 22:47:36,538] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.spliceJunctionCounts.knownSplices.txt
[2016-09-29 22:47:37,543] multiqc                                            [DEBUG  ]  Ignoring file as too large: exonGeTrInfo.tab
[2016-09-29 22:47:37,543] multiqc                                            [DEBUG  ]  Ignoring file as too large: exonInfo.tab
[2016-09-29 22:47:37,544] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbInfo.txt
[2016-09-29 22:47:37,544] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbList.fromGTF.out.tab
[2016-09-29 22:47:37,544] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbList.out.tab
[2016-09-29 22:47:37,646] multiqc                                            [DEBUG  ]  Ignoring file as too large: exonGeTrInfo.tab
[2016-09-29 22:47:37,646] multiqc                                            [DEBUG  ]  Ignoring file as too large: exonInfo.tab
[2016-09-29 22:47:37,646] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbInfo.txt
[2016-09-29 22:47:37,646] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbList.fromGTF.out.tab
[2016-09-29 22:47:37,646] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbList.out.tab
[2016-09-29 22:47:39,390] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.exonCounts.formatted.for.DEXSeq.txt
[2016-09-29 22:47:39,390] multiqc                                            [DEBUG  ]  Ignoring file as matched an ignore pattern: QC.geneBodyCoverage.DEBUG.intervals.txt.gz
[2016-09-29 22:47:39,391] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.spliceJunctionAndExonCounts.forJunctionSeq.txt
[2016-09-29 22:47:39,391] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.spliceJunctionCounts.knownSplices.txt
[2016-09-29 22:47:39,442] multiqc                                            [DEBUG  ]  Ignoring file as too large: exonGeTrInfo.tab
[2016-09-29 22:47:39,443] multiqc                                            [DEBUG  ]  Ignoring file as too large: exonInfo.tab
[2016-09-29 22:47:39,443] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbInfo.txt
[2016-09-29 22:47:39,443] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbList.fromGTF.out.tab
[2016-09-29 22:47:39,443] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbList.out.tab
[2016-09-29 22:47:40,138] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.exonCounts.formatted.for.DEXSeq.txt
[2016-09-29 22:47:40,138] multiqc                                            [DEBUG  ]  Ignoring file as matched an ignore pattern: QC.geneBodyCoverage.DEBUG.intervals.txt.gz
[2016-09-29 22:47:40,139] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.spliceJunctionAndExonCounts.forJunctionSeq.txt
[2016-09-29 22:47:40,139] multiqc                                            [DEBUG  ]  Ignoring file as too large: QC.spliceJunctionCounts.knownSplices.txt
[2016-09-29 22:47:40,443] multiqc                                            [DEBUG  ]  Ignoring file as too large: exonGeTrInfo.tab
[2016-09-29 22:47:40,443] multiqc                                            [DEBUG  ]  Ignoring file as too large: exonInfo.tab
[2016-09-29 22:47:40,444] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbInfo.txt
[2016-09-29 22:47:40,444] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbList.fromGTF.out.tab
[2016-09-29 22:47:40,444] multiqc                                            [DEBUG  ]  Ignoring file as too large: sjdbList.out.tab
^C
Aborted!
```

**Comment by ewels** [comment]
Ok, then yes it will take a little time to look through all of those files. You can probably speed it up significantly by using the `-m`/`--module` flag and specifying `star`:

```
multiqc -m star .
```

This will ignore all other MultiQC modules.
