### ISSUE TITLE
--ignore -x TEXT option is not working properly for fastqc and star modules

### ISSUE THREAD

**Issue by trigremm** [ewels/MultiQC#316]
Hello, while I was trying to aggregate all reports i have for RNA-seq analysis  I met an error in running star module.
the reason is that star module doest receive a list of ignored text
I also mentioned that FastQC module also ignores `--ignore TEXT` option 

upd: problem is solved by manually moving broken sample records into separate folder outside from the MultiQC search path 

```
[2016-10-13 11:24:48,664] multiqc                                            [ERROR  ]  Oops! The 'star' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
```

``` python
============================================================
Module star raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 345, in multiqc
    report.modules_output.append(mod())
  File "/usr/local/lib/python3.4/site-packages/multiqc/modules/star/star.py", line 27, in __init__
    parsed_data = self.parse_star_report(f['f'])
  File "/usr/local/lib/python3.4/site-packages/multiqc/modules/star/star.py", line 88, in parse_star_report
    parsed_data['unmapped_mismatches'] = int(round(unmapped_count * (parsed_data['unmapped_mismatches_percent'] / total_unmapped_percent), 0))
ZeroDivisionError: float division by zero
============================================================
```

```
# grep 18N_160423 err.txt 
[2016-10-13 11:23:06,320] multiqc                                            [DEBUG  ]  Command used: /usr/local/bin/multiqc -f -o . -n multiqc_report_ip_x.html -p -ip -v fastqc_report/ qualimap_report/ aligned_RNA_with_STAR_on_ensembl_GRCh37_75/ aligned_sam_incomplete/ --ignore 18N_160423 --ignore 18T_160423 
[2016-10-13 11:23:06,601] multiqc                                            [DEBUG  ]  Command     : /usr/local/bin/multiqc -f -o . -n multiqc_report_ip_x.html -p -ip -v fastqc_report/ qualimap_report/ aligned_RNA_with_STAR_on_ensembl_GRCh37_75/ aligned_sam_incomplete/ --ignore 18N_160423 --ignore 18T_160423 
[2016-10-13 11:23:06,601] multiqc                                            [DEBUG  ]  Ignoring files, directories and paths that match: 18N_160423, 18T_160423
[2016-10-13 11:23:08,538] multiqc                                            [DEBUG  ]  Ignoring file as matched an ignore pattern: 18N_160423Aligned.out.sam
[2016-10-13 11:23:08,538] multiqc                                            [DEBUG  ]  Ignoring file as matched an ignore pattern: 18N_160423Aligned.toTranscriptome.out.bam
[2016-10-13 11:23:08,538] multiqc                                            [DEBUG  ]  Ignoring file as too large: 18N_160423Log.out
[2016-10-13 11:23:08,550] multiqc                                            [DEBUG  ]  Ignoring file as matched an ignore pattern: 18N_160423Aligned.out.bam
[2016-10-13 11:23:08,553] multiqc                                            [DEBUG  ]  Ignoring file as matched an ignore pattern: 18N_160423Aligned.out.sorted.bam
[2016-10-13 11:25:13,790] multiqc.modules.fastqc.fastqc                      [WARNING]  Couldn't read '18N_160423.R2_fastqc.zip' - Bad zip file
[2016-10-13 11:25:14,449] multiqc.modules.fastqc.fastqc                      [WARNING]  Couldn't read '18N_160423.R1_fastqc.zip' - Bad zip file

```

**Comment by trigremm** [comment]
# multiqc --version 
multiqc, version 0.9.dev0

**Comment by ewels** [comment]
Thanks for this @trigremm, I'll look into the `ZeroDivisionError` - should be an easy catch (impressive data if you have no unaligned reads!).

Not sure why FastQC isn't ignoring your files, I'll see if I can replicate the error.

Phil

**Comment by ewels** [comment]
Hi @trigremm,

Sorry for the delay in looking at this. As you can see above, the STAR error should be fixed now. Are you still having problems with ignoring files? It seems to be working fine for me:

```
$ ls
SRR1067503_1_trimmedLog.final.out  SRR1067505_1_trimmedLog.final.out

$  multiqc -f .
[INFO   ]         multiqc : This is MultiQC v0.9.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]            star : Found 2 reports
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete

$ multiqc -f . -x *503*
[INFO   ]         multiqc : This is MultiQC v0.9.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]            star : Found 1 reports
[WARNING]         multiqc : Deleting    : multiqc_report.html   (-f was specified)
[INFO   ]         multiqc : Report      : multiqc_report.html
[WARNING]         multiqc : Deleting    : multiqc_data   (-f was specified)
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

Note that the pattern has to be a glob expression. Looking at your command above, it looks like you've specified `18N_160423`, so MultiQC will only ignore things called exactly that (eg. not `18N_160423.R2_fastqc.zip`). Running with `--ignore 18N_160423*` should work.

Phil

**Comment by ewels** [comment]
I'll close this for now as I can't replicate the `--ignore` error. Let me know if you still have problems though and I'll reopen.

Phil
