### ISSUE TITLE
Module gatk raised an exception

### ISSUE THREAD

**Issue by parlundin** [ewels/MultiQC#317]
```
[ERROR  ]         multiqc : Oops! The 'gatk' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
```

``` python
============================================================
Module gatk raised an exception: Traceback (most recent call last):
  File "/lupus/ngi/production/v1.3/sw/anaconda/envs/NGI/bin/multiqc", line 345, in multiqc
    report.modules_output.append(mod())
  File "/lupus/ngi/production/v1.3/sw/anaconda/envs/NGI/lib/python2.7/site-packages/multiqc/modules/gatk/gatk.py", line 39, in __init__
    n['varianteval'] = self.parse_gatk_varianteval()
  File "/lupus/ngi/production/v1.3/sw/anaconda/envs/NGI/lib/python2.7/site-packages/multiqc/modules/gatk/varianteval.py", line 24, in parse_gatk_varianteval
    log.debug("Duplicate sample name found! Overwriting: {}".format(f['s_name']))
NameError: global name 'log' is not defined
============================================================
```

**Comment by ewels** [comment]
Presumably due to [this commented out line](https://github.com/ewels/MultiQC/blob/master/multiqc/modules/gatk/varianteval.py#L12). Needs testing to make sure that it isn't commented out for a reason!
