### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by vj8uconn** [ewels/MultiQC#356]
## I was installing MultiQC to give it a try, and encountered following error. Any help will be appreciated.
Command used to install:  pip install multiqc
platform: Dell Linux cluster running Centos 6.3

Is the problem related to python version? I have python 2.7.3

Here is the brief error  and below that is the complete pip.log file
```
Downloading/unpacking multiqc
  Downloading multiqc-0.8.tar.gz (883kB): 883kB downloaded
  Running setup.py (path:/tmp/pip_build_root/multiqc/setup.py) egg_info for package multiqc
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/multiqc/setup.py", line 27, in <module>
        dl_version = 'master' if 'dev' in version else 'v{}'.format(version)
    ValueError: zero length field name in format
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/multiqc/setup.py", line 27, in <module>

    dl_version = 'master' if 'dev' in version else 'v{}'.format(version)

ValueError: zero length field name in format

----------------------------------------
Cleaning up...
_________________________________________________
pip log file
------------------------------------------------------------
/usr/bin/pip run on Tue Dec  6 12:20:39 2016
Downloading/unpacking multiqc
  Getting page https://pypi.python.org/simple/multiqc/
  URLs to search for versions for multiqc:
  * https://pypi.python.org/simple/multiqc/
  Analyzing links from page https://pypi.python.org/simple/multiqc/
    Found link https://pypi.python.org/packages/08/1c/d9833670aee1303332713f456140730a7a8335cc97bc7aa3c67f37a3b0e1/multiqc-0.5.tar.gz#md5=490385c105ffa16463b7621a5e28fb62 (from https://pypi.python.org/simple/multiqc/), version: 0.5
    Found link https://pypi.python.org/packages/1c/e0/1e14407025dd461f1917354af543dcd912b669729ce77e0e0d29879d146e/multiqc-0.4.tar.gz#md5=65c15862194529134888a00ebc0ebb11 (from https://pypi.python.org/simple/multiqc/), version: 0.4
    Found link https://pypi.python.org/packages/23/d9/95a5e62eea95f220007d7a6683d0da1ee1d9f99e6932bcff793b6601ef15/multiqc-0.6.tar.gz#md5=a22fd5d29fcf69e624831d4803bcb556 (from https://pypi.python.org/simple/multiqc/), version: 0.6
    Found link https://pypi.python.org/packages/44/ae/59e74780d4c66afbbac9053d2b6b0f12aaef94e4ce92cb00b71a20025098/multiqc-0.1.tar.gz#md5=c97c5b8c6d4446c05c367d3c47861ad7 (from https://pypi.python.org/simple/multiqc/), version: 0.1
    Found link https://pypi.python.org/packages/47/bb/3339d0a27891c241de1bcc76122e779b67efad072140224a02e8700e5199/multiqc-0.3.1.tar.gz#md5=0cbb35c67db2c67a4c39c73c80b42a23 (from https://pypi.python.org/simple/multiqc/), version: 0.3.1
    Found link https://pypi.python.org/packages/5d/cd/08627e78e84acc038dcab2ee6403af9eca73b1203fe505645a2c33c316b0/multiqc-0.3.0.tar.gz#md5=0046dc32d43f9bbef4c799e0718cacfb (from https://pypi.python.org/simple/multiqc/), version: 0.3.0
    Found link https://pypi.python.org/packages/6b/b7/839b0c84448856bd3b2e8c381c4778c4b9c22ded890881d1cd12f9e686fa/multiqc-0.7.tar.gz#md5=69874704db5ec1a22bd74065a4c1a6dd (from https://pypi.python.org/simple/multiqc/), version: 0.7
    Found link https://pypi.python.org/packages/ab/e4/9a9eea1facbc3dcb7c90e38d3719eea43d4877aa54a887726982f1ba1671/multiqc-0.8.tar.gz#md5=a7740e00a2a0deb57a72fbdd209475fa (from https://pypi.python.org/simple/multiqc/), version: 0.8
    Found link https://pypi.python.org/packages/e5/56/76229fca10700a78fe4a51baf2de7385509a48c7d281f42d9d311a547d76/multiqc-0.3.2.tar.gz#md5=7b765e11832199e59da2be1ef5b6558a (from https://pypi.python.org/simple/multiqc/), version: 0.3.2
    Found link https://pypi.python.org/packages/e9/7c/14ca085189df0aaba25054bf42fe3ceb74bcbee5c271d4c6f9c9c39bf1c0/multiqc-0.2.0.tar.gz#md5=081479604dd7222eb34a5ff9adde7fe1 (from https://pypi.python.org/simple/multiqc/), version: 0.2.0
  Using version 0.8 (newest of versions: 0.8, 0.7, 0.6, 0.5, 0.4, 0.3.2, 0.3.1, 0.3.0, 0.2.0, 0.1)
  Downloading from URL https://pypi.python.org/packages/ab/e4/9a9eea1facbc3dcb7c90e38d3719eea43d4877aa54a887726982f1ba1671/multiqc-0.8.tar.gz#md5=a7740e00a2a0deb57a72fbdd209475fa (from https://pypi.python.org/simple/multiqc/)
  Running setup.py (path:/tmp/pip_build_root/multiqc/setup.py) egg_info for package multiqc
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/multiqc/setup.py", line 27, in <module>
        dl_version = 'master' if 'dev' in version else 'v{}'.format(version)
    ValueError: zero length field name in format
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/multiqc/setup.py", line 27, in <module>

    dl_version = 'master' if 'dev' in version else 'v{}'.format(version)

ValueError: zero length field name in format

----------------------------------------
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/multiqc
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pip-1.5.2-py2.6.egg/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.6/site-packages/pip-1.5.2-py2.6.egg/pip/commands/install.py", line 274, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.6/site-packages/pip-1.5.2-py2.6.egg/pip/req.py", line 1215, in prepare_files
    req_to_install.run_egg_info()
  File "/usr/lib/python2.6/site-packages/pip-1.5.2-py2.6.egg/pip/req.py", line 321, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python2.6/site-packages/pip-1.5.2-py2.6.egg/pip/util.py", line 697, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/multiqc
```

## If you're requesting a new module
Checklist of requirements:
- [ ] Description of tool, link to homepage
- [ ] Log files - please submit as a PR to https://github.com/ewels/MultiQC_TestData
- [ ] Any standard log file naming patterns to get sample name (eg. `sample_name.processed.log`)
- [ ] Say which value is most important, to go into the General Stats table
- [ ] Specify what should be plotted, if anything

Thanks!

**Comment by ewels** [comment]
Hi @vj8uconn - I see you closed this already, did you solve the problem?

Phil
