### ISSUE TITLE
example tsv file with embedded config for custom_data

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#369]
Hi,

I am testing custom_data and found my way through all the examples. Very useful and will make good use of it from now on.

I was wondering what's the expected format for a scatter plot with embedded config where each file contains the data for one sample. The two files below give me the following error with head master code:

```
multiqc -f . 
/home/avilella/.local/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
[INFO   ]         multiqc : This is MultiQC v0.9.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[ERROR  ]         multiqc : Oops! The 'custom_content' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module custom_content raised an exception: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/multiqc-0.9.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 344, in multiqc
    output = mod()
  File "/usr/local/lib/python2.7/dist-packages/multiqc-0.9.dev0-py2.7.egg/multiqc/modules/custom_content/custom_content.py", line 172, in custom_module_classes
    parsed_modules.append( MultiqcModule(k, mod) )
  File "/usr/local/lib/python2.7/dist-packages/multiqc-0.9.dev0-py2.7.egg/multiqc/modules/custom_content/custom_content.py", line 211, in __init__
    self.intro += plots.scatter.plot(mod['data'], pconfig)
  File "/usr/local/lib/python2.7/dist-packages/multiqc-0.9.dev0-py2.7.egg/multiqc/plots/scatter.py", line 34, in plot
    this_series = { 'x': k['x'], 'y': k['y'] }
KeyError: 'x'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

The files are:

```
==> sample1_foo_scatter_mqc.tsv <==
# id: 'custom_data_scatter'
# description: 'foo'
# section_name: 'Custom Data File'
# plot_type: 'scatter'
# pconfig:
#     id: 'custom_data_scatter_plot'
#     title: 'Output from my script'
#     ylab: 'Number of things'
valueX  valueY
1       10
2       18
3       26
4       34
5       42
6       50

==> sample2_foo_scatter_mqc.tsv <==
# id: 'custom_data_scatter'
# description: 'foo'
# section_name: 'Custom Data File'
# plot_type: 'scatter'
# pconfig:
#     id: 'custom_data_scatter_plot'
#     title: 'Output from my script'
#     ylab: 'Number of things'
valueX  valueY
1.1     10.5
2       18.5
3.3     26.5
3.9     34.5
5       41.5
6       50.5
```

**Comment by ewels** [comment]
Hi @avilella,

There currently is no expected format for _'one file per sample'_ for scatter plots, mostly because I'm scared of people using the scatter plot type to plot huge amounts of data. I grudgingly introduced scatter plots for stuff like PCA plots where there is one point per sample. Many more than this and stuff starts to scale very badly (eg. if someone tries to plot 100 sets of gene expression in one report).

What are you trying to plot? The expected format for tsv is `str : num : num` with no header line. So this works:

`sample1_foo_scatter_mqc.tsv`
```
# id: 'custom_data_scatter'
# description: 'foo'
# section_name: 'Custom Data File'
# plot_type: 'scatter'
# pconfig:
#     id: 'custom_data_scatter_plot'
#     title: 'Output from my script'
#     ylab: 'Number of things'
sample1 1       10
```

`sample2_foo_scatter_mqc.tsv`
```
# id: 'custom_data_scatter'
# description: 'foo'
# section_name: 'Custom Data File'
# plot_type: 'scatter'
# pconfig:
#     id: 'custom_data_scatter_plot'
#     title: 'Output from my script'
#     ylab: 'Number of things'
sample2 1.1     10.5
```
(can also have these in a single file).

You shouldn't have been able to get as far as you did with your files (far enough to trigger that error), I've just made the code checking a bit more stringent so that you get a nicer warning that the file format is bad now.

Phil

**Comment by ewels** [comment]
(see f6c2904df47bc718298fce48d763e0b3bd9056a2 for update).

**Comment by ewels** [comment]
Also, sample names can be shared. So I think you can get what you want by just prepending the sample name as the first column in both of your files. But I wash my hands of responsibility for any crashing browsers or badly scaling plots 😉

**Comment by ewels** [comment]
I take it back, sample names can't be shared..

**Comment by avilella** [comment]
Aha. Understood the format now. Thanks!

**Comment by ewels** [comment]
No problem! I know I need to improve the docs about the accepted formats, but probably won't get to this until next year now.
