### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by wwood** [ewels/MultiQC#376]
Hi, in updating the multiqc package for GNU Guix and adding unit tests I found them to be failing. I wanted to make sure the tests are supposed to pass, given their introduction was quite recent (as I understand).
```
======================================================================
FAIL: test_rep1 (unit_tests.test_samtools_flagstat.T)
Test that parsing rep1 produces expected results
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/p5a6z9mq8awjk8ncf485mmaiv00xy3sb-multiqc-test-data32bf18b4d7c46496ae50bfaf4c94a9df3afd0491-checkout/unit_tests/test_samtools_flagstat.py", line 59, in test_rep1
    self.assertEqual(len(res1), 13 + 13 + 3 + 3 + 1 )
AssertionError: 21 != 33

======================================================================
FAIL: test_rep2 (unit_tests.test_samtools_flagstat.T)
I expect rep2 to give identical results to rep1.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/gnu/store/p5a6z9mq8awjk8ncf485mmaiv00xy3sb-multiqc-test-data32bf18b4d7c46496ae50bfaf4c94a9df3afd0491-checkout/unit_tests/test_samtools_flagstat.py", line 83, in test_rep2
    self.assertEqual(res1, res2)
AssertionError: {'with itself and mate mapped_passed': 5273[669 chars] 0.0} != {'total_failed': 0.0, 'flagstat_total': 541[1021 chars]11.0}
  {'duplicates_failed': 0.0,
   'duplicates_passed': 0.0,
   'flagstat_total': 5414.0,
+  'mapped_failed': 0.0,
+  'mapped_failed_pct': nan,
+  'mapped_passed': 5350.0,
+  'mapped_passed_pct': 98.82,
   'paired in sequencing_failed': 0.0,
   'paired in sequencing_passed': 5401.0,
+  'properly paired_failed': 0.0,
+  'properly paired_failed_pct': nan,
+  'properly paired_passed': 5011.0,
+  'properly paired_passed_pct': 92.78,
   'read1_failed': 0.0,
   'read1_passed': 2709.0,
   'read2_failed': 0.0,
   'read2_passed': 2692.0,
   'secondary_failed': 0.0,
   'secondary_passed': 13.0,
+  'singletons_failed': 0.0,
+  'singletons_failed_pct': nan,
+  'singletons_passed': 64.0,
+  'singletons_passed_pct': 1.18,
   'supplementary_failed': 0.0,
   'supplementary_passed': 0.0,
   'total_failed': 0.0,
   'total_passed': 5414.0,
   'with itself and mate mapped_failed': 0.0,
   'with itself and mate mapped_passed': 5273.0,
   'with mate mapped to a different chr (mapQ >= 5)_failed': 0.0,
   'with mate mapped to a different chr (mapQ >= 5)_passed': 81.0,
   'with mate mapped to a different chr_failed': 0.0,
   'with mate mapped to a different chr_passed': 206.0}

----------------------------------------------------------------------
Ran 2 tests in 0.005s

FAILED (failures=2)
```
These tests are run inside the build container, using `python3 -munittest discover`, from the base directory of commit 079pcr6j2nk0v238qwsslgk480rv82xwsjyy4lf6v48l6zj4llm0 of MultiQC_TestData, after adding the unpacked and built multiqc 0.9 downloaded from pip.

Thanks in advance, ben.

**Comment by ewels** [comment]
Hi @wwood,

Many thanks for adding MultiQC to GNU Guix! The tests are a new feature for the upcoming v1.0 release (coming next year) so will fail with v0.9.

I can't find the commit hash you mention, but ewels/MultiQC_TestData@60b771f2d0db34a74452f478d4bc9a5245ede5d7 should be fine (before any test scripts were added).

Phil
