### ISSUE TITLE
ZeroDivisionError

### ISSUE THREAD

**Issue by gordonaa** [ewels/MultiQC#378]
```python
Module featureCounts raised an exception: Traceback (most recent call last):
  File "/u/home/.local/bin/multiqc", line 345, in multiqc
    report.modules_output.append(mod())
  File "/u/home/.local/lib/python2.7/site-packages/multiqc/modules/featureCounts/feature_counts.py", line 30, in __init__
    self.parse_featurecounts_report(f)
  File "/u/home/.local/lib/python2.7/site-packages/multiqc/modules/featureCounts/feature_counts.py", line 85, in parse_featurecounts_report
    data['percent_assigned'] = (float(data['Assigned'])/float(data['Total'])) * 100.0
ZeroDivisionError: float division by zero
```

**Comment by ewels** [comment]
Thanks for reporting this @gordonaa - now fixed!

Phil
