### ISSUE TITLE
Install issue with python 2.7?

### ISSUE THREAD

**Issue by tarah28** [ewels/MultiQC#428]
## Hi, I realize that this is likely not a multiqc problem but thought I'd ask for help as I'm stumped. 
When I try to run multiqc I get this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 31, in <module>
    from multiqc import logger, plots, __version__
  File "/usr/local/lib/python2.7/dist-packages/multiqc/__init__.py", line 6, in <module>
    from multiqc.modules.base_module import BaseMultiqcModule
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/base_module.py", line 13, in <module>
    from multiqc import plots
  File "/usr/local/lib/python2.7/dist-packages/multiqc/plots/__init__.py", line 1, in <module>
    from . import bargraph, beeswarm, heatmap, linegraph, scatter, table
  File "/usr/local/lib/python2.7/dist-packages/multiqc/plots/bargraph.py", line 34, in <module>
    template_mod = config.avail_templates[config.template].load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1988, in load
    if require: self.require(env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2001, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: click
```
So I tried to install click, env and installer:
```
t@linus:~$ pip install env
Requirement already satisfied: env in /usr/local/lib/python2.7/dist-packages
t@linus:~$ pip install click
Requirement already satisfied: click in /usr/local/lib/python2.7/dist-packages
t@linus:~$ pip install installer
Collecting installer
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement installer (from versions: )
No matching distribution found for installer

```
Sorry for the newbie question, any help is much appreciated!

**Comment by ewels** [comment]
Hi @tarah28,

No problem at all. What logs do you get when you try to install MultiQC? I'm not sure what the env and installer packages are, they're not direct requirements of MultiQC (you can see these [here](https://github.com/ewels/MultiQC/blob/master/setup.py#L50-L58)).

Very generally speaking, when people have problems installing MultiQC I usually recommend using conda - at least to manage Python + pip. Often everything starts to work then. See some suggestions here: http://multiqc.info/docs/#installing-multiqc

Phil

**Comment by ewels** [comment]
Ah, I see - you were reading this line: `if require: self.require(env, installer)` Those are variable names within the installation scripts, not Python package names.

You should only need to run `pip install multiqc` - all dependencies should automatically be resolved (when it works properly, anyway).

Phil

**Comment by tarah28** [comment]
Hi @ewels, thanks for the quick reply! All looks good when I install, seemed pretty straightforward but when I try to run it I get that error above. I can try installing with conda instead as suggested

```
t@linus:~$ pip install multiqc
Requirement already satisfied: multiqc in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: jinja2 in /usr/local/lib/python2.7/dist-packages (from multiqc)
Requirement already satisfied: simplejson in /usr/lib/python2.7/dist-packages (from multiqc)
Requirement already satisfied: pyyaml in /usr/local/lib/python2.7/dist-packages (from multiqc)
Requirement already satisfied: click in /usr/local/lib/python2.7/dist-packages (from multiqc)
Requirement already satisfied: matplotlib in /usr/lib/pymodules/python2.7 (from multiqc)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from jinja2->multiqc)
```

**Comment by ewels** [comment]
Hi @tarah28,

This is strange. The install log says that `click` is installed, then when you run MultiQC it says that it can't find `click`...

Can you run `which python` and `which multiqc` please? I wonder if you have multiple python installations or something. It'd also be interesting to run `multiqc -v`, pasting the full log from that command here.

Cheers,

Phil

**Comment by tarah28** [comment]
Hi @ewels,

Sorry for the super late reply! Here's what I get:
<which python>
```/usr/bin/python```
<which multiqc>
```/usr/local/bin/multiqc```
<multiqc -v>
```
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 31, in <module>
    from multiqc import logger, plots, __version__
  File "/usr/local/lib/python2.7/dist-packages/multiqc/__init__.py", line 6, in <module>
    from multiqc.modules.base_module import BaseMultiqcModule
  File "/usr/local/lib/python2.7/dist-packages/multiqc/modules/base_module.py", line 13, in <module>
    from multiqc import plots
  File "/usr/local/lib/python2.7/dist-packages/multiqc/plots/__init__.py", line 1, in <module>
    from . import bargraph, beeswarm, heatmap, linegraph, scatter, table
  File "/usr/local/lib/python2.7/dist-packages/multiqc/plots/bargraph.py", line 34, in <module>
    template_mod = config.avail_templates[config.template].load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1988, in load
    if require: self.require(env, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2001, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: click
```

**Comment by ewels** [comment]
Ok, well one thing that you can try doing is running the latest development version - the code that is throwing the error has been rewritten since the last release so that could help?

You can install this with the following command:

```
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

To be honest, beyond this I don't have much of an idea of what is going wrong though, and as I'm unable to replicate the error there's not much I can do.. If the latest dev version doesn't work, I'd try using conda, hopefully that'll work.

Phil

**Comment by tarah28** [comment]
That did the trick! Thanks so much for your help @ewels! Looking forward to using this program :)

**Comment by ewels** [comment]
Brilliant! I had almost lost hope :relieved:

Thanks for letting me know!
