### ISSUE TITLE
Qualimap bamqc fails if there is no genome-gc-distribution

### ISSUE THREAD

**Issue by asabjorklund** [ewels/MultiQC#436]
When qualimap was run without the `-gd` (`--genome-gc-distribution`) flag, the MultiQC module fails since `extra_series` is empty. However, if I rerun qualimap on the same data, but adding flag `-gd hg19` MultiQC works fine.

```
[Error  ]         multiqc : Oops! The 'qualimap' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module qualimap raised an exception: Traceback (most recent call last):
  File "/media/box2/Experiments/Joanna/bin/miniconda3/envs/j_frisen_1602/lib/python3.5/site-packages/multiqc-0.9-py3.5.egg/EGG-INFO/scripts/multiqc", line 344, in multiqc
    output = mod()
  File "/media/box2/Experiments/Joanna/bin/miniconda3/envs/j_frisen_1602/lib/python3.5/site-packages/multiqc-0.9-py3.5.egg/multiqc/modules/qualimap/qualimap.py", line 40, in __init__
    n['BamQC'] = QM_BamQC.parse_reports(self)
  File "/media/box2/Experiments/Joanna/bin/miniconda3/envs/j_frisen_1602/lib/python3.5/site-packages/multiqc-0.9-py3.5.egg/multiqc/modules/qualimap/QM_BamQC.py", line 54, in parse_reports
    report_sections(self)
  File "/media/box2/Experiments/Joanna/bin/miniconda3/envs/j_frisen_1602/lib/python3.5/site-packages/multiqc-0.9-py3.5.egg/multiqc/modules/qualimap/QM_BamQC.py", line 324, in report_sections
    'extra_series': extra_series,
  File "/media/box2/Experiments/Joanna/bin/miniconda3/envs/j_frisen_1602/lib/python3.5/site-packages/multiqc-0.9-py3.5.egg/multiqc/plots/linegraph.py", line 89, in plot
    elif type(pconfig['extra_series']) == list and type(pconfig['extra_series'][0]) == dict:
IndexError: list index out of range

```

**Comment by ewels** [comment]
Thanks for the report @asabjorklund, that's annoying. What version of MultiQC are you running with? (A few bugs have been ironed out since the v0.9 release).

Phil

**Comment by asabjorklund** [comment]
I am using multiqc 0.9 py35 installed from bioconda. If you think this bug might be fixed in the devel version, I could try that version and let you know if it works.
/Åsa

**Comment by ewels** [comment]
Hi Åsa,

Taking a quick look at the current code, I don't think that it's fixed yet. Should be simple enough though - I'll try to look at this for you tomorrow.

Phil

**Comment by asabjorklund** [comment]
Thanks Phil, no rush on my behalf, I changed my pipe now to include the -gd flag. But for future users it may be a good idea to fix this ;)
/Å

**Comment by ewels** [comment]
Hi Åsa,

I've just pushed a change that should hopefully fix the error. I don't have any Qualimap reports to test it with though, so would be great if you could check that it works as intended!

Thanks,

Phil

**Comment by asabjorklund** [comment]
Hi Phil,

I just gave the new version a try and it works fine with files that did not have -gd flag. Great work!

/Åsa

**Comment by ewels** [comment]
Great stuff, thanks!
