### ISSUE TITLE
Merge Atropos module into MultiQC

### ISSUE THREAD

**Issue by jdidion** [ewels/MultiQC#447]
I have a working MultiQC module for [Atropos](http://github.com/jdidion/atropos) here: https://github.com/jdidion/atropos-multiqc. Would you be willing to add it to MultiQC? If so, can you pull it directly from my repo, or should I submit it as a pull request?

**Comment by ewels** [comment]
Hi @jdidion,

This looks great! Really nice that you decided to support MultiQC in this way. You're a little ahead of the curve by writing your own module like this, sort of fitting into a model of MultiQC development that I thought about almost exactly [one year ago](https://github.com/ewels/MultiQC/issues/181).

Anyway, we have two options going forward:

1. Merge your code into the main MultiQC repo
    * _Pro:_ Everyone gets out-of-the-box support for Atropos when they install MultiQC
    * _Con:_ You have to mess around copying and pasting and lose the existing repo + history
    * _Con:_ You will have to put up with me nitpicking over your code in a PR 😉 
2. Keep your code separate
    * You're welcome to fork it into the [MultiQC organisation](https://github.com/MultiQC) to help keep things centralised. This is the way that I envisage things moving in the future, though not much has happened yet.
    * _Pro_: Basically no additional work
    * _Con_: As it stands, people have to run a second installation to use your module

As described in that issue linked above, I quite like the idea of having all modules as stand-alone MultiQC "plugins" in this way as it keeps the main codebase a lot smaller and less co-dependent on releases. However, it also introduces quite a few problems (requirement of an internet connection etc) and work, which is why it hasn't happened yet. It's likely to be quite a long time until this happens, so my recommendation at this point would be for option 1.

Sorry for the somewhat long response - hope that makes sense. I'd welcome and thoughts or suggestions!

Phil

**Comment by jdidion** [comment]
@ewels - Option 1 does sound like the best approach at this point, although I do like the idea of an ecosystem where tool developers can create plugins within the MultiQC organization but not as a part of the core software, and the software is able to install any requested/missing modules on the fly.

Having someone nitpick my code sounds like a good idea. I mostly borrowed the code from the Cutadapt and FastQC modules, so it will probably end up being you nitpicking your own code :) My plan was always to get this working as a stand-alone module and then merge into MultiQC, so I’m fine with losing the repo history.

**Comment by ewels** [comment]
Ok, sounds good. In that case then yes - please go ahead and for this repo, add your code, and submit a PR.

**Comment by ewels** [comment]
ps. Also, please submit a PR to [ewels/MultiQC_TestData](https://github.com/ewels/MultiQC_TestData) with some example log files so that the automated tests run and so that I can have a play with your code. It's best if this is done first, then Travis will run properly when you open the PR here.

Phil

**Comment by tanaes** [comment]
Updated with code for Atropos (thanks @jdidion) and some test data in [a PR](https://github.com/ewels/MultiQC_TestData/pull/71) to MultiQC_TestData.

**Comment by antgonza** [comment]
Adding here to avoid opening a new issue.

In a new multiqc installation, I added the atropos module by using `pip install https://github.com/jdidion/atropos-multiqc/archive/master.zip`, and it seems like it worked fine. 

However, when I run multiqc on a given folder, either via `multiqc -m atropos_trim` or `multiqc`, it raises an error:
```bash
$ multiqc -m atropos_trim atropos_qc --outdir atropos_qc/summary
[INFO   ]         multiqc : This is MultiQC v1.8
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : /home/antoniog/mg-scripts/fastq/atropos_qc
[INFO   ]         multiqc : Only using modules atropos_trim
[ERROR  ]         multiqc : Oops! The 'atropos_trim' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    None
============================================================
Module atropos_trim raised an exception: Traceback (most recent call last):
  File "/home/antoniog/miniconda3/envs/qp-shogun/lib/python3.7/site-packages/multiqc/multiqc.py", line 546, in run
    output = mod()
  File "/home/antoniog/miniconda3/envs/qp-shogun/lib/python3.7/site-packages/multiqc_atropos/modules/atropos/atropos.py", line 183, in __init__
    super().__init__(name="Atropos", anchor="atropos", **kwargs)
  File "/home/antoniog/miniconda3/envs/qp-shogun/lib/python3.7/site-packages/multiqc_atropos/modules/atropos/atropos.py", line 88, in __init__
    self.init_from_config()
  File "/home/antoniog/miniconda3/envs/qp-shogun/lib/python3.7/site-packages/multiqc_atropos/modules/atropos/atropos.py", line 107, in init_from_config
    for file_dict in self.find_log_files(patterns, filehandles=True):
  File "/home/antoniog/miniconda3/envs/qp-shogun/lib/python3.7/site-packages/multiqc/modules/base_module.py", line 81, in find_log_files
    if report.search_file(sp_key, {'fn': sf[0], 'root': sf[1]}):
TypeError: search_file() missing 1 required positional argument: 'module_key'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

Any suggestions on how to fix? Also, just out of curiosity, what's needed for this module to be merged?
