### ISSUE TITLE
problem with samtools stats and bcftools

### ISSUE THREAD

**Issue by MaxUlysse** [ewels/MultiQC#451]
A little more about a problem with `samtools stats` and `bcftools`
Here is my Traceback log
```python
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 588, in <module>
    multiqc()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/multiqc", line 400, in multiqc
    del report.general_stats_data[i]
IndexError: list assignment index out of range
```
I managed to get a minimal sets of 2 logs that produce this error and joined my multiqc output:
[minimal_error_miltiqc.zip](https://github.com/ewels/MultiQC/files/943665/minimal_error_miltiqc.zip)

I'm using multiqc `v1.0.dev0`
I hope it'll help you to find out what is the problem (if you managed to reproduce it).

**Comment by ewels** [comment]
Thanks for this @MaxUlysse! I think this uncovered a nastier bug where MultiQC wasn't failing in my tests, but was messing up other stuff. Should be fixed now anyway 👍

**Comment by MaxUlysse** [comment]
No problem, I'm glad I helped you on that ;-)
Thanks a lot for the fix, it'll save my Travis tests
