### ISSUE TITLE
Multiqc 1.0 error on python 3.6 due to click

### ISSUE THREAD

**Issue by jfreimer** [ewels/MultiQC#484]
I just installed multiqc 1.0 with conda using python 3.6. However, multiqc fails with the following error. I saw something about a patch coming, but is there anyway to get multiqc running on conda for now?
Thanks

**Error log:**
```
[jfreimer@h1 ~]$ multiqc --help
Traceback (most recent call last):
  File "/N/u/jfreimer/Mason/miniconda3/bin/multiqc", line 4, in <module>
    __import__('pkg_resources').run_script('multiqc==1.0', 'multiqc')
  File "/N/u/jfreimer/Mason/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/N/u/jfreimer/Mason/miniconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/gpfs/home/j/f/jfreimer/Mason/miniconda3/lib/python3.6/site-packages/multiqc-1.0-py3.6.egg/EGG-INFO/scripts/multiqc", line 640, in <module>
    multiqc()
  File "/N/u/jfreimer/Mason/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/N/u/jfreimer/Mason/miniconda3/lib/python3.6/site-packages/click/core.py", line 676, in main
    _verify_python3_env()
  File "/N/u/jfreimer/Mason/miniconda3/lib/python3.6/site-packages/click/_unicodefun.py", line 118, in _verify_python3_env
    'for mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.
```

Here are the package versions I have from conda:
```
[jfreimer@h1 ~]$ conda list
# packages in environment at /N/u/jfreimer/Mason/miniconda3:
#
asn1crypto                0.22.0                   py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
ca-certificates           2017.4.17                     0    conda-forge
certifi                   2017.4.17                py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.2                    py36_1    conda-forge
click                     6.7                      py36_0    conda-forge
colormath                 2.1.1                    py36_0    conda-forge
conda                     4.3.22                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
cryptography              1.9                      py36_0    conda-forge
cutadapt                  1.14                     py36_0    bioconda
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.10.10                       3    conda-forge
decorator                 4.0.11                   py36_0    conda-forge
docutils                  0.13.1                   py36_0    conda-forge
dropbox                   5.2.1                    py36_0    bioconda
expat                     2.1.0                         2    conda-forge
fastqc                    0.11.5                        1    bioconda
filechunkio               1.6                      py36_0    bioconda
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
ftputil                   3.2                      py36_0    bioconda
future                    0.16.0                   py36_0    conda-forge
gettext                   0.19.7                        1    conda-forge
glib                      2.51.4                        0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
icu                       58.1                          1    conda-forge
idna                      2.5                      py36_0    conda-forge
java-jdk                  8.0.92                        1    bioconda
jinja2                    2.9.5                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         1
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libxcb                    1.12                          1    conda-forge
libxml2                   2.9.4                         4    conda-forge
lzstring                  1.0.3                    py36_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.2               np113py36_0    conda-forge
mkl                       2017.0.1                      0
multiqc                   1.0                      py36_4    bioconda
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py36_0    conda-forge
numpy                     1.13.0          py36_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
openjdk                   8.0.121                       1
openssl                   1.0.2k                        0    conda-forge
packaging                 16.8                     py36_0    conda-forge
pandas                    0.20.2              np113py36_1    conda-forge
paramiko                  2.1.2                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
perl                      5.22.2.1                      0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
psutil                    5.2.1                    py36_0    conda-forge
pyasn1                    0.2.3                    py36_0    conda-forge
pycosat                   0.6.1                    py36_0    conda-forge
pycparser                 2.17                     py36_0    conda-forge
pyopenssl                 16.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysftp                    0.2.9                    py36_0    bioconda
pysocks                   1.6.7                    py36_0    conda-forge
python                    3.6.1                         3    conda-forge
python-dateutil           2.6.0                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
qt                        5.6.2                         3    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.1                   py36_0    conda-forge
ruamel_yaml               0.11.14                  py36_0    conda-forge
setuptools                33.1.1                   py36_0    conda-forge
simplejson                3.8.1                    py36_0    bioconda
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
snakemake                 3.13.3                   py36_0    bioconda
spectra                   0.0.7                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        1    conda-forge
tornado                   4.5.1                    py36_0    conda-forge
urllib3                   1.21.1                   py36_1    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
wrapt                     1.10.8                   py36_0    conda-forge
xopen                     0.1.1                    py36_0    bioconda
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

**Comment by ewels** [comment]
Hi @jfreimer,

Thanks for this - the problem you're seeing is a new one to me and separate from the previous problems I had with click + python3 + bioconda. Thankfully, it sounds like it should be fairly easy for you to fix. It's described in the [click documentation](http://click.pocoo.org/5/python3/#python-3-surrogate-handling) and basically comes down to running these commands (hopefully!):

```bash
export LC_ALL=C.UTF-8
export LANG=C.UTF-8
```

This same error is sometimes thrown by MatPlotLib (not python3 specific) and is described in the [MultiQC docs](http://multiqc.info/docs/#locale-error-messages). Can you try that and let me know how you get on? If it works then I'll expand the docs to describe this one too.

Cheers,

Phil

**Comment by chambm** [comment]
I actually had the same error  when running MultiQC in Galaxy. Adding those environment variables to my job_conf.xml did fix that error, but now I have a possibly related problem: the output HTML displays as gibberish (zoomed out to show a greater extent of its gibberishness):
![image](https://user-images.githubusercontent.com/5011937/27653048-7f84e794-5c03-11e7-9e3e-c0e31a064a54.png)

**Comment by chambm** [comment]
Nevermind about the gibberish. It was due to Galaxy sanitizing the HTML display, which can be avoided if the tool is whitelisted. Now I'm off to tell the wrapper maintainer that they need to add a big all-caps notice about that in the toolshed. :)

Also I got rid of the "not a valid language tag" warning by using "en_US.utf-8" instead. This is on a Ubuntu 14.04 host and some docs said C.UTF-8 is available on newer Linux only.

**Comment by ewels** [comment]
Great stuff, thanks @chambm! (Note to self: PR for Galaxy + instructions at EnginesOn/galaxy_tools#10). I've updated the [MultiQC troubleshooting docs](http://multiqc.info/docs/#locale-error-messages) with this error. Also good to know about the `C.UTF-8` problem.

I'll close this issue now as I hope it's resolved. @jfreimer - please reopen if you're still having problems.
