### ISSUE TITLE
Allow relative path for custom logo file

### ISSUE THREAD

**Issue by pditommaso** [ewels/MultiQC#493]
When customising the MultiQC report it would be useful being able to provide the logo by specifying a path relative to the configuration file.

Currently relative path seems to be resolved against a temporary directory. I'm getting the following error message: 

```python
Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 4, in <module>
    __import__('pkg_resources').run_script('multiqc==1.0', 'multiqc')
  File "/usr/local/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/usr/local/lib/python3.5/site-packages/setuptools-27.2.0-py3.5.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/usr/local/lib/python3.5/site-packages/multiqc-1.0-py3.5.egg/EGG-INFO/scripts/multiqc", line 640, in <module>
    multiqc()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/multiqc-1.0-py3.5.egg/EGG-INFO/scripts/multiqc", line 548, in multiqc
    report_output = j_template.render(report=report, config=config)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/tmp/tmp6184e9cy/base.html", line 31, in top-level template code
    {% include 'header.html' %}
  File "/tmp/tmp6184e9cy/header.html", line 15, in top-level template code
    <img src="data:image/png;base64,{{ include_file(config.custom_logo, b64=True) }}" title="{{ config.custom_logo_title if config.custom_logo_title is not none }}">
  File "/usr/local/lib/python3.5/site-packages/multiqc-1.0-py3.5.egg/EGG-INFO/scripts/multiqc", line 532, in include_file
    with io.open (os.path.join(fdir, name), "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp6184e9cy/nextflow2014_logo_large.png'
```

**Comment by ewels** [comment]
Hi @pditommaso,

I've just put this together for you, I think it should work now. The new behaviour is that it checks whether the given file path exists (_eg._ if it's absolute, or relative to the working directory). If not, it checks to see if the file path exists when joined to the config file directory. In both cases, if found, the file path is then made absolute. If it's not found after this, an error is logged and it's ignored going forward.

Let me know if it works / breaks!

Phil

**Comment by pditommaso** [comment]
Nice, thanks! How to use it? How you uploaded a new release ?

**Comment by ewels** [comment]
Just pull the latest version from GitHub. One-liner with `pip` here: https://github.com/ewels/MultiQC#installation

```
pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

By chance, also hoping to release v1.1 today though..

Phil

**Comment by pditommaso** [comment]
The upgrade failed in my box :(
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/site-packages/python_dateutil-2.6.0-py3.5.egg'
```

However, no hurry. I'll wait the stable release. Thanks a lot!
