### ISSUE TITLE
Error when calling general_stats_addcols with dict that has ints as keys 

### ISSUE THREAD

**Issue by iimog** [ewels/MultiQC#521]
**Description of bug:**
When developing a module and calling the `self.general_stats_addcols` function with a dictionary that uses something other than string as keys (e.g. ints) there is an error. This is related to #519 Example:
```python
data = {
    0: {
        'first_col': 91.4,
        'second_col': '78.2%'
    },
    1: {
        'first_col': 138.3,
        'second_col': '66.3%'
    }
}
self.general_stats_addcols(data)
```

**Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.2.dev0 (e86ba77)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 3 files..  [####################################]  100%
Traceback (most recent call last):
  File "/tank/home/s216121/miniconda3/bin/multiqc", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/tank/home/s216121/software/MultiQC/scripts/multiqc", line 669, in <module>
    multiqc()
  File "/tank/home/s216121/miniconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/tank/home/s216121/miniconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/tank/home/s216121/miniconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tank/home/s216121/miniconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/tank/home/s216121/software/MultiQC/scripts/multiqc", line 459, in multiqc
    report.general_stats_html = table.plot(report.general_stats_data, report.general_stats_headers, pconfig)
  File "/tank/home/s216121/software/MultiQC/multiqc/plots/table.py", line 44, in plot
    return make_table ( dt )
  File "/tank/home/s216121/software/MultiQC/multiqc/plots/table.py", line 249, in make_table
    t_row_keys = sorted(t_row_keys)
TypeError: unorderable types: int() < str()
```

* **File that triggers the error:**
    * none required
* **Operating System:**
    * Ubuntu 16.04
* **Python Version:**
    * Python 3.5.2
* **Method of MultiQC installation:**
    * manual

**Comment by iimog** [comment]
Actually it only happens if you call `self.general_stats_addcols` multiple times (can be from different files) once with ints as keys and once with strings. Like this:
```python
data = {
    0: {
        'first_col': 91.4,
        'second_col': '78.2%'
    },
    1: {
        'first_col': 138.3,
        'second_col': '66.3%'
    }
}
self.general_stats_addcols(data)

data = {
    'foo': {
        'first_col': 91.4,
        'second_col': '78.2%'
    },
    'bar': {
        'first_col': 138.3,
        'second_col': '66.3%'
    }
}
self.general_stats_addcols(data)
```
