### ISSUE TITLE
Running MultiQC with config file

### ISSUE THREAD

**Issue by rdali** [ewels/MultiQC#551]
Hello Phil, 

I am trying to customize the multiqc report using the config file. 
I created a `multiqc_config.yaml` file in my working directory and pasted the content of `multiqc_config_example.yaml`

When I run multiqc (`multiqc .`) it creates an error even though before the config file was created it worked just fine. What am I doing wrong?

```python
Traceback (most recent call last):
  File "/home/.local/bin/multiqc", line 668, in <module>
    multiqc()
  File "CentOS6/software/python/Python-2.7.13/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "CentOS6/software/python/Python-2.7.13/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "CentOS6/software/python/Python-2.7.13/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "CentOS6/software/python/Python-2.7.13/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/.local/bin/multiqc", line 187, in multiqc
    config.mqc_load_userconfig(config_file)
  File "/home/.local/lib/python2.7/site-packages/multiqc/utils/config.py", line 110, in mqc_load_userconfig
    mqc_load_config('multiqc_config.yaml')
  File "/home/.local/lib/python2.7/site-packages/multiqc/utils/config.py", line 124, in mqc_load_config
    mqc_add_config(new_config, yaml_config)
  File "/home/.local/lib/python2.7/site-packages/multiqc/utils/config.py", line 169, in mqc_add_config
    if os.path.exists(v):
  File "CentOS6/software/python/Python-2.7.13/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by ewels** [comment]
Hi @rdali,

What version of MultiQC are you running? Could you paste the entire log please? Ideally if you can rerun it in verbose mode (`-v`) and paste that entire log that would be great. Feel free to use [pastebin](https://pastebin.com/) if it's very long.

Phil

**Comment by rdali** [comment]
Here is the log:

**Comment by ewels** [comment]
Ok great, thanks for that. It looks like this is the same error that was reported in #502 and is fixed in the current development version. It should be fixed in the upcoming v1.2 release (hopefully out this week), or if you grab the latest development version of the code. But probably easiest is to remove the offending line of code from the `multiqc_config.yaml` file:

```yaml
custom_logo: null
```

I added parsing of the example config file to the automated tests to catch problems like this in the future, and I'm thinking of removing `multiqc_config_example.yaml` file as it contains a lot of unused things and I'd prefer people to add just the lines that they need to config files.

Thanks for reporting anyway and I hope that helps! Let me know if you have any opinions about whether `multiqc_config_example.yaml` should stay or go :)

Phil

**Comment by rdali** [comment]
Thanks!
I think multiqc_config_example.yaml is useful as a template; I downloaded it to edit it based on my needs.

**Comment by ewels** [comment]
Yeah, that's another of my concerns though as it only contains a fraction of the available config options :) Hmm..
