### ISSUE TITLE
Module extension: QoRTs

### ISSUE THREAD

**Issue by friedue** [ewels/MultiQC#564]
Following up on [the previous issue here](https://github.com/ewels/MultiQC/issues/485)

* **Name of tool:**
    * QoRTs
* **Tool description:**
    * The QoRTs software package is a fast, efficient, and portable multifunction toolkit designed to assist in the analysis, quality control, and data management of RNA-Seq datasets
* **Tool homepage:**
    * [http://hartleys.github.io/QoRTs/](http://hartleys.github.io/QoRTs/)
* **Complete log file output:**
    * there is the general `summary.txt` and there are numerous additional files that underlie the various plots that QoRTs can produce
    * will share all via the MultiQC data repo
* **Most interesting data for General Stats table:** [based on `QC.summary.txt`]
    * `StrandTest_frFirstStrand`, `StrandTest_frSecondStrand`
                 - useful to determine what kind of strand specific protocol was used
                - if both numbers are more or less the same, this indicates unstranded data
   * `head -n 16 QC.summary.txt`  and `ReadPairs*` and `Genes_*` and `NumberOfChromosomesCovered` -- basic alignment stats
* **Data suitable for MultiQC plot(s):**
    * `ReadPairs*`
    * more data from additional files (see MultiQC data repo)

My own personal preference would include the following plots/data (listed based on priority):

* gene diversity
* aggregate genes
* strand test
* the mapping stats

**Comment by ewels** [comment]
Hi @friedue,

I've just added code to the module to produce a few new plots, remove the confusing GeneBodyCoverage plot and add data to the General Stats table. So far, this is only using the data that the module was already parsing from the summary files. I'll look at adding the Gene Diversity plot next.

Regarding aggregate genes - I didn't do anything here as I'm not totally clear on what this is or why it's useful. Could you explain what these stats tell you? (Then I can add this as help text too).

Phil

**Comment by christiankroy** [comment]
Thanks for implementing support for QoRTs.  I've tried running this with individual QoRTs folders for >200 different RNA-Seq libraries and I only get values for a library called `COUNT` in the final html report.  Am I not specifying where the sample names should come from correctly?  Thanks again.

using QoRTs version 1.1.8 and multiqc v 1.3.0dev

**Comment by ewels** [comment]
Hi @christiankroy,

Short answer - if these files are in subfolders with meaningful names, you can fix this by using `-d` (and/or `-dd`), as described in [the docs](http://multiqc.info/docs/#sample-names-prefixed-with-directories).

Longer answer - the [example data](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/qorts/summary.table.txt) that I wrote the module around had multiple samples per summary file and the header cells contained the sample names. However, from what you describe and some [more recent example data](https://github.com/ewels/MultiQC_TestData/blob/master/data/modules/qorts/ver1.2.42/QC.summary.txt), it sounds like sometimes it's just one sample and the less useful `COUNT`.

I'm assuming that you didn't specify `COUNT` anywhere and that it's some kind of default? I think I'll change the code to keep the current behaviour _except_ for when there is only two columns in the file and the header says exactly `COUNT`. In those cases I'll use the filename as the sample name instead. Would that work for you?

Phil

**Comment by ewels** [comment]
Ok, I've just pushed that change for you as it was very quick - if you could pull the latest changes and let me know if that does the job for you that would be great!

Thanks,

Phil

**Comment by christiankroy** [comment]
Phil,

Thanks so much for your prompt response.  And for writing this *extremely* impressive set of software.  It was exactly what we needed, exactly when we needed it.

You correctly caught me on not knowing about `--dd`.  Once I provided that argument the `QoRTs` logs were correctly parsed.  I had not gone looking for that argument because the rest of the modules were parsed correctly.

And your assumption stated above is correct.  My `QoRTs` command was in the context of per-sample pipeline and thus the summary file only had 2 columns, one of which was `COUNT`.

I *haven't* pulled your latest changes or tested, as the `-dd` command fixed my issue, but it sounds as though you correctly understand my issue.  Thanks again!

-Chris

**Comment by royfrancis** [comment]
QoRTs module runs into error. I wasn't sure if this has to be a new error topic or if it goes under this qorts module request. I can open a new topic if necessary.

```
$ multiqc --interactive -m samtools -m bamtools -m qorts . ../test-bwa-sanger/c20-01-bwa-qorts/ ../../bwa-ensembl/qorts/c20-01-bwa-qorts/
[INFO   ]         multiqc : This is MultiQC v1.3 (2017dd0)
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[INFO   ]         multiqc : Searching '../test-bwa-sanger/c20-01-bwa-qorts/'
[INFO   ]         multiqc : Searching '../../bwa-ensembl/qorts/c20-01-bwa-qorts/'
[INFO   ]         multiqc : Only using modules samtools, bamtools, qorts
Searching 98 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'qorts' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module qorts raised an exception: Traceback (most recent call last):
  File "/home/royfranc/.pyenv/versions/2.7.6/bin/multiqc", line 412, in multiqc
    output = mod()
  File "/home/royfranc/.pyenv/versions/2.7.6/lib/python2.7/site-packages/multiqc/modules/qorts/qorts.py", line 29, in __init__
    self.parse_qorts(f)
  File "/home/royfranc/.pyenv/versions/2.7.6/lib/python2.7/site-packages/multiqc/modules/qorts/qorts.py", line 64, in parse_qorts
    self.qorts_data[s_name][s[0]] = float(s[i+1])
ValueError: could not convert string to float: Code for the strandedness rule used. 0 if data is unstranded, 1 if data is fr_firstStrand, 2 if data is fr_secondStrand.
============================================================
[INFO   ]        samtools : Found 2 stats reports
[INFO   ]        bamtools : Found 2 bamtools stats reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**Comment by bankhead3** [comment]
I also get the same error as royfrancis.

**Comment by ewels** [comment]
Ah sorry, yes please could one of you make a new issue. Comments on closed issues are easy to miss in my inbox and don’t show up when I check through unresolved issues..

**Comment by royfrancis** [comment]
#639 #
