### ISSUE TITLE
Distribution not found matplotlib 

### ISSUE THREAD

**Issue by likelet** [ewels/MultiQC#586]
Hi @ewels,

I came across the following error message this morning in my new server. It seems a dependency issue:

```
[INFO   ]         multiqc : This is MultiQC v1.2
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './'
Traceback (most recent call last):
  File "/usr/bin/multiqc", line 723, in <module>
    multiqc()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/multiqc", line 389, in multiqc
    template_mod = config.avail_templates[config.template].load()
  File "/usr/lib64/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 1947, in load
    if require: self.require(env, installer)
  File "/usr/lib64/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 1960, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/usr/lib64/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: matplotlib
```

So I checked the install logs of multiQC, it run smoothly without any error reported:

```
$ sudo pip install multiqc

Collecting multiqc
  Downloading multiqc-1.2.tar.gz (1.3MB)
    100% |████████████████████████████████| 1.3MB 202kB/s 
Requirement already satisfied: click in /usr/lib/python2.7/site-packages (from multiqc)
Requirement already satisfied: future>0.14.0 in /usr/lib/python2.7/site-packages (from multiqc)
Requirement already satisfied: lzstring in /usr/lib/python2.7/site-packages (from multiqc)
Requirement already satisfied: jinja2>=2.9 in /usr/lib64/python2.7/site-packages (from multiqc)
Requirement already satisfied: matplotlib in /usr/lib64/python2.7/site-packages (from multiqc)
Collecting markdown (from multiqc)
  Downloading Markdown-2.6.9.tar.gz (271kB)
    100% |████████████████████████████████| 276kB 181kB/s 
Requirement already satisfied: numpy in /usr/lib64/python2.7/site-packages (from multiqc)
Requirement already satisfied: pyyaml in /usr/lib64/python2.7/site-packages (from multiqc)
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from multiqc)
Requirement already satisfied: simplejson in /usr/lib64/python2.7/site-packages (from multiqc)
Requirement already satisfied: spectra in /usr/lib/python2.7/site-packages (from multiqc)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python2.7/site-packages (from jinja2>=2.9->multiqc)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 in /usr/lib/python2.7/site-packages (from matplotlib->multiqc)
Requirement already satisfied: six>=1.10 in /usr/lib/python2.7/site-packages (from matplotlib->multiqc)
Requirement already satisfied: pytz in /usr/lib/python2.7/site-packages (from matplotlib->multiqc)
Requirement already satisfied: functools32 in /usr/lib/python2.7/site-packages (from matplotlib->multiqc)
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from matplotlib->multiqc)
Requirement already satisfied: cycler>=0.10 in /usr/lib/python2.7/site-packages (from matplotlib->multiqc)
Requirement already satisfied: subprocess32 in /usr/lib64/python2.7/site-packages (from matplotlib->multiqc)
Requirement already satisfied: colormath in /usr/lib/python2.7/site-packages (from spectra->multiqc)
Requirement already satisfied: networkx in /usr/lib/python2.7/site-packages (from colormath->spectra->multiqc)
Requirement already satisfied: decorator>=3.4.0 in /usr/lib/python2.7/site-packages (from networkx->colormath->spectra->multiqc)
Installing collected packages: markdown, multiqc
  Running setup.py install for markdown ... done
  Running setup.py install for multiqc ... done
```

Then I reinstalled `matplotlib` by pip, but problem still exists. Any suggestions?

PS: I review the issue list and found that https://github.com/ewels/MultiQC/issues/428 may give a solution. but after put (no error throw out) this command as you suggested:

```
sudo pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
```

Then error message changed:

```
$ multiqc ./

[INFO   ]         multiqc : This is MultiQC v1.3dev
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './'
Traceback (most recent call last):
  File "/usr/bin/multiqc", line 724, in <module>
    multiqc()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/multiqc", line 390, in multiqc
    template_mod = config.avail_templates[config.template].load()
  File "/usr/lib64/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 1947, in load
    if require: self.require(env, installer)
  File "/usr/lib64/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 1960, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer))
  File "/usr/lib64/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: networkx<2
```

**Comment by ewels** [comment]
Hi @likelet,

It sounds like you've come across two problems here - firstly, MatPlotLib didn't install properly or was broken, which was causing an error for MultiQC. That was fixed by the `--force-reinstall` command that you found and used.

Once fixed, it revealed a second, different problem with the new `networkx` dependency (see #561). This error message is because you're using a fairly old version of `pip` - I think it would be solved if you do `pip update pip`. However, it's also been changed in #571 a couple of weeks ago when others reported the same error. I guess you must have run that reinstall command before that, so I think if you just run it again to pull the latest version of MultiQC then it should also be fine.

Let me know how you get on!

Cheers,

Phil

**Comment by likelet** [comment]
Thanks @ewels , I think my pip is already up to date 
```
$pip -V
pip 9.0.1 from /usr/lib/python2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)
```
anyway, I reinstall pip and reinstall multiqc by the `--force-reinstall`, it report another error 
```
$sudo pip install --upgrade --force-reinstall git+https://github.com/ewels/MultiQC.git
Collecting git+https://github.com/ewels/MultiQC.git
  Cloning https://github.com/ewels/MultiQC.git to /tmp/pip-_e_7Dp-build
Collecting click (from multiqc==1.3dev)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting future>0.14.0 (from multiqc==1.3dev)
  Using cached future-0.16.0.tar.gz
Collecting lzstring (from multiqc==1.3dev)
  Using cached lzstring-1.0.3-py2.py3-none-any.whl
Collecting jinja2>=2.9 (from multiqc==1.3dev)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Collecting matplotlib (from multiqc==1.3dev)
  Using cached matplotlib-2.0.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting markdown (from multiqc==1.3dev)
  Using cached Markdown-2.6.9.tar.gz
Collecting numpy (from multiqc==1.3dev)
  Using cached numpy-1.13.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pyyaml (from multiqc==1.3dev)
  Using cached PyYAML-3.12.tar.gz
Collecting requests (from multiqc==1.3dev)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Collecting simplejson (from multiqc==1.3dev)
  Using cached simplejson-3.11.1.tar.gz
Collecting spectra (from multiqc==1.3dev)
  Using cached spectra-0.0.8.tar.gz
Collecting networkx<2 (from multiqc==1.3dev)
  Using cached networkx-1.11-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2>=2.9->multiqc==1.3dev)
  Using cached MarkupSafe-1.0.tar.gz
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=1.5.6 (from matplotlib->multiqc==1.3dev)
  Using cached pyparsing-2.2.0-py2.py3-none-any.whl
Collecting six>=1.10 (from matplotlib->multiqc==1.3dev)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting pytz (from matplotlib->multiqc==1.3dev)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting functools32 (from matplotlib->multiqc==1.3dev)
  Using cached functools32-3.2.3-2.zip
Collecting python-dateutil (from matplotlib->multiqc==1.3dev)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting cycler>=0.10 (from matplotlib->multiqc==1.3dev)
  Using cached cycler-0.10.0-py2.py3-none-any.whl
Collecting subprocess32 (from matplotlib->multiqc==1.3dev)
  Using cached subprocess32-3.2.7.tar.gz
Collecting chardet<3.1.0,>=3.0.2 (from requests->multiqc==1.3dev)
  Using cached chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->multiqc==1.3dev)
  Using cached certifi-2017.7.27.1-py2.py3-none-any.whl
Collecting urllib3<1.23,>=1.21.1 (from requests->multiqc==1.3dev)
  Using cached urllib3-1.22-py2.py3-none-any.whl
Collecting idna<2.7,>=2.5 (from requests->multiqc==1.3dev)
  Using cached idna-2.6-py2.py3-none-any.whl
Collecting colormath (from spectra->multiqc==1.3dev)
  Using cached colormath-2.1.1.tar.gz
Collecting decorator>=3.4.0 (from networkx<2->multiqc==1.3dev)
  Using cached decorator-4.1.2-py2.py3-none-any.whl
Building wheels for collected packages: future, markdown, pyyaml, simplejson, spectra, MarkupSafe, functools32, subprocess32, colormath
  Running setup.py bdist_wheel for future ... error
  Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-72DdMz/future/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmplBsdfbpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  **error: invalid command 'bdist_wheel'**
  
  ----------------------------------------
  Failed building wheel for future
  Running setup.py clean for future
  Running setup.py bdist_wheel for markdown ... error
  Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-72DdMz/markdown/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpzIGutLpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for markdown
  Running setup.py clean for markdown
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: /root/.cache/pip/wheels/2c/f7/79/13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for simplejson ... error
  Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-72DdMz/simplejson/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpq0wC3ppip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for simplejson
  Running setup.py clean for simplejson
  Running setup.py bdist_wheel for spectra ... error
  Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-72DdMz/spectra/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpNXgGBBpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for spectra
  Running setup.py clean for spectra
  Running setup.py bdist_wheel for MarkupSafe ... error
  Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-72DdMz/MarkupSafe/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpGfUwZXpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for MarkupSafe
  Running setup.py clean for MarkupSafe
  Running setup.py bdist_wheel for functools32 ... error
  Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-72DdMz/functools32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpiqj5QApip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for functools32
  Running setup.py clean for functools32
  Running setup.py bdist_wheel for subprocess32 ... error
  Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-72DdMz/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpLaLRfvpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for subprocess32
  Running setup.py clean for subprocess32
  Running setup.py bdist_wheel for colormath ... error
  Complete output from command /bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-72DdMz/colormath/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp_T9IUhpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for colormath
  Running setup.py clean for colormath
Successfully built pyyaml
Failed to build future markdown simplejson spectra MarkupSafe functools32 subprocess32 colormath
Installing collected packages: click, future, lzstring, MarkupSafe, jinja2, pyparsing, six, pytz, functools32, python-dateutil, numpy, cycler, subprocess32, matplotlib, markdown, pyyaml, chardet, certifi, urllib3, idna, requests, simplejson, decorator, networkx, colormath, spectra, multiqc
  Found existing installation: click 6.7
    Uninstalling click-6.7:
      Successfully uninstalled click-6.7
  Found existing installation: future 0.16.0
    Uninstalling future-0.16.0:
      Successfully uninstalled future-0.16.0
  Running setup.py install for future ... done
  Found existing installation: lzstring 1.0.3
    Uninstalling lzstring-1.0.3:
      Successfully uninstalled lzstring-1.0.3
  Found existing installation: MarkupSafe 1.0
    Uninstalling MarkupSafe-1.0:
      Successfully uninstalled MarkupSafe-1.0
  Running setup.py install for MarkupSafe ... done
  Found existing installation: Jinja2 2.9.6
    Uninstalling Jinja2-2.9.6:
      Successfully uninstalled Jinja2-2.9.6
  Found existing installation: pyparsing 2.2.0
    Uninstalling pyparsing-2.2.0:
      Successfully uninstalled pyparsing-2.2.0
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: pytz 2017.2
    Uninstalling pytz-2017.2:
      Successfully uninstalled pytz-2017.2
  Found existing installation: functools32 3.2.3.post2
    Uninstalling functools32-3.2.3.post2:
      Successfully uninstalled functools32-3.2.3.post2
  Running setup.py install for functools32 ... done
  Found existing installation: python-dateutil 2.6.1
    Uninstalling python-dateutil-2.6.1:
      Successfully uninstalled python-dateutil-2.6.1
  Found existing installation: numpy 1.13.1
    Uninstalling numpy-1.13.1:
      Successfully uninstalled numpy-1.13.1
  Found existing installation: cycler 0.10.0
    Uninstalling cycler-0.10.0:
      Successfully uninstalled cycler-0.10.0
  Found existing installation: subprocess32 3.2.7
    Uninstalling subprocess32-3.2.7:
      Successfully uninstalled subprocess32-3.2.7
  Running setup.py install for subprocess32 ... done
  Found existing installation: matplotlib 2.0.2
    Uninstalling matplotlib-2.0.2:
      Successfully uninstalled matplotlib-2.0.2
  Found existing installation: Markdown 2.6.9
    Uninstalling Markdown-2.6.9:
      Successfully uninstalled Markdown-2.6.9
  Running setup.py install for markdown ... done
  Found existing installation: PyYAML 3.12
    Uninstalling PyYAML-3.12:
      Successfully uninstalled PyYAML-3.12
  Found existing installation: chardet 3.0.4
    Uninstalling chardet-3.0.4:
      Successfully uninstalled chardet-3.0.4
  Found existing installation: certifi 2017.7.27.1
    Uninstalling certifi-2017.7.27.1:
      Successfully uninstalled certifi-2017.7.27.1
  Found existing installation: urllib3 1.22
    Uninstalling urllib3-1.22:
      Successfully uninstalled urllib3-1.22
  Found existing installation: idna 2.6
    Uninstalling idna-2.6:
      Successfully uninstalled idna-2.6
  Found existing installation: requests 2.18.4
    Uninstalling requests-2.18.4:
      Successfully uninstalled requests-2.18.4
  Found existing installation: simplejson 3.11.1
    Uninstalling simplejson-3.11.1:
      Successfully uninstalled simplejson-3.11.1
  Running setup.py install for simplejson ... done
  Found existing installation: decorator 4.1.2
    Uninstalling decorator-4.1.2:
      Successfully uninstalled decorator-4.1.2
  Found existing installation: networkx 1.11
    Uninstalling networkx-1.11:
      Successfully uninstalled networkx-1.11
  Found existing installation: colormath 2.1.1
    Uninstalling colormath-2.1.1:
      Successfully uninstalled colormath-2.1.1
  Running setup.py install for colormath ... done
  Found existing installation: spectra 0.0.8
    Uninstalling spectra-0.0.8:
      Successfully uninstalled spectra-0.0.8
  Running setup.py install for spectra ... done
  Running setup.py install for multiqc ... done
Successfully installed MarkupSafe-1.0 certifi-2017.7.27.1 chardet-3.0.4 click-6.7 colormath-2.1.1 cycler-0.10.0 decorator-4.1.2 functools32-3.2.3.post2 future-0.16.0 idna-2.6 jinja2-2.9.6 lzstring-1.0.3 markdown-2.6.9 matplotlib-2.0.2 multiqc-1.3.dev0 networkx-1.11 numpy-1.13.1 pyparsing-2.2.0 python-dateutil-2.6.1 pytz-2017.2 pyyaml-3.12 requests-2.18.4 simplejson-3.11.1 six-1.10.0 spectra-0.0.8 subprocess32-3.2.7 urllib3-1.22
```
It seems the `wheel` package was not installed properly(not reported at the first install), so I check the wheel with a install command 
```
$sudo pip install wheel 
Requirement already satisfied: wheel in /usr/lib/python2.7/site-packages
```
I am sorry that I am not familiar with solving python packages  dependencies and I am now really confused by those overlapping installation.
PS: for using multiQC anyway, I installed it into another machine, copy the log files , it works smoothy.

**Comment by ewels** [comment]
> my pip is already up to date

Interesting! We thought that the `networkx<2` incompatibility was due to `pip` versions. I guess it must be something else then (it works fine for most people). Shouldn't matter anyway as we changed this now.

I've not seen the `error: invalid command 'bdist_wheel'` error before, I'm not sure why that would suddenly pop up. If I'm honest, these python package installations seem to either work straight out of the box, or just be impossible. When people have had similar problems in the past the best solution has usually been to install [miniconda](https://conda.io/miniconda.html) and run Python in a conda environment. This nearly always works... (though I appreciate that it can be annoying to have to change setups).

Phil

**Comment by ewels** [comment]
I'll close this issue for now as I'm not sure that I can be much more help. Feel free to comment / reopen though, and let me know if you find any solutions!

Phil

**Comment by likelet** [comment]
Recently, I fix this by replace the current python in my system(2.75) into python 3.7. Since the error was caused by missing dependencies. Some dependencies of MultiQC, such as enum34, is deprecated under python 2.7.x, which may cause problems when running MultiQC. Change the interpreter of python to 3.X (anaconda distribution can fit this job), or set up a virtualenv can solve this problem.

hope this answer can help others 
:)
