### ISSUE TITLE
bug - 1.2 - custom_content - linegraph

### ISSUE THREAD

**Issue by lecorguille** [ewels/MultiQC#618]
**Description of bug:**
It works like a charm with the 1.1 but crash "horribly" (😉 ) with the 1.2

**MultiQC Error log:**
```
Module custom_content raised an exception: Traceback (most recent call last):
  File "/Users/lecorguille/miniconda3/envs/multiqc/lib/python3.6/site-packages/multiqc-1.2-py3.6.egg/EGG-INFO/scripts/multiqc", line 411, in multiqc
    output = mod()
  File "/Users/lecorguille/miniconda3/envs/multiqc/lib/python3.6/site-packages/multiqc-1.2-py3.6.egg/multiqc/modules/custom_content/custom_content.py", line 204, in custom_module_classes
    parsed_modules.append( MultiqcModule(k, mod) )
  File "/Users/lecorguille/miniconda3/envs/multiqc/lib/python3.6/site-packages/multiqc-1.2-py3.6.egg/multiqc/modules/custom_content/custom_content.py", line 248, in __init__
    self.add_section( plot = linegraph.plot(mod['data'], pconfig) )
  File "/Users/lecorguille/miniconda3/envs/multiqc/lib/python3.6/site-packages/multiqc-1.2-py3.6.egg/multiqc/plots/linegraph.py", line 79, in plot
    for k in sorted(d[s].keys()):
TypeError: '<' not supported between instances of 'float' and 'str'

```

* **File that triggers the error:**
    * [cc_ko15-bpc_mqc.out](https://raw.githubusercontent.com/galaxyproject/tools-iuc/master/tools/multiqc/test-data/cc_ko15.bpc.embedded.tab)
    * [cc_wt15-bpc_mqc.out](https://raw.githubusercontent.com/galaxyproject/tools-iuc/master/tools/multiqc/test-data/cc_wt15.bpc.embedded.tab)
* **Command used to run MultiQC**
    * `multiqc .`
* **MultiQC Version:**
    * MultiQC v1.2
* **Operating System:**
    * macOS Sierra 10.12.6
* **Python Version:**
    * Python 3.6.3 :: Anaconda, Inc.
* **Method of MultiQC installation:**
    * conda

**Comment by ewels** [comment]
Hi @lecorguille,

I just tried running your files with v1.3dev and it worked without any problem. As such, I suspect that I've already fixed this bug, whatever it was :)

If you're able to recreate this error with the latest version of MultiQC, please reopen the issue. Otherwise, I'm hoping to release v1.3 today so it should be fixed v. soon.

Phil
