### ISSUE TITLE
Installation difficulties

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#628]
Sent via e-mail:

---

Dear Dr. Ewels:
The installation is not working; see below. Thanks for your asistance. I have no pip, nor conda.

```
[fuy@wpgrhapp002 multiqc-1.3]$ ls
LICENSE      multiqc           PKG-INFO   scripts    setup.py
MANIFEST.in  multiqc.egg-info  README.md  setup.cfg
```
```
[fuy@wpgrhapp002 multiqc-1.3]$ python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    from setuptools import setup, find_packages
ImportError: No module named 'setuptools'
```
```
[fuy@wpgrhapp002 multiqc-1.3]$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    dl_version = 'master' if 'dev' in version else 'v{}'.format(version)
ValueError: zero length field name in format
```
```
[fuy@wpgrhapp002 multiqc-1.3]$ python276 setup.py install
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
```

python=2.6.6, python276=2.7.6, python3=2.4.3. I don't have the root access, so I have to install python and set environment with path to use python.

**Comment by ewels** [comment]
Hi there,

MultiQC doesn't work with python version 2.6.6 (it works with 2.7 onwards), so that explains the one error. The others are because you're missing a Python package called `setuptools`. This is a very core package that is used by most Python software. It is used to install MultiQC and gather all other dependencies (see https://packaging.python.org/tutorials/installing-packages/).

Neither `pip` nor `conda` require root access, so that shouldn't be a problem. Installing without these tools will be very difficult, if not impossible. I'd recommend getting in touch with your server administration to install MultiQC for you (or provide help).

Let me know if I'm able to help any further.

Phil
