### ISSUE TITLE
qorts error

### ISSUE THREAD

**Issue by bankhead3** [ewels/MultiQC#639]
When running MultiQC v1.3 on qorts v1.3.0 I get the following error:

```
multiqc input/pipeline5a-exemplar6 -o multiqc-pipeline5a-exemplar6
[INFO   ]         multiqc : This is MultiQC v1.3
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'input/pipeline5a-exemplar6'
Searching 662 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'qorts' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)
============================================================
Module qorts raised an exception: Traceback (most recent call last):
  File "/sw/lsa/centos7/python-anaconda2/created-20170421b/bin/multiqc", line 412, in multiqc
    output = mod()
  File "/sw/lsa/centos7/python-anaconda2/created-20170421b/lib/python2.7/site-packages/multiqc/modules/qorts/qorts.py", line 29, in __init__
    self.parse_qorts(f)
  File "/sw/lsa/centos7/python-anaconda2/created-20170421b/lib/python2.7/site-packages/multiqc/modules/qorts/qorts.py", line 64, in parse_qorts
    self.qorts_data[s_name][s[0]] = float(s[i+1])
ValueError: could not convert string to float: Code for the strandedness rule used. 0 if data is unstranded, 1 if data is fr_firstStrand, 2 if data is fr_secondStrand.
============================================================
[INFO   ]            star : Found 6 reports
[INFO   ]          fastqc : Found 24 reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc-pipeline5a-exemplar6/multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc-pipeline5a-exemplar6/multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
Thanks @bankhead3 and @royfrancis. Please could one of you attach some QORTs results that trigger this error so that I can replicate and then fix it?

Phil

**Comment by bankhead3** [comment]
[TCGA-E7-A519-1.tar.gz](https://github.com/ewels/MultiQC/files/1543841/TCGA-E7-A519-1.tar.gz)
tar -xvzf TCGA-E7-A519-1.tar.gz
The attached archive contains qorts output that is causing multiqc to error out.
Hope this helps
best,
Armand

**Comment by ewels** [comment]
Thanks @bankhead3! I'll have a look at this when I get a chance..

Phil

**Comment by ewels** [comment]
Hi @bankhead3,

Thanks for the test files - it looks like QoRTs changed the output format a little between v1.2.42 and v1.3.0, which is what broke the module.

I've updated the MultiQC code to handle output from both versions. Let me know if you run into any further problems!

Phil

**Comment by bankhead3** [comment]
Thanks Phil!
