### ISSUE TITLE
'qualimap' MultiQC module bug

### ISSUE THREAD

**Issue by janstrauss1** [ewels/MultiQC#642]
Hi Phil!

I keep receiving an error when I run the qualimap module.

Jan

**Description of bug:**
After running `qualimap bamqc -bam sorted.bam -outdir ./qualimap -outformat HTML` on a single BAM file, I run MultiQC to aggregate the results but get an error.

MultiQC Error log:

```
[WARNING]         multiqc : MultiQC Version v1.3 now available!
[INFO   ]         multiqc : This is MultiQC v1.2
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching './'
Searching 50 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'qualimap' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module qualimap raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 411, in multiqc
    output = mod()
  File "/usr/local/lib/python3.6/site-packages/multiqc/modules/qualimap/qualimap.py", line 40, in __init__
    n['BamQC'] = QM_BamQC.parse_reports(self)
  File "/usr/local/lib/python3.6/site-packages/multiqc/modules/qualimap/QM_BamQC.py", line 58, in parse_reports
    report_sections(self)
  File "/usr/local/lib/python3.6/site-packages/multiqc/modules/qualimap/QM_BamQC.py", line 247, in report_sections
    depth_range.append(int(c))
AttributeError: 'range' object has no attribute 'append'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

Command used to run MultiQC: `multiqc ./`
Operating System: macOS X Yosemite 10.10.5

**Comment by ewels** [comment]
Hi @janstrauss1,

I'm pretty sure that this bug has been fixed in the latest release of MultiQC, so if you grab the latest update you should be fine. Please let me know if this is not the case..

Phil

**Comment by ewels** [comment]
(I'm basing this on the first two lines of your log, which say that you're running v1.2)

```
[WARNING]         multiqc : MultiQC Version v1.3 now available!
[INFO   ]         multiqc : This is MultiQC v1.2
```
