### ISSUE TITLE
multiQC - error with homer module

### ISSUE THREAD

**Issue by venuthatikonda** [ewels/MultiQC#673]
Hi Phil,

I was trying to use `multiQC` with `homer` module. But I got the following error

multiqc version - 1.4
python version - 2.7.3

Here is the command I issued

`/scripts/tools/anaconda3/bin/multiqc tagDir/ -m homer`

```
[INFO   ]         multiqc : This is MultiQC v1.4
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching 'tagDir/'
[INFO   ]         multiqc : Only using modules homer
Searching 29 files..  [####################################]  100%
[ERROR  ]         multiqc : Oops! The 'homer' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    tagDir/tagInfo.txt
============================================================
Module homer raised an exception: Traceback (most recent call last):
  File "/scripts/tools/anaconda3/bin/multiqc", line 427, in multiqc
    output = mod()
  File "/scripts/tools/anaconda3/lib/python3.6/site-packages/multiqc/modules/homer/homer.py", line 60, in __init__
    n['Homer_tagDir'] = self.homer_tagdirectory()
  File "/scripts/tools/anaconda3/lib/python3.6/site-packages/multiqc/modules/homer/tagdirectory.py", line 24, in homer_tagdirectory
    self.parse_tagInfo_data()
  File "/scripts/tools/anaconda3/lib/python3.6/site-packages/multiqc/modules/homer/tagdirectory.py", line 142, in parse_tagInfo_data
    parsed_data = self.parse_tag_info(f)
  File "/scripts/tools/anaconda3/lib/python3.6/site-packages/multiqc/modules/homer/tagdirectory.py", line 349, in parse_tag_info
    tag_info['gsizeEstimate'] = float(s[0].strip().split("=")[1])
IndexError: list index out of range
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

```

**Comment by ewels** [comment]
Hi @venuthatikonda,

Yes, this is due to an update in the Homer output. See #666

I'm short on time currently, so it may be some time before I get to fixing this sorry.

Phil
