### ISSUE TITLE
 The 'htseq' MultiQC module broke

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [ewels/MultiQC#688]
Here I report th error 
```
[WARNING]         multiqc : MultiQC Version v1.4 now available!
[INFO   ]         multiqc : This is MultiQC v0.9.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[ERROR  ]         multiqc : Oops! The 'htseq' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module htseq raised an exception: Traceback (most recent call last):
  File "/home/centos/illumina/ANALISI/.snakemake/conda/85d2b37a/lib/python3.5/site-packages/multiqc-0.9.dev0-py3.5.egg/EGG-INFO/scripts/multiqc", line 344, in multiqc
    output = mod()
  File "/home/centos/illumina/ANALISI/.snakemake/conda/85d2b37a/lib/python3.5/site-packages/multiqc-0.9.dev0-py3.5.egg/multiqc/modules/htseq/htseq.py", line 29, in __init__
    parsed_data = self.parse_htseq_report(f)
  File "/home/centos/illumina/ANALISI/.snakemake/conda/85d2b37a/lib/python3.5/site-packages/multiqc-0.9.dev0-py3.5.egg/multiqc/modules/htseq/htseq.py", line 60, in parse_htseq_report
    assigned_counts += int(s[1])
IndexError: list index out of range
```

**Comment by ewels** [comment]
Hi @bioinfo-dirty-jobs,

You're running a really old version of MultiQC - v0.9 was released back in [December 2016](https://github.com/ewels/MultiQC/releases). A lot has changed since then, and there's a good chance that the bug you've encountered has been fixed (the changelogs show bugfixes for the htseq module in the v1.0 and v1.1 releases at least).

If you could please update your version of MultiQC to the latest version and try again, that would be great. If you still get the error I'll reopen the issue and look into it.

Phil
