### ISSUE TITLE
Error with QUAST module

### ISSUE THREAD

**Issue by KevinMenden** [ewels/MultiQC#719]
Hi Phil,

I'm running MultiQC with QUAST, and after it has been working, it now broke for a new test dataset.

I made some debugging and the reason seems to be that QUAST reports '-' instead of zeros in the 'report.tsv' file (in my case, for 'final_scaffolds_broken' there were '-' in two places). I substituted those with zeros and it worked.
I feel like this is something that should be ultimately changed in QUAST but for now it can lead to problems in some rare cases so I report it here.

Thank you!
Kevin

**MultiQC Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.5
============================================================
Module quast raised an exception: Traceback (most recent call last):
  File "/home/kevin/anaconda3/envs/assembly-env/bin/multiqc", line 442, in multiqc
    output = mod()
  File "/home/kevin/anaconda3/envs/assembly-env/lib/python2.7/site-packages/multiqc/modules/quast/quast.py", line 72, in __init__
    plot = self.quast_contigs_barplot()
  File "/home/kevin/anaconda3/envs/assembly-env/lib/python2.7/site-packages/multiqc/modules/quast/quast.py", line 279, in quast_contigs_barplot
    p[c] = nums_by_t[t] - nums_by_t[tresholds[i - 1]]
TypeError: unsupported operand type(s) for -: 'unicode' and 'float'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

* **File that triggers the error:**
    * [[latest.zip](https://github.com/ewels/MultiQC/files/1876138/latest.zip)]
* **Command used to run MultiQC**
    * `multiqc .`
* **MultiQC Version:**
    *  [MultiQC v1.5]
* **QUAST Version:**
   * [QUAST v4.6.3]
* **Operating System:**
    * [Ubuntu 16.04]
* **Python Version:**
    * [Python 2.7.14]
* **Method of MultiQC installation:**
    * [conda]

**Comment by ewels** [comment]
Thanks for this @KevinMenden - sounds like something that MultiQC should be able to handle fairly easily.

@vladsaveliev - any input on this?

**Comment by vladsaveliev** [comment]
Hi Kevin, thanks for the report. It is definitely something we need to fix. Dashes - placeholders for null values - can be handled in the MultiQC module, however if there is something wrong with QUAST analysis too, we need to fix that too. I can't open your archive `latest.zip` however - it doesn't decompress for me, neither by MacOS finder not in command line on a linux machine: ```
unzip latest.zip
Archive:  latest.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of latest.zip or
        latest.zip.zip, and cannot find latest.zip.ZIP, period.
```

Can you please take a look if it decompresses for you without issues? It it does, would you be able to create a tarball by any chance (`tar -czf quast_results.tar.gz quast_results`)?

Vlad

**Comment by KevinMenden** [comment]
Hi Vlad,

sorry for that! Here's the tarball:
[quast_results.tar.gz](https://github.com/ewels/MultiQC/files/1878849/quast_results.tar.gz)

Btw, the error occured when using QUAST with the --scaffolds option and then only using scaffolds as input. It creates the 'scaffolds_broken' column in the report, and this is where the dashes occur. I thought that for smaller contig thresholds the number of contigs should always be bigger than for larger thresholds, but maybe I just didn't quite get it.

Thank you!

Kevin

**Comment by vladsaveliev** [comment]
You are absolutely right! Just walked through the code and indeed for scaffolds, we skip reporting counts within thresholds for thresholds above min contig: https://github.com/ablab/quast/commit/111b865b803045811955fd16ed4f5477872809f7

Will talk with other authors why it's done for scaffolds specifically, but skipping lines with dashes in MultiQC should fix the problem - will test now!
