### ISSUE TITLE
bismark MultiQC module broke when dedup logs not found

### ISSUE THREAD

**Issue by avilella** [ewels/MultiQC#75]
I am running it on a directory where deduplicate_bismark was not executed, but bismark with bowtie2 was executed. I think it freaks out because it expects data to be there for the dedup_reads part.

```
[INFO   ]         multiqc : Working dir : /media/sf_Downloads/CEGX_Run110-25500479
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching   : .
[INFO   ]         multiqc : Saving to   : multiqc_report.html
[INFO   ]         bismark : Found 16 reports
[ERROR  ]         multiqc : Oops! The 'bismark' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 
============================================================
Module bismark raised an exception: Traceback (most recent call last):
  File "/home/avilella/MultiQC/scripts/multiqc", line 201, in multiqc
    report.modules_output.append(mod.MultiqcModule())
  File "/home/avilella/.local/lib/python2.7/site-packages/multiqc/modules/bismark/bismark.py", line 132, in __init__
    self.bismark_stats_table()
  File "/home/avilella/.local/lib/python2.7/site-packages/multiqc/modules/bismark/bismark.py", line 221, in bismark_stats_table
    self.general_stats_addcols(self.bismark_data['merged'], headers)
  File "/home/avilella/.local/lib/python2.7/site-packages/multiqc/modules/base_module.py", line 185, in general_stats_addcols
    val = float(samp[k])
KeyError: 'dedup_reads'
============================================================
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete
```

**Comment by ewels** [comment]
Ah ok, thanks for reporting - when I originally wrote the module I did it with the intention that any of the reports could be missing. But I've pretty much completely rewritten it since then so I must have broken that at some point. I'll look into it..

**Comment by ewels** [comment]
Should be fixed now @avilella - let me know if you run into any trouble!

**Comment by avilella** [comment]
I just tried it and it did fix it for me. Can close ticket :-)

**Comment by ewels** [comment]
Hah, great! Top marks on the fast response ;)
