### ISSUE TITLE
Oops! The 'star' MultiQC module broke...

### ISSUE THREAD

**Issue by annaquaglieri16** [ewels/MultiQC#754]
Hi there, 

I got the following error message and it suggests to report it here. 

```
multiqc ${star_2pass} -n 'CD34_hg38_leucegene_STAR_2pass' -o ${star_2pass} --interactive -f

[INFO   ]         multiqc : This is MultiQC v0.8.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '/wehisan/general/user_managed/grpu_majewski_3/quaglieri.a/GEO_Leucegene_data/GRCh38_aligned/STAR_2pass_CD34'
[INFO   ]  feature_counts : Found 17 reports
[INFO   ]          picard : Found 17 InsertSizeMetrics reports
[INFO   ]          picard : Found 34 BaseDistributionByCycleMetrics reports
[ERROR  ]         multiqc : Oops! The 'star' MultiQC module broke...
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
                    (if possible, include a log file that triggers the error)

Module star raised an exception: Traceback (most recent call last):
  File "/usr/local/bioinfsoftware/python/current/bin/multiqc", line 345, in multiqc
    report.modules_output.append(mod())
  File "/home/users/allstaff/quaglieri.a/.local/lib/python2.7/site-packages/multiqc-0.8.dev0-py2.7.egg/multiqc/modules/star/star.py", line 27, in __init__
    parsed_data = self.parse_star_report(f['f'])
  File "/home/users/allstaff/quaglieri.a/.local/lib/python2.7/site-packages/multiqc-0.8.dev0-py2.7.egg/multiqc/modules/star/star.py", line 88, in parse_star_report
    parsed_data['unmapped_mismatches'] = int(round(unmapped_count * (parsed_data['unmapped_mismatches_percent'] / total_unmapped_percent), 0))
ZeroDivisionError: float division by zero

[WARNING]         multiqc : Deleting    : CD34_hg38_leucegene_STAR_2pass.html   (-f was specified)
[INFO   ]         multiqc : Report      : CD34_hg38_leucegene_STAR_2pass.html
[WARNING]         multiqc : Deleting    : CD34_hg38_leucegene_STAR_2pass_data   (-f was specified)
[INFO   ]         multiqc : Data        : CD34_hg38_leucegene_STAR_2pass_data
[INFO   ]         multiqc : MultiQC complete
```

Let me know if you've seen this already!

Thanks!!

Anna

**Comment by ewels** [comment]
Hi @annaquaglieri16,

You're using MultiQC `v0.8.dev0` here which is really old - it's the pre-release code for the version that shipped in September 2016.

After a little bit of digging it looks like I fixed this error on the 13th Oct 2016 - see https://github.com/ewels/MultiQC/issues/316#issuecomment-253420343 and d2dc0b67fb2475204f343752cc2520b4a4164ab6

Hopefully if you update MultiQC it should go away, plus you'll get a tonne of new modules and features 😀 

I'll close this for now, but let me know how you get on and if you encounter any problems.

Cheers,

Phil

**Comment by annaquaglieri16** [comment]
Thanks! I am sorry, I was just using the latest update available on the Institute's servers. So I need to ask for updates!!

Thanks for this, 

Anna

**Comment by ewels** [comment]
No problem :) Let me know if there's anything else I can help with.
