### ISSUE TITLE
'htseq' , 'slamdunk' MultiQC module broke

### ISSUE THREAD

**Issue by pbrazda** [ewels/MultiQC#818]
**MultiQC Error log:**
```
multiqc : Oops! The 'htseq' MultiQC module broke... 
multiqc : Oops! The 'slamdunk' MultiQC module broke... 
```

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: `multiqc .`
 - MultiQC Version: MultiQC v1.0.dev0
 - Operating System: macOS Sierra 10.13.6
 - Python Version: Python 2.7.15 
 - Method of MultiQC installation: conda 4.5.4

 **Additional context**
```
[INFO   ]         multiqc : This is MultiQC v1.0.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Fontconfig warning: ignoring UTF-8: not a valid region tag
[ERROR  ]         multiqc : Oops! The 'htseq' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 

Module htseq raised an exception: Traceback (most recent call last):
  File "/Users/peterbrazda/miniconda2/envs/py2.7/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/Users/peterbrazda/miniconda2/envs/py2.7/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/htseq/htseq.py", line 31, in __init__
    parsed_data = self.parse_htseq_report(f)
  File "/Users/peterbrazda/miniconda2/envs/py2.7/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/htseq/htseq.py", line 62, in parse_htseq_report
    assigned_counts += int(s[1])
IndexError: list index out of range

[INFO   ]        samtools : Found 1 rmdup reports
[ERROR  ]         multiqc : Oops! The 'slamdunk' MultiQC module broke... 
                    Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
                    (if possible, include a log file that triggers the error) 

Module slamdunk raised an exception: Traceback (most recent call last):
  File "/Users/peterbrazda/miniconda2/envs/py2.7/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/EGG-INFO/scripts/multiqc", line 346, in multiqc
    output = mod()
  File "/Users/peterbrazda/miniconda2/envs/py2.7/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/slamdunk/slamdunk.py", line 42, in __init__
    self.parseSummary(f)
  File "/Users/peterbrazda/miniconda2/envs/py2.7/lib/python2.7/site-packages/multiqc-1.0.dev0-py2.7.egg/multiqc/modules/slamdunk/slamdunk.py", line 295, in parseSummary
    self.slamdunk_data[s_name]['sequenced'] = int(fields[4])
IndexError: list index out of range

[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```
(py2.7)

**Comment by ewels** [comment]
Hi @pbrazda,

Thanks for reporting this. Do you have some example files that I could use to reproduce the error please?

Phil

**Comment by ewels** [comment]
Hi @pbrazda,

If you can send some example data so that I can replicate this error that would be great. It's pretty difficult to implement any fixes without that (or at least, to be sure that the fix worked!).

Cheers,

Phil

**Comment by ewels** [comment]
Closing this issue now as I can't replicate the error. Happy to reopen if there is an example that I can work with.
