### ISSUE TITLE
adapterRemoval doesn't handle invalid files well

### ISSUE THREAD

**Issue by ewels** [ewels/MultiQC#824]
Taken from #823 - adapterRemoval fails with a `KeyError` exception when it tries to parse files which are not really from the tool (the [search pattern](https://github.com/ewels/MultiQC/blob/56d2b69a1b68b65b3ff70b4e2b5f87010d80fef2/multiqc/utils/search_patterns.yaml#L5-L8) is relatively generic).

```python
Module adapterRemoval raised an exception: Traceback (most recent call last):
  File "/data/anaconda3/envs/env/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/data/anaconda3/envs/env/lib/python3.6/site-packages/multiqc/modules/adapterRemoval/adapterRemoval.py", line 47, in __init__
    parsed_data = self.parse_settings_file(f)
  File "/data/anaconda3/envs/env/lib/python3.6/site-packages/multiqc/modules/adapterRemoval/adapterRemoval.py", line 103, in parse_settings_file
    self.set_result_data(settings_data)
  File "/data/anaconda3/envs/env/lib/python3.6/site-packages/multiqc/modules/adapterRemoval/adapterRemoval.py", line 109, in set_result_data
    self.set_ar_type(settings_data['Length distribution'])
KeyError: 'Length distribution'
```

**Comment by ewels** [comment]
The search settings are pretty strict actually: filename and requiring `AdapterRemoval` in the first line. Given that the parsing code for Adapter Removal is kind of strange, there are actually a bunch of ways this can fail. I'm not sure that a generic catch-all is the right solution for now.
