### ISSUE TITLE
FastQC - zipfile.BadZipFile: Bad magic number for file header

### ISSUE THREAD

**Issue by joefaa** [ewels/MultiQC#943]
Hello. I got an error trying to summarize some fastqc output files. They were created with fastqc version 0.11.7.

Is it possible that the problem was cause because I am running python 3.7? Or maybe that there are some output files named the same way since the fastq files were produced by two illumina runs?

```console
bluebird:fastqc j_casano$ multiqc .
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./51_S51_L003_R1_001_fastqc.zip
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/multiqc/modules/fastqc/fastqc.py", line 64, in __init__
    with fqc_zip.open(os.path.join(d_name, 'fastqc_data.txt')) as fh:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1488, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header
============================================================
/Library/Frameworks/Python.framework/Versions/3.7/bin/multiqc:495: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("No analysis results found. Cleaning up..")
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

```
This is an example of a file that created the error.
[51_S51_L003_R1_001_fastqc.zip](https://github.com/ewels/MultiQC/files/3038936/51_S51_L003_R1_001_fastqc.zip)

This is the directory with the fastqc outputs.

```console
bluebird:fastqc j_casano$ ls
29_S29_L001_R1_001_fastqc.html	51_S51_L002_R1_001_fastqc.html	53_S53_L004_R2_001_fastqc.html
29_S29_L001_R1_001_fastqc.zip	51_S51_L002_R1_001_fastqc.zip	53_S53_L004_R2_001_fastqc.zip
29_S29_L001_R2_001_fastqc.html	51_S51_L002_R2_001_fastqc.html	53_S53_L005_R1_001_fastqc.html
29_S29_L001_R2_001_fastqc.zip	51_S51_L002_R2_001_fastqc.zip	53_S53_L005_R1_001_fastqc.zip
29_S29_L002_R1_001_fastqc.html	51_S51_L003_R1_001_fastqc.html	53_S53_L005_R2_001_fastqc.html
29_S29_L002_R1_001_fastqc.zip	51_S51_L003_R1_001_fastqc.zip	53_S53_L005_R2_001_fastqc.zip
49_S49_L001_R1_001_fastqc.html	51_S51_L003_R2_001_fastqc.html	53_S53_L006_R1_001_fastqc.html
49_S49_L001_R1_001_fastqc.zip	51_S51_L003_R2_001_fastqc.zip	53_S53_L006_R1_001_fastqc.zip
49_S49_L001_R2_001_fastqc.html	51_S51_L004_R1_001_fastqc.html	53_S53_L006_R2_001_fastqc.html
49_S49_L001_R2_001_fastqc.zip	51_S51_L004_R1_001_fastqc.zip	53_S53_L006_R2_001_fastqc.zip
49_S49_L002_R1_001_fastqc.html	51_S51_L004_R2_001_fastqc.html	53_S53_L007_R1_001_fastqc.html
49_S49_L002_R1_001_fastqc.zip	51_S51_L004_R2_001_fastqc.zip	53_S53_L007_R1_001_fastqc.zip
49_S49_L002_R2_001_fastqc.html	51_S51_L005_R1_001_fastqc.html	53_S53_L007_R2_001_fastqc.html
49_S49_L002_R2_001_fastqc.zip	51_S51_L005_R1_001_fastqc.zip	53_S53_L007_R2_001_fastqc.zip
49_S49_L003_R1_001_fastqc.html	51_S51_L005_R2_001_fastqc.html	53_S53_L008_R1_001_fastqc.html
49_S49_L003_R1_001_fastqc.zip	51_S51_L005_R2_001_fastqc.zip	53_S53_L008_R1_001_fastqc.zip
49_S49_L003_R2_001_fastqc.html	51_S51_L006_R1_001_fastqc.html	53_S53_L008_R2_001_fastqc.html
49_S49_L003_R2_001_fastqc.zip	51_S51_L006_R1_001_fastqc.zip	53_S53_L008_R2_001_fastqc.zip
49_S49_L004_R1_001_fastqc.html	51_S51_L006_R2_001_fastqc.html	5_S5_L001_R2_001_fastqc.html
49_S49_L004_R1_001_fastqc.zip	51_S51_L006_R2_001_fastqc.zip	5_S5_L001_R2_001_fastqc.zip
49_S49_L004_R2_001_fastqc.html	51_S51_L007_R1_001_fastqc.html	5_S5_L002_R1_001_fastqc.html
49_S49_L004_R2_001_fastqc.zip	51_S51_L007_R1_001_fastqc.zip	5_S5_L002_R1_001_fastqc.zip
49_S49_L005_R1_001_fastqc.html	51_S51_L007_R2_001_fastqc.html	5_S5_L002_R2_001_fastqc.html
49_S49_L005_R1_001_fastqc.zip	51_S51_L007_R2_001_fastqc.zip	5_S5_L002_R2_001_fastqc.zip
49_S49_L005_R2_001_fastqc.html	51_S51_L008_R1_001_fastqc.html	5_S5_L003_R1_001_fastqc.html
49_S49_L005_R2_001_fastqc.zip	51_S51_L008_R1_001_fastqc.zip	5_S5_L003_R1_001_fastqc.zip
49_S49_L006_R1_001_fastqc.html	51_S51_L008_R2_001_fastqc.html	5_S5_L003_R2_001_fastqc.html
49_S49_L006_R1_001_fastqc.zip	51_S51_L008_R2_001_fastqc.zip	5_S5_L003_R2_001_fastqc.zip
49_S49_L006_R2_001_fastqc.html	52_S52_L001_R1_001_fastqc.html	5_S5_L004_R1_001_fastqc.html
49_S49_L006_R2_001_fastqc.zip	52_S52_L001_R1_001_fastqc.zip	5_S5_L004_R1_001_fastqc.zip
49_S49_L007_R1_001_fastqc.html	52_S52_L001_R2_001_fastqc.html	5_S5_L004_R2_001_fastqc.html
49_S49_L007_R1_001_fastqc.zip	52_S52_L001_R2_001_fastqc.zip	5_S5_L004_R2_001_fastqc.zip
49_S49_L007_R2_001_fastqc.html	52_S52_L002_R1_001_fastqc.html	5_S5_L005_R1_001_fastqc.html
49_S49_L007_R2_001_fastqc.zip	52_S52_L002_R1_001_fastqc.zip	5_S5_L005_R1_001_fastqc.zip
49_S49_L008_R1_001_fastqc.html	52_S52_L002_R2_001_fastqc.html	5_S5_L005_R2_001_fastqc.html
49_S49_L008_R1_001_fastqc.zip	52_S52_L002_R2_001_fastqc.zip	5_S5_L005_R2_001_fastqc.zip
49_S49_L008_R2_001_fastqc.html	52_S52_L003_R1_001_fastqc.html	5_S5_L006_R1_001_fastqc.html
49_S49_L008_R2_001_fastqc.zip	52_S52_L003_R1_001_fastqc.zip	5_S5_L006_R1_001_fastqc.zip
50_S50_L001_R1_001_fastqc.html	52_S52_L003_R2_001_fastqc.html	5_S5_L006_R2_001_fastqc.html
50_S50_L001_R1_001_fastqc.zip	52_S52_L003_R2_001_fastqc.zip	5_S5_L006_R2_001_fastqc.zip
50_S50_L001_R2_001_fastqc.html	52_S52_L004_R1_001_fastqc.html	96_S94_L001_R1_001_fastqc.html
50_S50_L001_R2_001_fastqc.zip	52_S52_L004_R1_001_fastqc.zip	96_S94_L001_R1_001_fastqc.zip
50_S50_L002_R1_001_fastqc.html	52_S52_L004_R2_001_fastqc.html	96_S94_L001_R2_001_fastqc.html
50_S50_L002_R1_001_fastqc.zip	52_S52_L004_R2_001_fastqc.zip	96_S94_L001_R2_001_fastqc.zip
50_S50_L002_R2_001_fastqc.html	52_S52_L005_R1_001_fastqc.html	96_S94_L002_R1_001_fastqc.html
50_S50_L002_R2_001_fastqc.zip	52_S52_L005_R1_001_fastqc.zip	96_S94_L002_R1_001_fastqc.zip
50_S50_L003_R1_001_fastqc.html	52_S52_L005_R2_001_fastqc.html	96_S94_L002_R2_001_fastqc.html
50_S50_L003_R1_001_fastqc.zip	52_S52_L005_R2_001_fastqc.zip	96_S94_L002_R2_001_fastqc.zip
50_S50_L003_R2_001_fastqc.html	52_S52_L006_R1_001_fastqc.html	96_S94_L003_R1_001_fastqc.html
50_S50_L003_R2_001_fastqc.zip	52_S52_L006_R1_001_fastqc.zip	96_S94_L003_R1_001_fastqc.zip
50_S50_L004_R1_001_fastqc.html	52_S52_L006_R2_001_fastqc.html	96_S94_L003_R2_001_fastqc.html
50_S50_L004_R1_001_fastqc.zip	52_S52_L006_R2_001_fastqc.zip	96_S94_L003_R2_001_fastqc.zip
50_S50_L004_R2_001_fastqc.html	52_S52_L007_R1_001_fastqc.html	96_S94_L004_R1_001_fastqc.html
50_S50_L004_R2_001_fastqc.zip	52_S52_L007_R1_001_fastqc.zip	96_S94_L004_R1_001_fastqc.zip
50_S50_L005_R1_001_fastqc.html	52_S52_L007_R2_001_fastqc.html	96_S94_L004_R2_001_fastqc.html
50_S50_L005_R1_001_fastqc.zip	52_S52_L007_R2_001_fastqc.zip	96_S94_L004_R2_001_fastqc.zip
50_S50_L005_R2_001_fastqc.html	52_S52_L008_R1_001_fastqc.html	96_S94_L005_R1_001_fastqc.html
50_S50_L005_R2_001_fastqc.zip	52_S52_L008_R1_001_fastqc.zip	96_S94_L005_R1_001_fastqc.zip
50_S50_L006_R1_001_fastqc.html	52_S52_L008_R2_001_fastqc.html	96_S94_L005_R2_001_fastqc.html
50_S50_L006_R1_001_fastqc.zip	52_S52_L008_R2_001_fastqc.zip	96_S94_L005_R2_001_fastqc.zip
50_S50_L006_R2_001_fastqc.html	53_S53_L001_R1_001_fastqc.html	96_S94_L006_R1_001_fastqc.html
50_S50_L006_R2_001_fastqc.zip	53_S53_L001_R1_001_fastqc.zip	96_S94_L006_R1_001_fastqc.zip
50_S50_L007_R1_001_fastqc.html	53_S53_L001_R2_001_fastqc.html	96_S94_L006_R2_001_fastqc.html
50_S50_L007_R1_001_fastqc.zip	53_S53_L001_R2_001_fastqc.zip	96_S94_L006_R2_001_fastqc.zip
50_S50_L007_R2_001_fastqc.html	53_S53_L002_R1_001_fastqc.html	96_S94_L007_R1_001_fastqc.html
50_S50_L007_R2_001_fastqc.zip	53_S53_L002_R1_001_fastqc.zip	96_S94_L007_R1_001_fastqc.zip
50_S50_L008_R1_001_fastqc.html	53_S53_L002_R2_001_fastqc.html	96_S94_L007_R2_001_fastqc.html
50_S50_L008_R1_001_fastqc.zip	53_S53_L002_R2_001_fastqc.zip	96_S94_L007_R2_001_fastqc.zip
50_S50_L008_R2_001_fastqc.html	53_S53_L003_R1_001_fastqc.html	96_S94_L008_R1_001_fastqc.html
50_S50_L008_R2_001_fastqc.zip	53_S53_L003_R1_001_fastqc.zip	96_S94_L008_R1_001_fastqc.zip
51_S51_L001_R1_001_fastqc.html	53_S53_L003_R2_001_fastqc.html	96_S94_L008_R2_001_fastqc.html
51_S51_L001_R1_001_fastqc.zip	53_S53_L003_R2_001_fastqc.zip	96_S94_L008_R2_001_fastqc.zip
51_S51_L001_R2_001_fastqc.html	53_S53_L004_R1_001_fastqc.html	fastqc.slurm
51_S51_L001_R2_001_fastqc.zip	53_S53_L004_R1_001_fastqc.zip	fibroblast_qc.sh
```

Any ideas?

Thank you!

**Comment by ewels** [comment]
Hi @joefaa,

Is MultiQC always having problems with just that Zip file, or all zip files from FastQC? Was the file created by FastQC, or was it manually zipped afterwards? Looking at google results for the Python error (`zipfile.BadZipFile: Bad magic number for file header`), the most common problems are that the file was compressed with WinRAR or other tools (eg. [this SO post](https://stackoverflow.com/questions/7703639/bad-magic-number-error-with-zipfile-module-in-python#comment9381231_7705133)).

When I test the file locally, I get the same error. When I extract it and recompress it as a zip file again using Mac OSX it works fine.

Phil

**Comment by joefaa** [comment]
Thank you for your reply Phil,

Those zip file are right from fastqc. So I did some more testing with your reply in mind and to me it looks like something is wrong with some of the output files. Its strange because I submitted all of those fastqc jobs at once with a script.

Anyway first, I ran it on a single zip file from that directory and it produced a report. Then I tried to run it on a subset of the files in that directory and it failed.
```
bluebird:fastqc j_casano$ multiqc 96*zip
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/multiqc/utils/config.py:45: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  configs = yaml.load(f)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/multiqc/utils/config.py:51: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  sp = yaml.load(f)
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '96_S94_L001_R1_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L001_R2_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L002_R1_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L002_R2_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L003_R1_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L003_R2_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L004_R1_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L004_R2_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L005_R1_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L005_R2_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L006_R1_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L006_R2_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L007_R1_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L007_R2_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L008_R1_001_fastqc.zip'
[INFO   ]         multiqc : Searching '96_S94_L008_R2_001_fastqc.zip'
[ERROR  ]         multiqc : Oops! The 'fastqc' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    96_S94_L004_R2_001_fastqc.zip
============================================================
Module fastqc raised an exception: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/multiqc/modules/fastqc/fastqc.py", line 64, in __init__
    with fqc_zip.open(os.path.join(d_name, 'fastqc_data.txt')) as fh:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1488, in open
    raise BadZipFile("Bad magic number for file header")
zipfile.BadZipFile: Bad magic number for file header
============================================================
/Library/Frameworks/Python.framework/Versions/3.7/bin/multiqc:495: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("No analysis results found. Cleaning up..")
[WARNING]         multiqc : No analysis results found. Cleaning up..
[INFO   ]         multiqc : MultiQC complete

```
Then I tried to subset it further to exclude the file that made it fail and it worked. Both of the following worked perfectly.
```
bluebird:fastqc j_casano$ multiqc 96*L00{1..3}*zip
bluebird:fastqc j_casano$ multiqc 96*L00{5..8}*zip
```
Thank you for your help Phil! I'm going to try to figure out what happened with those files.

**Comment by ewels** [comment]
Ok great, glad you got it working in the end! I guess we can chalk this one up to _"that was weird"_ - hopefully it won't happen again...!

Shout if it becomes a recurring problem, or you figure out a pattern.

Phil
