### ISSUE TITLE
Oops! The 'gatk' MultiQC module broke

### ISSUE THREAD

**Issue by catalinaguilar** [ewels/MultiQC#950]
```
[INFO   ]         multiqc : This is MultiQC v1.8.dev0
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Searching '.'
Searching 761 files..  [####################################]  100%          
[ERROR  ]         multiqc : Oops! The 'gatk' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    ./build/lib/multiqc/modules/gatk/varianteval.py
============================================================
Module gatk raised an exception: Traceback (most recent call last):
  File "/Users/catalina.aguilar/miniconda3/lib/python3.6/site-packages/multiqc-1.8.dev0-py3.6.egg/EGG-INFO/scripts/multiqc", line 440, in multiqc
    output = mod()
  File "/Users/catalina.aguilar/miniconda3/lib/python3.6/site-packages/multiqc-1.8.dev0-py3.6.egg/multiqc/modules/gatk/gatk.py", line 41, in __init__
    n_reports_found += self.parse_gatk_varianteval()
  File "/Users/catalina.aguilar/miniconda3/lib/python3.6/site-packages/multiqc-1.8.dev0-py3.6.egg/multiqc/modules/gatk/varianteval.py", line 20, in parse_gatk_varianteval
    parsed_data = parse_single_report(f['f'])
  File "/Users/catalina.aguilar/miniconda3/lib/python3.6/site-packages/multiqc-1.8.dev0-py3.6.egg/multiqc/modules/gatk/varianteval.py", line 106, in parse_single_report
    d[headers[i]] = s
IndexError: list index out of range
============================================================
[INFO   ]          picard : Found 1 ValidateSamFile reports
[INFO   ]        samtools : Found 1 rmdup reports
[INFO   ]         multiqc : Compressing plot data
[INFO   ]         multiqc : Report      : multiqc_report.html
[INFO   ]         multiqc : Data        : multiqc_data
[INFO   ]         multiqc : MultiQC complete
```

**Comment by catalinaguilar** [comment]
I was doing something wrong. Now it works, but not sure how to delete the issue.
Thanks

**Comment by ewels** [comment]
No problem, thanks @catalinaguilar 👍 I'll close the issue now.

If it's not super random, it could be nice to know what the problem was, for future googlers..

**Comment by xiwechen** [comment]
> I was doing something wrong. Now it works, but not sure how to delete the issue.
> Thanks

Hi @catalinaguilar , 
Could you tell me how you fixed this? I got the same issue...
Thanks!

**Comment by ewels** [comment]
x-ref https://github.com/ewels/MultiQC/issues/961

**Comment by catalinaguilar** [comment]
I think my problem was understanding what I needed to input. But I am sorry I tried a couple of things and can't really remember what I did.
