### ISSUE TITLE
Quast report parsing failure

### ISSUE THREAD

**Issue by jamesabbott** [ewels/MultiQC#954]
**Description of bug:**
MultiQC dies when trying to parse a quast output. Quast was run with the following commandline:

```
quast $TMPDIR/scaffolds.fasta -o $TMPDIR/quast -r $TMPDIR/$REF
 --threads 16 --glimmer -k -s --circos -a one --plots-format png --pe1 $TMPDIR/$FQ1 --pe2 $TMPDIR/$FQ2
```

**MultiQC Error log:**
```
[INFO   ]         multiqc : This is MultiQC v1.7
[INFO   ]         multiqc : Template    : default
[INFO   ]         multiqc : Prepending directory to sample names
[INFO   ]         multiqc : Searching 'outputs'
[INFO   ]         multiqc : Only using modules quast
[INFO   ]           quast : Found 16 reports
[ERROR  ]         multiqc : Oops! The 'quast' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    outputs/NRS6065/quast/report.tsv
============================================================
Module quast raised an exception: Traceback (most recent call last):
  File "/homes/jabbott/NSW_assembly/.snakemake/conda/a820f7a0/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/homes/jabbott/NSW_assembly/.snakemake/conda/a820f7a0/lib/python3.6/site-packages/multiqc/modules/quast/quast.py", line 75, in __init__
    ng_pdata = self.quast_predicted_genes_barplot()
  File "/homes/jabbott/NSW_assembly/.snakemake/conda/a820f7a0/lib/python3.6/site-packages/multiqc/modules/quast/quast.py", line 305, in quast_predicted_genes_barplot
    for _, d in self.quast_data.items()
  File "/homes/jabbott/NSW_assembly/.snakemake/conda/a820f7a0/lib/python3.6/site-packages/multiqc/modules/quast/quast.py", line 307, in <listcomp>
    if key.startswith(prefix)
ValueError: invalid literal for int() with base 10: '0 bp)_par'
============================================================
```

**File that triggers the error:**
report.tsv uploaded as report.txt since github didn't like the extension....
[report.txt](https://github.com/ewels/MultiQC/files/3091441/report.txt)

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC:  `multiqc -d -m quast -o outputs/multiqc outputs`
 - MultiQC Version: MultiQC v1.7
 - Operating System: CentOS release 6.10 (Final)
 - Python Version: Python 3.6.7
 - Method of MultiQC installation: conda

 **Additional context**

**Comment by ewels** [comment]
Pinging @vladsaveliev 🆘

**Comment by vladsaveliev** [comment]
My apologies for missing this, for some reason I wasn't getting any notifications from MultiQC repo.

Fixed now with https://github.com/ewels/MultiQC/pull/965

We didn't hit it before because we didn't have a test case with both a predicted genes section and partial predictions, like:

``
# predicted genes (>= 300 bp)   2670 + 0 part   2665 + 3 part
```

I added @jamesabbott's test case into MultiQC_TestData now.
