### ISSUE TITLE
Oops! The 'fastqc' MultiQC module broke.

### ISSUE THREAD

**Issue by erikagedvilaite** [ewels/MultiQC#959]
```python
Module fastqc raised an exception: Traceback (most recent call last):
  File "/ifs/res/tsuilab/code/MultiQC/0.7/bin/multiqc", line 412, in multiqc
    output = mod()
  File "/ifs/res/tsuilab/code/MultiQC/0.7/lib/python2.7/site-packages/multiqc/modules/fastqc/fastqc.py", line 64, in __init__
    with fqc_zip.open(os.path.join(d_name, 'fastqc_data.txt')) as fh:
  File "/opt/common/CentOS_6/python/python-2.7.14/lib/python2.7/zipfile.py", line 971, in open
    raise BadZipfile("Bad magic number for file header")
BadZipfile: Bad magic number for file header
```

**Comment by ewels** [comment]
Hi @erikagedvilaite,

MultiQC v0.7 is extremely old (Jul 2016). Please update and see if that helps.

Note that I've seen similar issues in the past from strange zip files which have been produced in non-standard ways. A simple fix is to just unzip them manually, then it should work.

Phil

**Comment by ewels** [comment]
x-ref https://github.com/ewels/MultiQC/issues/943
