### ISSUE TITLE
The 'gatk' MultiQC module broke

### ISSUE THREAD

**Issue by xiwechen** [ewels/MultiQC#961]
**Description of bug:**
multiqc : Oops! The 'gatk' MultiQC module broke...

**MultiQC Error log:**
```
 If possible, please include a log file that triggers the error - the last file found was:
    ./MultiQC-master/multiqc/modules/gatk/varianteval.py
============================================================
Module gatk raised an exception: Traceback (most recent call last):
  File "/Users/Candyxi/Library/Python/2.7/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/Users/Candyxi/Library/Python/2.7/lib/python/site-packages/multiqc/modules/gatk/gatk.py", line 41, in __init__
    n_reports_found += self.parse_gatk_varianteval()
  File "/Users/Candyxi/Library/Python/2.7/lib/python/site-packages/multiqc/modules/gatk/varianteval.py", line 20, in parse_gatk_varianteval
    parsed_data = parse_single_report(f['f'])
  File "/Users/Candyxi/Library/Python/2.7/lib/python/site-packages/multiqc/modules/gatk/varianteval.py", line 106, in parse_single_report
    d[headers[i]] = s
IndexError: list index out of range
```

**MultiQC run details (please complete the following):**
 - Command used to run MultiQC: [multiqc ~/desktop/raw_data/ ./]
 - MultiQC Version: [MultiQC v1.7]
 - Operating System: [macOS Mojave 10.14.4]
 - Python Version: [Python 2.7.16]
 - Method of MultiQC installation: [pip]
[multiqc.log](https://github.com/ewels/MultiQC/files/3134614/multiqc.log)

**Comment by ewels** [comment]
Thanks! Please could you share an input file that triggers this error?

**Comment by xiwechen** [comment]
> Thanks! Please could you share an input file that triggers this error?

I figured that out! I missed some parts from fastqc!

Thanks!!!
