### ISSUE TITLE
report section order fails 

### ISSUE THREAD

**Issue by malhamdoosh** [ewels/MultiQC#990]
Hi there,

I was trying to change the order of sections in the multiqc report and got this error 

```
[INFO   ]  feature_counts : Found 32 reports
[INFO   ]           fastp : Found 32 reports
[INFO   ]            star : Found 32 reports
[INFO   ]        qualimap : Found 32 RNASeq reports
Traceback (most recent call last):
  File "/home/anaconda/anaconda3/envs/rnaseq-nostar/bin/multiqc", line 766, in <module>
    multiqc()
  File "/home/anaconda/anaconda3/envs/rnaseq-nostar/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/anaconda/anaconda3/envs/rnaseq-nostar/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/anaconda/anaconda3/envs/rnaseq-nostar/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/anaconda/anaconda3/envs/rnaseq-nostar/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/anaconda/anaconda3/envs/rnaseq-nostar/bin/multiqc", line 508, in multiqc
    for anchor, ss in config.report_section_order.items():
AttributeError: 'list' object has no attribute 'items'
```

The config file has the following 

```yaml
module_order:
    - fastp:
        name: 'Fastp Sequencing QC'
    - star:
        name: 'STAR Alignment Scores'
    - qualimap:
        name: 'QualiMap Alignment Quality'
    - featurecounts:
        name: 'featureCounts Read Summarization'

report_section_order:
    - fastp:
        order: -100 
    - star:
        order: -200
    - qualimap:
        order: -300
    - featurecounts:
        order: -400  
```

**Comment by ewels** [comment]
Hi @malhamdoosh,

There's a subtle difference in the yaml between `module_order` and `report_section_order` - the first is a list of dictionaries (so that it has a defined order in python 2k), and the second is just a dictionary. In other words; `report_section_order` shouldn't have the hyphens that define a list in yaml:

```yaml
report_section_order:
    fastp:
        order: -100 
    star:
        order: -200
    qualimap:
        order: -300
    featurecounts:
        order: -400 
```

This should solve your problem. Let me know if you still have difficulties though!

Phil
