### ISSUE TITLE
gatk/base_recalibrator: ZeroDivisionError

### ISSUE THREAD

**Issue by cagaser** [ewels/MultiQC#991]
```
[ERROR  ]         multiqc : Oops! The 'gatk' MultiQC module broke... 
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues 
  If possible, please include a log file that triggers the error - the last file found was:
    /exports/sascstudent/cedrick/project-223/analysis/19_germline_dna_fix/samples/wgs3_test/lib_lib1/gatk_preprocess_scatter/scatter-8.bed.bqsr
============================================================
```
```python
Module gatk raised an exception: Traceback (most recent call last):
  File "/usr/local/bin/multiqc", line 440, in multiqc
    output = mod()
  File "/usr/local/lib/python3.6/site-packages/multiqc/modules/gatk/gatk.py", line 40, in __init__
    n_reports_found += self.parse_gatk_base_recalibrator()
  File "/usr/local/lib/python3.6/site-packages/multiqc/modules/gatk/base_recalibrator.py", line 59, in parse_gatk_base_recalibrator
    self.add_quality_score_vs_no_of_observations_section()
  File "/usr/local/lib/python3.6/site-packages/multiqc/modules/gatk/base_recalibrator.py", line 89, in add_quality_score_vs_no_of_observations_section
    for sample, table in sample_tables.items()
  File "/usr/local/lib/python3.6/site-packages/multiqc/modules/gatk/base_recalibrator.py", line 89, in <dictcomp>
    for sample, table in sample_tables.items()
  File "/usr/local/lib/python3.6/site-packages/multiqc/modules/gatk/base_recalibrator.py", line 87, in <dictcomp>
    for x, y in zip(table['QualityScore'], table['Count'])
ZeroDivisionError: float division by zero

```

**Comment by ewels** [comment]
Thanks @cagaser! 

>  If possible, please include a log file that triggers the error - the last file found was:
    `/exports/sascstudent/cedrick/project-223/analysis/19_germline_dna_fix/samples/wgs3_test/lib_lib1/gatk_preprocess_scatter/scatter-8.bed.bqsr`

If you could attach this file, or another that triggers the same error, that would be very helpful for debugging.

Phil

**Comment by ewels** [comment]
Hi @cagaser,

I've just pushed code to handle this edge case so that MultiQC shouldn't fail when you have zero counts. If you're able to test it with the latest v1.8dev code, that would be great!

Thanks,

Phil
